//给角色分配用户
Ext.define('DJ.System.Customer.SubUserToRoleEdit',{
	extend:'Ext.c.SelectFrameUI',
	id:'DJ.System.Customer.SubUserToRoleEdit',
	modal:true,
	title:'分配用户',
	width:850,
	height:600,
	resizable:false,
	closable:true,
	MyConfig:{
		txtLable:"角色名称",   //设置文本宽label值
		selectbtnname:"分配",  //设置选择按钮text
		delbtnname:"取消",      //设置取消按钮text
		selecturl:"addSubUserForRole.do",          //选择按钮调用接口
		delurl:"delSubUserFromRole.do"              //删除按钮调用接口
	},
	RightConfig:{
		width:800,
		height:200,
		url:'getAllUserOfRole.do',
		objectfilterfield:'l.froleid',
		fields:[{
			name:'fid'
		},{
			name:'fname'
		},{
			name:'fcustomername'
		}],
		columns:[{
			dataIndex:'fid',
			hidden:true,
			hideable:false,
			sortable:true
		},{
			header:'用户名称',
			dataIndex:'fname',
			width:150,
			sortable:true
		},{
			header:'客户名称',
			dataIndex:'fcustomername',
			width:220,
			sortable:true
		}]
	},
	LeftConfig:{
		width:800,
		height:200,
		url:'getAllSubUser.do',
		fields:[{
			name:'fid'
		},{
			name:'fname'
		},{
			name:'fcustomername'
		}],
		columns:[{
			dataIndex:'fid',
			hidden:true,
			hideable:false,
			sortable:true
		},{
			header:'用户名称',
			dataIndex:'fname',
			width:150,
			sortable:true
		},{
			header:'客户名称',
			dataIndex:'fcustomername',
			width:220,
			sortable:true
		}]
	}
});