package Com.Entity.Finance;
// default package
// Generated 2013-11-30 14:42:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TBalPurchaseprice generated by hbm2java
 */
public class Purchaseprice implements java.io.Serializable {

	private String fid;
	private String fproductid;
	private String fcreatorid;
	private Date fcreatetime;
	private Integer fpurchaseType;

	public Purchaseprice() {
	}

	public Purchaseprice(String fid) {
		this.fid = fid;
	}

	public Purchaseprice(String fid, String fproductid, String fcreatorid,
			Date fcreatetime, Integer fpurchaseType) {
		this.fid = fid;
		this.fproductid = fproductid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fpurchaseType = fpurchaseType;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public Integer getFpurchaseType() {
		return this.fpurchaseType;
	}

	public void setFpurchaseType(Integer fpurchaseType) {
		this.fpurchaseType = fpurchaseType;
	}

}
