package com.model.saledeliver;
// default package
// Generated 2015-5-12 8:51:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TFtuSaledeliver generated by hbm2java
 */
public class FTUSaledeliver implements java.io.Serializable {

	private String fid;
	private String fsuppliername;
	private String fsupplierid;
	private String fnumber;
	private Date fcreatetime;
	private String fcreator;
	private String ffax;
	private String ftel;
	private String fdriver;
	private String fclerk;
	private String fcustomer;
	private String fphone;
	private Integer fstate = 0;
	private Date fprinttime;
	private Integer fprintcount;
	private String fcustAddress;
	private String fbusNumber;
	private String fcustomername;
	
	private String fcustname;
	public String getFcustname() {
		return fcustname;
	}

	public void setFcustname(String fcustname) {
		this.fcustname = fcustname;
	}

	public String getFproductid() {
		return fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public String getFcustoermid() {
		return fcustoermid;
	}

	public void setFcustoermid(String fcustoermid) {
		this.fcustoermid = fcustoermid;
	}

	public String getFname() {
		return fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFspec() {
		return fspec;
	}

	public void setFspec(String fspec) {
		this.fspec = fspec;
	}

	public String getFunit() {
		return funit;
	}

	public void setFunit(String funit) {
		this.funit = funit;
	}

	public String getFamount() {
		return famount;
	}

	public void setFamount(String famount) {
		this.famount = famount;
	}

	public String getFdanjia() {
		return fdanjia;
	}

	public void setFdanjia(String fdanjia) {
		this.fdanjia = fdanjia;
	}

	public String getFprice() {
		return fprice;
	}

	public void setFprice(String fprice) {
		this.fprice = fprice;
	}

	public String getFdescription() {
		return fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	private String fproductid;
	private String fcustoermid;
	private String fname;
	private String fspec;
	private String funit;
	private String famount;
	private String fdanjia;
	private String fprice;
	private String fdescription;
	public String getFcustomername() {
		return fcustomername;
	}

	public void setFcustomername(String fcustomername) {
		this.fcustomername = fcustomername;
	}

	
	public String getFcustAddress() {
		return fcustAddress;
	}

	public void setFcustAddress(String fcustAddress) {
		this.fcustAddress = fcustAddress;
	}

	public String getFbusNumber() {
		return fbusNumber;
	}

	public void setFbusNumber(String fbusNumber) {
		this.fbusNumber = fbusNumber;
	}

	public FTUSaledeliver() {
	}

	public FTUSaledeliver(String fid, String fsuppliername, String fsupplierid,
			String fnumber) {
		this.fid = fid;
		this.fsuppliername = fsuppliername;
		this.fsupplierid = fsupplierid;
		this.fnumber = fnumber;
	}

	public FTUSaledeliver(String fid, String fsuppliername, String fsupplierid,
			String fnumber, Date fcreatetime, String fcreator, String ffax,
			String ftel, String fdriver, String fclerk, String fcustomer,
			String fphone, Integer fstate, Date fprinttime, Integer fprintcount,String fbusNumber,String fcustAddress) {
		this.fid = fid;
		this.fsuppliername = fsuppliername;
		this.fsupplierid = fsupplierid;
		this.fnumber = fnumber;
		this.fcreatetime = fcreatetime;
		this.fcreator = fcreator;
		this.ffax = ffax;
		this.ftel = ftel;
		this.fdriver = fdriver;
		this.fclerk = fclerk;
		this.fcustomer = fcustomer;
		this.fphone = fphone;
		this.fstate = fstate;
		this.fprinttime = fprinttime;
		this.fprintcount = fprintcount;
		this.fbusNumber = fbusNumber;
		this.fcustAddress = fcustAddress;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFsuppliername() {
		return this.fsuppliername;
	}

	public void setFsuppliername(String fsuppliername) {
		this.fsuppliername = fsuppliername;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFcreator() {
		return this.fcreator;
	}

	public void setFcreator(String fcreator) {
		this.fcreator = fcreator;
	}

	public String getFfax() {
		return this.ffax;
	}

	public void setFfax(String ffax) {
		this.ffax = ffax;
	}

	public String getFtel() {
		return this.ftel;
	}

	public void setFtel(String ftel) {
		this.ftel = ftel;
	}

	public String getFdriver() {
		return this.fdriver;
	}

	public void setFdriver(String fdriver) {
		this.fdriver = fdriver;
	}

	public String getFclerk() {
		return this.fclerk;
	}

	public void setFclerk(String fclerk) {
		this.fclerk = fclerk;
	}

	public String getFcustomer() {
		return this.fcustomer;
	}

	public void setFcustomer(String fcustomer) {
		this.fcustomer = fcustomer;
	}

	public String getFphone() {
		return this.fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public Integer getFstate() {
		return this.fstate;
	}

	public void setFstate(Integer fstate) {
		this.fstate = fstate;
	}

	public Date getFprinttime() {
		return this.fprinttime;
	}

	public void setFprinttime(Date fprinttime) {
		this.fprinttime = fprinttime;
	}

	public Integer getFprintcount() {
		return this.fprintcount;
	}

	public void setFprintcount(Integer fprintcount) {
		this.fprintcount = fprintcount;
	}

}
