package Com.Entity.Logistics;
// default package
// Generated 2015-7-20 8:55:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TOrdCar generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private String fid;
	private Integer fcartype;
	private Float fcarKg;
	private String fcarnumber;
	private String fdrivername;
	private String fdriverphone;
	private String fcarpicture;
	private Float fdrivingexperience;
	private Float fcarlength;
	private Float fcarwidth;
	private Float fcarheight;
	private String fname;
	private String fdescription;
	private Date fcreatetime;
	private String fcreaterid;
	private String fcustomerid;
	private Float fcarage;
	private Integer fseats;

	public Car() {
	}

	public Car(String fid) {
		this.fid = fid;
	}

	public Car(String fid, Integer fcartype, Float fcarKg,
			String fcarnumber, String fdrivername, String fdriverphone,
			String fcarpicture, Float fdrivingexperience, Float fcarlength,
			Float fcarwidth, Float fcarheight, String fname,
			String fdescription, Date fcreatetime, String fcreaterid,
			String fcustomerid, Float fcarage, Integer fseats) {
		this.fid = fid;
		this.fcartype = fcartype;
		this.fcarKg = fcarKg;
		this.fcarnumber = fcarnumber;
		this.fdrivername = fdrivername;
		this.fdriverphone = fdriverphone;
		this.fcarpicture = fcarpicture;
		this.fdrivingexperience = fdrivingexperience;
		this.fcarlength = fcarlength;
		this.fcarwidth = fcarwidth;
		this.fcarheight = fcarheight;
		this.fname = fname;
		this.fdescription = fdescription;
		this.fcreatetime = fcreatetime;
		this.fcreaterid = fcreaterid;
		this.fcustomerid = fcustomerid;
		this.fcarage = fcarage;
		this.fseats = fseats;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Integer getFcartype() {
		return this.fcartype;
	}

	public void setFcartype(Integer fcartype) {
		this.fcartype = fcartype;
	}

	public Float getFcarKg() {
		return this.fcarKg;
	}

	public void setFcarKg(Float fcarKg) {
		this.fcarKg = fcarKg;
	}

	public String getFcarnumber() {
		return this.fcarnumber;
	}

	public void setFcarnumber(String fcarnumber) {
		this.fcarnumber = fcarnumber;
	}

	public String getFdrivername() {
		return this.fdrivername;
	}

	public void setFdrivername(String fdrivername) {
		this.fdrivername = fdrivername;
	}

	public String getFdriverphone() {
		return this.fdriverphone;
	}

	public void setFdriverphone(String fdriverphone) {
		this.fdriverphone = fdriverphone;
	}

	public String getFcarpicture() {
		return this.fcarpicture;
	}

	public void setFcarpicture(String fcarpicture) {
		this.fcarpicture = fcarpicture;
	}

	public Float getFdrivingexperience() {
		return this.fdrivingexperience;
	}

	public void setFdrivingexperience(Float fdrivingexperience) {
		this.fdrivingexperience = fdrivingexperience;
	}

	public Float getFcarlength() {
		return this.fcarlength;
	}

	public void setFcarlength(Float fcarlength) {
		this.fcarlength = fcarlength;
	}

	public Float getFcarwidth() {
		return this.fcarwidth;
	}

	public void setFcarwidth(Float fcarwidth) {
		this.fcarwidth = fcarwidth;
	}

	public Float getFcarheight() {
		return this.fcarheight;
	}

	public void setFcarheight(Float fcarheight) {
		this.fcarheight = fcarheight;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFcreaterid() {
		return this.fcreaterid;
	}

	public void setFcreaterid(String fcreaterid) {
		this.fcreaterid = fcreaterid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public Float getFcarage() {
		return this.fcarage;
	}

	public void setFcarage(Float fcarage) {
		this.fcarage = fcarage;
	}

	public Integer getFseats() {
		return this.fseats;
	}

	public void setFseats(Integer fseats) {
		this.fseats = fseats;
	}

}
