package Com.Entity.Logistics;
// default package
// Generated 2015-7-22 14:58:51 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TBdLogisticsaddress generated by hbm2java
 */
public class LogisticsAddress implements java.io.Serializable {

	private String fid;
	private String fname;
	private String flinkman;
	private String fphone;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private Integer ftype=0;//我的地址 1收货人地址
	private String fcustomerid;
	private Integer flasted=0;//最近使用记录

	public LogisticsAddress() {
		ftype=0;
		flasted=0;
	}

	public LogisticsAddress(String fid) {
		this.fid = fid;
	}

	public LogisticsAddress(String fid, String fname, String flinkman,
			String fphone, String fcreatorid, Date fcreatetime,
			String flastupdateuserid, Date flastupdatetime,
			Integer ftype, String fcustomerid,Integer flasted) {
		this.fid = fid;
		this.fname = fname;
		this.flinkman = flinkman;
		this.fphone = fphone;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.ftype = ftype;
		this.fcustomerid = fcustomerid;
		this.flasted=flasted;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFlinkman() {
		return this.flinkman;
	}

	public void setFlinkman(String flinkman) {
		this.flinkman = flinkman;
	}

	public String getFphone() {
		return this.fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public Integer getFtype() {
		return this.ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	/**
	 * @return the flasted
	 */
	public Integer getFlasted() {
		return flasted;
	}

	/**
	 * @param flasted the flasted to set
	 */
	public void setFlasted(Integer flasted) {
		this.flasted = flasted;
	}

}
