package Com.Entity.Logistics;
// default package
// Generated 2015-7-23 15:42:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TOrdLogisticsorder generated by hbm2java
 */
public class Logisticsorder implements java.io.Serializable {

	private String fid;
	private String fcustomerid;
	private String faddressid;
	private String flinkman;
	private String fphone;
	private String fcargoname;
	private String fcargoaddress;
	private String frecipientsname;
	private String frecipientsphone;
	private String fdriver;
	private String fdriverphone;
	private Date farrivedate;
	private Date frealityarrivetime;
	private Float fcost;
	private Integer fstate;
	private String fnumber;
	private String frecipientsaddress;
	private Date fcreatetime;
	private String fcreater;
	private String fcargotype;
	private String fcarnumber;
	private Integer fconveyingstate;
	private Integer farrivetime;
	private String fcartype;
	private String fdescription;

	public Logisticsorder() {
	}

	public Logisticsorder(String fid) {
		this.fid = fid;
	}

	public Logisticsorder(String fid, String fcustomerid,
			String faddressid, String flinkman, String fphone,
			String fcargoname, String fcargoaddress, String frecipientsname,
			String frecipientsphone, String fdriver, String fdriverphone,
			Date farrivedate, Date frealityarrivetime, Float fcost,
			Integer fstate, String fnumber, String frecipientsaddress,
			Date fcreatetime, String fcreater, String fcargotype,
			String fcarnumber, Integer fconveyingstate, Integer farrivetime,
			String fcartype, String fdescription) {
		this.fid = fid;
		this.fcustomerid = fcustomerid;
		this.faddressid = faddressid;
		this.flinkman = flinkman;
		this.fphone = fphone;
		this.fcargoname = fcargoname;
		this.fcargoaddress = fcargoaddress;
		this.frecipientsname = frecipientsname;
		this.frecipientsphone = frecipientsphone;
		this.fdriver = fdriver;
		this.fdriverphone = fdriverphone;
		this.farrivedate = farrivedate;
		this.frealityarrivetime = frealityarrivetime;
		this.fcost = fcost;
		this.fstate = fstate;
		this.fnumber = fnumber;
		this.frecipientsaddress = frecipientsaddress;
		this.fcreatetime = fcreatetime;
		this.fcreater = fcreater;
		this.fcargotype = fcargotype;
		this.fcarnumber = fcarnumber;
		this.fconveyingstate = fconveyingstate;
		this.farrivetime = farrivetime;
		this.fcartype = fcartype;
		this.fdescription = fdescription;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFaddressid() {
		return this.faddressid;
	}

	public void setFaddressid(String faddressid) {
		this.faddressid = faddressid;
	}

	public String getFlinkman() {
		return this.flinkman;
	}

	public void setFlinkman(String flinkman) {
		this.flinkman = flinkman;
	}

	public String getFphone() {
		return this.fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public String getFcargoname() {
		return this.fcargoname;
	}

	public void setFcargoname(String fcargoname) {
		this.fcargoname = fcargoname;
	}

	public String getFcargoaddress() {
		return this.fcargoaddress;
	}

	public void setFcargoaddress(String fcargoaddress) {
		this.fcargoaddress = fcargoaddress;
	}

	public String getFrecipientsname() {
		return this.frecipientsname;
	}

	public void setFrecipientsname(String frecipientsname) {
		this.frecipientsname = frecipientsname;
	}

	public String getFrecipientsphone() {
		return this.frecipientsphone;
	}

	public void setFrecipientsphone(String frecipientsphone) {
		this.frecipientsphone = frecipientsphone;
	}

	public String getFdriver() {
		return this.fdriver;
	}

	public void setFdriver(String fdriver) {
		this.fdriver = fdriver;
	}

	public String getFdriverphone() {
		return this.fdriverphone;
	}

	public void setFdriverphone(String fdriverphone) {
		this.fdriverphone = fdriverphone;
	}

	public Date getFarrivedate() {
		return this.farrivedate;
	}

	public void setFarrivedate(Date farrivedate) {
		this.farrivedate = farrivedate;
	}

	public Date getFrealityarrivetime() {
		return this.frealityarrivetime;
	}

	public void setFrealityarrivetime(Date frealityarrivetime) {
		this.frealityarrivetime = frealityarrivetime;
	}

	public Float getFcost() {
		return this.fcost;
	}

	public void setFcost(Float fcost) {
		this.fcost = fcost;
	}

	public Integer getFstate() {
		return this.fstate;
	}

	public void setFstate(Integer fstate) {
		this.fstate = fstate;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFrecipientsaddress() {
		return this.frecipientsaddress;
	}

	public void setFrecipientsaddress(String frecipientsaddress) {
		this.frecipientsaddress = frecipientsaddress;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFcreater() {
		return this.fcreater;
	}

	public void setFcreater(String fcreater) {
		this.fcreater = fcreater;
	}

	public String getFcargotype() {
		return this.fcargotype;
	}

	public void setFcargotype(String fcargotype) {
		this.fcargotype = fcargotype;
	}

	public String getFcarnumber() {
		return this.fcarnumber;
	}

	public void setFcarnumber(String fcarnumber) {
		this.fcarnumber = fcarnumber;
	}

	public Integer getFconveyingstate() {
		return this.fconveyingstate;
	}

	public void setFconveyingstate(Integer fconveyingstate) {
		this.fconveyingstate = fconveyingstate;
	}

	public Integer getFarrivetime() {
		return this.farrivetime;
	}

	public void setFarrivetime(Integer farrivetime) {
		this.farrivetime = farrivetime;
	}

	public String getFcartype() {
		return this.fcartype;
	}

	public void setFcartype(String fcartype) {
		this.fcartype = fcartype;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

}
