package Com.Entity.Logistics;
// default package
// Generated 2015-7-22 14:58:51 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TBdLogisticscarinfo generated by hbm2java
 */
public class LogisticsCarinfo implements java.io.Serializable {

	private String fid;
	private String fcargotype;
	private String fcartype;
	private String fcreatorid;
	private Date fcreatetime;
	private Integer flasted=0;
	private String fcustomerid;
	private String flastupdateuserid;
	private Date flastupdatetime;

	public LogisticsCarinfo() {
		flasted=0;
	}

	public LogisticsCarinfo(String fid) {
		this.fid = fid;
	}

	public LogisticsCarinfo(String fid, String fcargotype, String fcartype,
			String fcreatorid, Date fcreatetime, String flastupdateuserid,
			Date flastupdatetime,String fcustomerid,Integer flasted) {
		this.fid = fid;
		this.fcargotype = fcargotype;
		this.fcartype = fcartype;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.fcustomerid=fcustomerid;
		this.flasted=flasted;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}



	public String getFcartype() {
		return this.fcartype;
	}

	public void setFcartype(String fcartype) {
		this.fcartype = fcartype;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	/**
	 * @return the fcargotype
	 */
	public String getFcargotype() {
		return fcargotype;
	}

	/**
	 * @param fcargotype the fcargotype to set
	 */
	public void setFcargotype(String fcargotype) {
		this.fcargotype = fcargotype;
	}

	/**
	 * @return the flasted
	 */
	public Integer getFlasted() {
		return flasted;
	}

	/**
	 * @param flasted the flasted to set
	 */
	public void setFlasted(Integer flasted) {
		this.flasted = flasted;
	}

	/**
	 * @return the fcustomerid
	 */
	public String getFcustomerid() {
		return fcustomerid;
	}

	/**
	 * @param fcustomerid the fcustomerid to set
	 */
	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

}
