package Com.Entity.order;
// default package
// Generated 2014-12-12 14:01:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TOrdDelivers generated by hbm2java
 */
public class Delivers implements java.io.Serializable {

	private String fid;
	private String fcreatorid;
	private Date fcreatetime;
	private String fupdateuserid;
	private Date fupdatetime;
	private String fnumber;
	private String fcustomerid;
	private String fcusproductid;
	private Date farrivetime;
	private String flinkman;
	private String flinkphone;
	private Integer famount;
	private String faddress;
	private String fdescription;
	private int fordered;
	private String fordermanid;
	private Date fordertime;
	private String fsaleorderid;
	private String fordernumber;
	private String forderentryid;
	private Integer fimportEas;
	private String fimportEasuserid;
	private Date fimportEastime;
	private Integer fouted;
	private String foutorid;
	private Date fouttime;
	private String faddressid;
	private String feasdeliverid;
	private Integer fistoPlan;
	private Date fplanTime;
	private String fplanNumber;
	private String fplanid;
	private Integer falloted;
	private String fproductid;
	private String fapplayid;
	private String fapplynumber;
	private BigDecimal fbalanceprice;
	private BigDecimal fbalanceunitprice;
	private String fcusfid;
	private String ftype;
	private String ftraitid;
	private String fsupplierid;
	private String fpcmordernumber;

	public Delivers() {
		fouted=0;
		falloted=0;
		fordered=0;
		fbalanceprice=new BigDecimal("0.00");
		fbalanceunitprice=new BigDecimal("0.00");
		ftype="0";
	}

	public Delivers(String fid, int fordered) {
		this.fid = fid;
		this.fordered = fordered;
	}

	public Delivers(String fid, String fcreatorid, Date fcreatetime,
			String fupdateuserid, Date fupdatetime, String fnumber,
			String fcustomerid, String fcusproductid, Date farrivetime,
			String flinkman, String flinkphone, Integer famount,
			String faddress, String fdescription, int fordered,
			String fordermanid, Date fordertime, String fsaleorderid,
			String fordernumber, String forderentryid, Integer fimportEas,
			String fimportEasuserid, Date fimportEastime, Integer fouted,
			String foutorid, Date fouttime, String faddressid,
			String feasdeliverid, Integer fistoPlan, Date fplanTime,
			String fplanNumber, String fplanid, Integer falloted,
			String fproductid, String fapplayid, String fapplynumber,
			BigDecimal fbalanceprice, BigDecimal fbalanceunitprice,
			String fcusfid, String ftype, String ftraitid,
			String fsupplierid, String fpcmordernumber) {
		this.fid = fid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fupdateuserid = fupdateuserid;
		this.fupdatetime = fupdatetime;
		this.fnumber = fnumber;
		this.fcustomerid = fcustomerid;
		this.fcusproductid = fcusproductid;
		this.farrivetime = farrivetime;
		this.flinkman = flinkman;
		this.flinkphone = flinkphone;
		this.famount = famount;
		this.faddress = faddress;
		this.fdescription = fdescription;
		this.fordered = fordered;
		this.fordermanid = fordermanid;
		this.fordertime = fordertime;
		this.fsaleorderid = fsaleorderid;
		this.fordernumber = fordernumber;
		this.forderentryid = forderentryid;
		this.fimportEas = fimportEas;
		this.fimportEasuserid = fimportEasuserid;
		this.fimportEastime = fimportEastime;
		this.fouted = fouted;
		this.foutorid = foutorid;
		this.fouttime = fouttime;
		this.faddressid = faddressid;
		this.feasdeliverid = feasdeliverid;
		this.fistoPlan = fistoPlan;
		this.fplanTime = fplanTime;
		this.fplanNumber = fplanNumber;
		this.fplanid = fplanid;
		this.falloted = falloted;
		this.fproductid = fproductid;
		this.fapplayid = fapplayid;
		this.fapplynumber = fapplynumber;
		this.fbalanceprice = fbalanceprice;
		this.fbalanceunitprice = fbalanceunitprice;
		this.fcusfid = fcusfid;
		this.ftype = ftype;
		this.ftraitid = ftraitid;
		this.fsupplierid = fsupplierid;
		this.fpcmordernumber = fpcmordernumber;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFupdateuserid() {
		return this.fupdateuserid;
	}

	public void setFupdateuserid(String fupdateuserid) {
		this.fupdateuserid = fupdateuserid;
	}

	public Date getFupdatetime() {
		return this.fupdatetime;
	}

	public void setFupdatetime(Date fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFcusproductid() {
		return this.fcusproductid;
	}

	public void setFcusproductid(String fcusproductid) {
		this.fcusproductid = fcusproductid;
	}

	public Date getFarrivetime() {
		return this.farrivetime;
	}

	public void setFarrivetime(Date farrivetime) {
		this.farrivetime = farrivetime;
	}

	public String getFlinkman() {
		return this.flinkman;
	}

	public void setFlinkman(String flinkman) {
		this.flinkman = flinkman;
	}

	public String getFlinkphone() {
		return this.flinkphone;
	}

	public void setFlinkphone(String flinkphone) {
		this.flinkphone = flinkphone;
	}

	public Integer getFamount() {
		return this.famount;
	}

	public void setFamount(Integer famount) {
		this.famount = famount;
	}

	public String getFaddress() {
		return this.faddress;
	}

	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public int getFordered() {
		return this.fordered;
	}

	public void setFordered(int fordered) {
		this.fordered = fordered;
	}

	public String getFordermanid() {
		return this.fordermanid;
	}

	public void setFordermanid(String fordermanid) {
		this.fordermanid = fordermanid;
	}

	public Date getFordertime() {
		return this.fordertime;
	}

	public void setFordertime(Date fordertime) {
		this.fordertime = fordertime;
	}

	public String getFsaleorderid() {
		return this.fsaleorderid;
	}

	public void setFsaleorderid(String fsaleorderid) {
		this.fsaleorderid = fsaleorderid;
	}

	public String getFordernumber() {
		return this.fordernumber;
	}

	public void setFordernumber(String fordernumber) {
		this.fordernumber = fordernumber;
	}

	public String getForderentryid() {
		return this.forderentryid;
	}

	public void setForderentryid(String forderentryid) {
		this.forderentryid = forderentryid;
	}

	public Integer getFimportEas() {
		return this.fimportEas;
	}

	public void setFimportEas(Integer fimportEas) {
		this.fimportEas = fimportEas;
	}

	public String getFimportEasuserid() {
		return this.fimportEasuserid;
	}

	public void setFimportEasuserid(String fimportEasuserid) {
		this.fimportEasuserid = fimportEasuserid;
	}

	public Date getFimportEastime() {
		return this.fimportEastime;
	}

	public void setFimportEastime(Date fimportEastime) {
		this.fimportEastime = fimportEastime;
	}

	public Integer getFouted() {
		return this.fouted;
	}

	public void setFouted(Integer fouted) {
		this.fouted = fouted;
	}

	public String getFoutorid() {
		return this.foutorid;
	}

	public void setFoutorid(String foutorid) {
		this.foutorid = foutorid;
	}

	public Date getFouttime() {
		return this.fouttime;
	}

	public void setFouttime(Date fouttime) {
		this.fouttime = fouttime;
	}

	public String getFaddressid() {
		return this.faddressid;
	}

	public void setFaddressid(String faddressid) {
		this.faddressid = faddressid;
	}

	public String getFeasdeliverid() {
		return this.feasdeliverid;
	}

	public void setFeasdeliverid(String feasdeliverid) {
		this.feasdeliverid = feasdeliverid;
	}

	public Integer getFistoPlan() {
		return this.fistoPlan;
	}

	public void setFistoPlan(Integer fistoPlan) {
		this.fistoPlan = fistoPlan;
	}

	public Date getFplanTime() {
		return this.fplanTime;
	}

	public void setFplanTime(Date fplanTime) {
		this.fplanTime = fplanTime;
	}

	public String getFplanNumber() {
		return this.fplanNumber;
	}

	public void setFplanNumber(String fplanNumber) {
		this.fplanNumber = fplanNumber;
	}

	public String getFplanid() {
		return this.fplanid;
	}

	public void setFplanid(String fplanid) {
		this.fplanid = fplanid;
	}

	public Integer getFalloted() {
		return this.falloted;
	}

	public void setFalloted(Integer falloted) {
		this.falloted = falloted;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public String getFapplayid() {
		return this.fapplayid;
	}

	public void setFapplayid(String fapplayid) {
		this.fapplayid = fapplayid;
	}

	public String getFapplynumber() {
		return this.fapplynumber;
	}

	public void setFapplynumber(String fapplynumber) {
		this.fapplynumber = fapplynumber;
	}

	public BigDecimal getFbalanceprice() {
		return this.fbalanceprice;
	}

	public void setFbalanceprice(BigDecimal fbalanceprice) {
		this.fbalanceprice = fbalanceprice;
	}

	public BigDecimal getFbalanceunitprice() {
		return this.fbalanceunitprice;
	}

	public void setFbalanceunitprice(BigDecimal fbalanceunitprice) {
		this.fbalanceunitprice = fbalanceunitprice;
	}

	public String getFcusfid() {
		return this.fcusfid;
	}

	public void setFcusfid(String fcusfid) {
		this.fcusfid = fcusfid;
	}

	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public String getFtraitid() {
		return this.ftraitid;
	}

	public void setFtraitid(String ftraitid) {
		this.ftraitid = ftraitid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public String getFpcmordernumber() {
		return this.fpcmordernumber;
	}

	public void setFpcmordernumber(String fpcmordernumber) {
		this.fpcmordernumber = fpcmordernumber;
	}

}
