package Com.Entity.order;
// default package
// Generated 2013-12-21 9:39:06 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TOrdDeliverratio generated by hbm2java
 */
public class Deliverratio implements java.io.Serializable {

	private String fid;
	private String fdeliverappid;
	private String fdeliverid;
	private String fcustid;
	private BigDecimal fdelivernum;
	private BigDecimal fdeliverapplynum;

	public Deliverratio() {
		this.fdelivernum=new BigDecimal("1");
	}

	public Deliverratio(String fid) {
		this.fid = fid;
	}

	public Deliverratio(String fid, String fdeliverappid,
			String fdeliverid, BigDecimal fdelivernum,
			BigDecimal fdeliverapplynum,String fcustid) {
		this.fid = fid;
		this.fcustid=fcustid;
		this.fdeliverappid = fdeliverappid;
		this.fdeliverid = fdeliverid;
		this.fdelivernum = fdelivernum;
		this.fdeliverapplynum = fdeliverapplynum;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFdeliverappid() {
		return this.fdeliverappid;
	}

	public void setFdeliverappid(String fdeliverappid) {
		this.fdeliverappid = fdeliverappid;
	}

	public String getFdeliverid() {
		return this.fdeliverid;
	}

	public void setFdeliverid(String fdeliverid) {
		this.fdeliverid = fdeliverid;
	}

	public BigDecimal getFdelivernum() {
		return this.fdelivernum;
	}

	public void setFdelivernum(BigDecimal fdelivernum) {
		this.fdelivernum = fdelivernum;
	}

	public BigDecimal getFdeliverapplynum() {
		return this.fdeliverapplynum;
	}

	public void setFdeliverapplynum(BigDecimal fdeliverapplynum) {
		this.fdeliverapplynum = fdeliverapplynum;
	}

	public String getFcustid() {
		return fcustid;
	}

	public void setFcustid(String fcustid) {
		this.fcustid = fcustid;
	}

}
