package com.model.productdemandfile;

import java.util.Date;

// default package
// Generated 2014-8-19 13:53:31 by Hibernate Tools 3.4.0.CR1

/**
 * TOrdProductdemandfile generated by hbm2java
 */
public class Productdemandfile implements java.io.Serializable {

	private String fid;
	private String fname;
	private String ftype;
	private String fcharacter;
	private String fdescription;
	private String fpath;
	private String fparentid;
	private String fbid;
	private Date fcreatetime = new Date();

	public Productdemandfile() {
	}

	public Productdemandfile(String fid) {
		this.fid = fid;
	}

	public Productdemandfile(String fid, String fname, String ftype,
			String fcharacter, String fdescription, String fpath,
			String fparentid,Date fcreatetime) {
		this.fid = fid;
		this.fname = fname;
		this.ftype = ftype;
		this.fcharacter = fcharacter;
		this.fdescription = fdescription;
		this.fpath = fpath;
		this.fparentid = fparentid;
		this.fcreatetime = fcreatetime;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public String getFcharacter() {
		return this.fcharacter;
	}

	public void setFcharacter(String fcharacter) {
		this.fcharacter = fcharacter;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFpath() {
		return this.fpath;
	}

	public void setFpath(String fpath) {
		this.fpath = fpath;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public Date getFcreatetime() {
		return fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFbid() {
		return fbid;
	}

	public void setFbid(String fbid) {
		this.fbid = fbid;
	}

	
	
	
}
