package Com.Entity.System;
// default package
// Generated 2013-4-23 10:52:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysRole generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private String fid;
	private String fname;
	private String fnumber;
	private Integer fisdefrole;
	private Integer ftype;
	private String fcreateid;
	private Date fcratetime;
	private String fdescription;
	private String flastupdateid;
	private Date flastupdatetime;
	private String fcustomerid;


	public Role() {
	}

	public Role(String fid, String fname, String fcreateid,
			Date fcratetime, String flastupdateid, Date flastupdatetime) {
		this.fid = fid;
		this.fname = fname;
		this.fcreateid = fcreateid;
		this.fcratetime = fcratetime;
		this.flastupdateid = flastupdateid;
		this.flastupdatetime = flastupdatetime;
	}


	public Role(String fid, String fname, String fnumber, Integer fisdefrole,
			Integer ftype, String fcreateid, Date fcratetime,
			String fdescription, String flastupdateid, Date flastupdatetime,
			String fcustomerid) {
		super();
		this.fid = fid;
		this.fname = fname;
		this.fnumber = fnumber;
		this.fisdefrole = fisdefrole;
		this.ftype = ftype;
		this.fcreateid = fcreateid;
		this.fcratetime = fcratetime;
		this.fdescription = fdescription;
		this.flastupdateid = flastupdateid;
		this.flastupdatetime = flastupdatetime;
		this.fcustomerid = fcustomerid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public Integer getFisdefrole() {
		return this.fisdefrole;
	}

	public void setFisdefrole(Integer fisdefrole) {
		this.fisdefrole = fisdefrole;
	}

	public Integer getFtype() {
		return this.ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	public String getFcreateid() {
		return this.fcreateid;
	}

	public void setFcreateid(String fcreateid) {
		this.fcreateid = fcreateid;
	}

	public Date getFcratetime() {
		return this.fcratetime;
	}

	public void setFcratetime(Date fcratetime) {
		this.fcratetime = fcratetime;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFlastupdateid() {
		return this.flastupdateid;
	}

	public void setFlastupdateid(String flastupdateid) {
		this.flastupdateid = flastupdateid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public String getFcustomerid() {
		return fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}
	
	
}
