package Com.Entity.System;
// default package
// Generated 2014-3-31 10:40:41 by Hibernate Tools 3.4.0.CR1

/**
 * TPdtProductdraw generated by hbm2java
 */
public class Productdraw implements java.io.Serializable {

	private String fid;
	private String fproductId;
	private String fimagePath;
	private String fdrawnNo;
	private String fversion;

	public Productdraw() {
	}

	public Productdraw(String fid) {
		this.fid = fid;
	}

	public Productdraw(String fid, String fproductId, String fimagePath,
			String fdrawnNo, String fversion) {
		this.fid = fid;
		this.fproductId = fproductId;
		this.fimagePath = fimagePath;
		this.fdrawnNo = fdrawnNo;
		this.fversion = fversion;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFproductId() {
		return this.fproductId;
	}

	public void setFproductId(String fproductId) {
		this.fproductId = fproductId;
	}

	public String getFimagePath() {
		return this.fimagePath;
	}

	public void setFimagePath(String fimagePath) {
		this.fimagePath = fimagePath;
	}

	public String getFdrawnNo() {
		return this.fdrawnNo;
	}

	public void setFdrawnNo(String fdrawnNo) {
		this.fdrawnNo = fdrawnNo;
	}

	public String getFversion() {
		return this.fversion;
	}

	public void setFversion(String fversion) {
		this.fversion = fversion;
	}

}
