package Com.Entity.System;
// default package
// Generated 2014-8-17 12:34:12 by Hibernate Tools 3.4.0.CR1

/**
 * TOrdBoxpile generated by hbm2java
 */
public class Boxpile implements java.io.Serializable {

	private String fid;
	private String fname;
	private String fnumber;

	public Boxpile() {
	}

	public Boxpile(String fid) {
		this.fid = fid;
	}

	public Boxpile(String fid, String fname, String fnumber) {
		this.fid = fid;
		this.fname = fname;
		this.fnumber = fnumber;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber2) {
		this.fnumber = fnumber2;
	}

}
