package Com.Entity.System;
// default package
// Generated 2013-12-16 14:42:26 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TSysCuswincfg generated by hbm2java
 */
public class CusWinCfg implements java.io.Serializable {

	private String fid;
	private Integer fpositionx;
	private Integer fpositiony;
	private String ftitle;
	private BigDecimal fwidth;
	private BigDecimal fheight;
	private String ftype;
	private String fcode;
	private String fuserid;

	public CusWinCfg() {
	}

	public CusWinCfg(String fid) {
		this.fid = fid;
	}

	public CusWinCfg(String fid, Integer fpositionx, Integer fpositiony,
			String ftitle, BigDecimal fwidth, BigDecimal fheight, String ftype,
			String fcode, String fuserid) {
		this.fid = fid;
		this.fpositionx = fpositionx;
		this.fpositiony = fpositiony;
		this.ftitle = ftitle;
		this.fwidth = fwidth;
		this.fheight = fheight;
		this.ftype = ftype;
		this.fcode = fcode;
		this.fuserid = fuserid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Integer getFpositionx() {
		return this.fpositionx;
	}

	public void setFpositionx(Integer fpositionx) {
		this.fpositionx = fpositionx;
	}

	public Integer getFpositiony() {
		return this.fpositiony;
	}

	public void setFpositiony(Integer fpositiony) {
		this.fpositiony = fpositiony;
	}

	public String getFtitle() {
		return this.ftitle;
	}

	public void setFtitle(String ftitle) {
		this.ftitle = ftitle;
	}

	public BigDecimal getFwidth() {
		return this.fwidth;
	}

	public void setFwidth(BigDecimal fwidth) {
		this.fwidth = fwidth;
	}

	public BigDecimal getFheight() {
		return this.fheight;
	}

	public void setFheight(BigDecimal fheight) {
		this.fheight = fheight;
	}

	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public String getFcode() {
		return this.fcode;
	}

	public void setFcode(String fcode) {
		this.fcode = fcode;
	}

	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

}
