package com.pc.model;

// default package
// Generated 2013-4-20 13:47:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysUseronline generated by hbm2java
 */
public class Util_UserOnline implements java.io.Serializable {

	private String fuserid;//cps平台user表的fid
	private Date flogintime;
	private String fusername;
	private String fsessionid;
	private String fip;
	private String fbrowser;
	private String fsystem;
    private java.lang.Integer fuserCarId;//用于PcWeb端登录时记录司机认证状态;
    private java.lang.Integer fuserHuoId;//用于PcWeb端登录时记录货主认证状态;
    private String versionCode;
	private java.lang.Integer  fuserId;//user_role_id
	private boolean isSub;//是否子帐号
   private Integer fsubId;//管理帐号Id
   private String fsubTel;//管理帐号手机号
   private String vmiUserPhone;//用户表的手机号码
    
    public java.lang.Integer getFuserId() {
		return fuserId;
	}

	public void setFuserId(java.lang.Integer fuserId) {
		this.fuserId = fuserId;
	}

	public java.lang.Integer getFuserCarId() {
		return fuserCarId;
	}

	public void setFuserCarId(java.lang.Integer fuserCarId) {
		this.fuserCarId = fuserCarId;
	}

	public java.lang.Integer getFuserHuoId() {
		return fuserHuoId;
	}

	public void setFuserHuoId(java.lang.Integer fuserHuoId) {
		this.fuserHuoId = fuserHuoId;
	}

	public String getFsessionid() {
		return fsessionid;
	}

	public String getFip() {
		return fip;
	}

	public void setFip(String fip) {
		this.fip = fip;
	}

	public String getFbrowser() {
		return fbrowser;
	}

	public void setFbrowser(String fbrowser) {
		this.fbrowser = fbrowser;
	}

	public String getFsystem() {
		return fsystem;
	}

	public void setFsystem(String fsystem) {
		this.fsystem = fsystem;
	}

	public void setFsessionid(String fsessionid) {
		this.fsessionid = fsessionid;
	}

	public String getFusername() {
		return fusername;
	}

	public void setFusername(String fusername) {
		this.fusername = fusername;
	}

	public Util_UserOnline() {
	}

	public Util_UserOnline(String fuserid, Date flogintime,
			Date flastoperatetime) {
		this.fuserid = fuserid;
		this.flogintime = flogintime;
	}


	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public Date getFlogintime() {
		return this.flogintime;
	}

	public void setFlogintime(Date flogintime) {
		this.flogintime = flogintime;
	}

	public String getVersionCode() {
		return versionCode;
	}

	public void setVersionCode(String versionCode) {
		this.versionCode = versionCode;
	}

	public boolean isSub() {
		return isSub;
	}
	public void setSub(boolean isSub) {
		this.isSub = isSub;
	}

	public String getVmiUserPhone() {
		return vmiUserPhone;
	}

	public void setVmiUserPhone(String vmiUserPhone) {
		this.vmiUserPhone = vmiUserPhone;
	}

	public Integer getFsubId() {
		return fsubId;
	}

	public void setFsubId(Integer fsubId) {
		this.fsubId = fsubId;
	}

	public String getFsubTel() {
		return fsubTel;
	}

	public void setFsubTel(String fsubTel) {
		this.fsubTel = fsubTel;
	}


}
