package Com.Entity.Finance;
// default package
// Generated 2013-11-21 10:33:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TBalBalanceprice generated by hbm2java
 */
public class Balanceprice implements java.io.Serializable {

	private String fid;
	private String fproductid;
	private String fcreatorid;
	private Date fcreatetime;
	private Integer fbalancetype; 

	public Balanceprice() {
	}

	public Balanceprice(String fid) {
		this.fid = fid;
	}

	public Balanceprice(String fid, String fproductid, String fcreatorid,
			Date fcreatetime,Integer fbalancetype) {
		this.fid = fid;
		this.fproductid = fproductid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fbalancetype=fbalancetype;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public Integer getFbalancetype() {
		return fbalancetype;
	}

	public void setFbalancetype(Integer fbalancetype) {
		this.fbalancetype = fbalancetype;
	}

}
