package Com.Entity.Inv;
// default package
// Generated 2014-12-6 8:44:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TInvProductcheck generated by hbm2java
 */
public class Productcheck implements java.io.Serializable {

	private String fid;
	private Date fcreatetime;
	private Date fupdatetime;
	private String fuserid;
	private Byte fstate;
	private String fremark;
	private String fnumber;

	public Productcheck() {
	}

	public Productcheck(String fid) {
		this.fid = fid;
	}

	public Productcheck(String fid, Date fcreatetime, Date fupdatetime,
			String fuserid, Byte fstate, String fremark, String fnumber) {
		this.fid = fid;
		this.fcreatetime = fcreatetime;
		this.fupdatetime = fupdatetime;
		this.fuserid = fuserid;
		this.fstate = fstate;
		this.fremark = fremark;
		this.fnumber = fnumber;
	}

	
	
	public String getFnumber() {
		return fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public Date getFupdatetime() {
		return this.fupdatetime;
	}

	public void setFupdatetime(Date fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public Byte getFstate() {
		return this.fstate;
	}

	public void setFstate(Byte fstate) {
		this.fstate = fstate;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

}
