package Com.Entity.Inv;
// default package
// Generated 2014-6-17 14:50:46 by Hibernate Tools 3.4.0.CR1

/**
 * TInvUsedstorebalance generated by hbm2java
 */
public class Usedstorebalance implements java.io.Serializable,Cloneable {

	private String fid;
	private Integer fratio=1;
	private Integer fusedqty=0;
	private String fdeliverorderid;
	private String fstorebalanceid;
	private String fproductid;
	private Integer ftype;

	public Usedstorebalance() {
		fusedqty=0;
		fratio=1;
	}

	public Usedstorebalance(String fid) {
		this.fid = fid;
	}

	public Usedstorebalance(String fid, Integer fratio, Integer fusedqty,
			String fdeliverorderid, String fstorebalanceid, String fproductid,
			Integer ftype) {
		this.fid = fid;
		this.fratio = fratio;
		this.fusedqty = fusedqty;
		this.fdeliverorderid = fdeliverorderid;
		this.fstorebalanceid = fstorebalanceid;
		this.fproductid = fproductid;
		this.ftype = ftype;
	}
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Integer getFratio() {
		return this.fratio;
	}

	public void setFratio(Integer fratio) {
		this.fratio = fratio;
	}

	public Integer getFusedqty() {
		return this.fusedqty;
	}

	public void setFusedqty(Integer fusedqty) {
		this.fusedqty = fusedqty;
	}

	public String getFdeliverorderid() {
		return this.fdeliverorderid;
	}

	public void setFdeliverorderid(String fdeliverorderid) {
		this.fdeliverorderid = fdeliverorderid;
	}

	public String getFstorebalanceid() {
		return this.fstorebalanceid;
	}

	public void setFstorebalanceid(String fstorebalanceid) {
		this.fstorebalanceid = fstorebalanceid;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public Integer getFtype() {
		return this.ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

}
