package Com.Entity.Inv;
// default package
// Generated 2013-6-26 8:47:41 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TBdWarehousesites generated by hbm2java
 */
public class Warehousesites implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private String faddress;
	private String fname;
	private Integer fseq;
	private String fparentid;
	private String fremark;
	private BigDecimal finstoreprice;
	private BigDecimal foutstoreprice;
	private BigDecimal farea;

	public Warehousesites() {
	}

	public Warehousesites(String fid, String fparentid) {
		this.fid = fid;
		this.fparentid = fparentid;
	}

	public Warehousesites(String fid, String fnumber, String fcreatorid,
			Date fcreatetime, String flastupdateuserid, Date flastupdatetime,
			String faddress, String fname, Integer fseq, String fparentid,
			String fremark, BigDecimal finstoreprice,
			BigDecimal foutstoreprice, BigDecimal farea) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.faddress = faddress;
		this.fname = fname;
		this.fseq = fseq;
		this.fparentid = fparentid;
		this.fremark = fremark;
		this.finstoreprice = finstoreprice;
		this.foutstoreprice = foutstoreprice;
		this.farea = farea;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public String getFaddress() {
		return this.faddress;
	}

	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public Integer getFseq() {
		return this.fseq;
	}

	public void setFseq(Integer fseq) {
		this.fseq = fseq;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

	public BigDecimal getFinstoreprice() {
		return this.finstoreprice;
	}

	public void setFinstoreprice(BigDecimal finstoreprice) {
		this.finstoreprice = finstoreprice;
	}

	public BigDecimal getFoutstoreprice() {
		return this.foutstoreprice;
	}

	public void setFoutstoreprice(BigDecimal foutstoreprice) {
		this.foutstoreprice = foutstoreprice;
	}

	public BigDecimal getFarea() {
		return this.farea;
	}

	public void setFarea(BigDecimal farea) {
		this.farea = farea;
	}

}
