package com.model.productdef;
// default package
// Generated 2013-9-21 8:41:03 by Hibernate Tools 3.4.0.CR1

/**
 * TPdtProductdef generated by hbm2java
 */
public class ProductdefProducts implements java.io.Serializable {

	private String fid;
	private Integer fseq ;
	private String fparentid;
	private String fproductid;
	private Integer famount;
	private String fremark;
	public ProductdefProducts() {
	}
	public String getFid() {
		return fid;
	}
	public void setFid(String fid) {
		this.fid = fid;
	}
	public Integer getFseq() {
		return fseq;
	}
	public void setFseq(Integer fseq) {
		this.fseq = fseq;
	}
	public String getFparentid() {
		return fparentid;
	}
	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}
	public String getFproductid() {
		return fproductid;
	}
	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}
	public Integer getFamount() {
		return famount;
	}
	public void setFamount(Integer famount) {
		this.famount = famount;
	}
	public String getFremark() {
		return fremark;
	}
	public void setFremark(String fremark) {
		this.fremark = fremark;
	}


}
