package Com.Entity.System;
// default package
// Generated 2013-10-24 17:13:36 by Hibernate Tools 3.4.0.CR1

/**
 * TPdtCustrelation generated by hbm2java
 */
public class Custrelation implements java.io.Serializable {

	private String fid;
	private String fcustomerid;
	private String fcustproductid;

	public Custrelation() {
	}

	public Custrelation(String fid, String fcustomerid,
			String fcustproductid) {
		this.fid = fid;
		this.fcustomerid = fcustomerid;
		this.fcustproductid = fcustproductid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFcustproductid() {
		return this.fcustproductid;
	}

	public void setFcustproductid(String fcustproductid) {
		this.fcustproductid = fcustproductid;
	}

}
