package com.model.custproduct;
// default package
// Generated 2013-10-24 17:13:36 by Hibernate Tools 3.4.0.CR1

/**
 * TPdtCustrelationentry generated by hbm2java
 */
public class Custrelationentry implements java.io.Serializable {

	private String fid;
	private Integer fseq;
	private String fparentid;
	private String fproductid;
	private Integer famount;
	private String fremark;

	public Custrelationentry() {
	}

	public Custrelationentry(String fid, String fparentid) {
		this.fid = fid;
		this.fparentid = fparentid;
	}

	public Custrelationentry(String fid, Integer fseq, String fparentid,
			String fproductid, Integer famount, String fremark) {
		this.fid = fid;
		this.fseq = fseq;
		this.fparentid = fparentid;
		this.fproductid = fproductid;
		this.famount = famount;
		this.fremark = fremark;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Integer getFseq() {
		return this.fseq;
	}

	public void setFseq(Integer fseq) {
		this.fseq = fseq;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public Integer getFamount() {
		return this.famount;
	}

	public void setFamount(Integer famount) {
		this.famount = famount;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

}
