package Com.Entity.Inv;
// default package
// Generated 2013-6-26 8:47:41 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TBdWarehouse generated by hbm2java
 */
public class Warehouse implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private String fsimplename;
	private String fcontrollerid;
	private String faddress;
	private BigDecimal foutstorage;
	private BigDecimal finstorage;
	private String fname;
	private String fdescription;
	private int fwarehousetype;
	private BigDecimal cffreightprice;
	private String cfaddresid;

	public Warehouse() {
	}

	public Warehouse(String fid, int fwarehousetype) {
		this.fid = fid;
		this.fwarehousetype = fwarehousetype;
	}

	public Warehouse(String fid, String fnumber, String fcreatorid,
			Date fcreatetime, String flastupdateuserid, Date flastupdatetime,
			String fsimplename, String fcontrollerid, String faddress,
			BigDecimal foutstorage, BigDecimal finstorage, String fname,
			String fdescription, int fwarehousetype, BigDecimal cffreightprice,
			String cfaddresid) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.fsimplename = fsimplename;
		this.fcontrollerid = fcontrollerid;
		this.faddress = faddress;
		this.foutstorage = foutstorage;
		this.finstorage = finstorage;
		this.fname = fname;
		this.fdescription = fdescription;
		this.fwarehousetype = fwarehousetype;
		this.cffreightprice = cffreightprice;
		this.cfaddresid = cfaddresid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public String getFsimplename() {
		return this.fsimplename;
	}

	public void setFsimplename(String fsimplename) {
		this.fsimplename = fsimplename;
	}

	public String getFcontrollerid() {
		return this.fcontrollerid;
	}

	public void setFcontrollerid(String fcontrollerid) {
		this.fcontrollerid = fcontrollerid;
	}

	public String getFaddress() {
		return this.faddress;
	}

	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	public BigDecimal getFoutstorage() {
		return this.foutstorage;
	}

	public void setFoutstorage(BigDecimal foutstorage) {
		this.foutstorage = foutstorage;
	}

	public BigDecimal getFinstorage() {
		return this.finstorage;
	}

	public void setFinstorage(BigDecimal finstorage) {
		this.finstorage = finstorage;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public int getFwarehousetype() {
		return this.fwarehousetype;
	}

	public void setFwarehousetype(int fwarehousetype) {
		this.fwarehousetype = fwarehousetype;
	}

	public BigDecimal getCffreightprice() {
		return this.cffreightprice;
	}

	public void setCffreightprice(BigDecimal cffreightprice) {
		this.cffreightprice = cffreightprice;
	}

	public String getCfaddresid() {
		return this.cfaddresid;
	}

	public void setCfaddresid(String cfaddresid) {
		this.cfaddresid = cfaddresid;
	}

}
