package Com.Entity.Finance;
// default package
// Generated 2013-11-21 10:33:52 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TBalBalancepricecustprices generated by hbm2java
 */
public class Balancepricecustprices implements java.io.Serializable {

	private String fid;
	private String fparentid;
	private String fcustomerid;
	private Integer flowerlimit;
	private Integer fupperlimit;
	private Date fstartdate;
	private Date fenddate;
	private BigDecimal fprice;
	private String fremark;
	private int fiseffect;

	public Balancepricecustprices() {
	}

	public Balancepricecustprices(String fid, String fparentid,
			int fiseffect) {
		this.fid = fid;
		this.fparentid = fparentid;
		this.fiseffect = fiseffect;
	}

	public Balancepricecustprices(String fid, String fparentid,
			String fcustomerid, Integer flowerlimit, Integer fupperlimit,
			Date fstartdate, Date fenddate, BigDecimal fprice, String fremark,
			int fiseffect) {
		this.fid = fid;
		this.fparentid = fparentid;
		this.fcustomerid = fcustomerid;
		this.flowerlimit = flowerlimit;
		this.fupperlimit = fupperlimit;
		this.fstartdate = fstartdate;
		this.fenddate = fenddate;
		this.fprice = fprice;
		this.fremark = fremark;
		this.fiseffect = fiseffect;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public Integer getFlowerlimit() {
		return this.flowerlimit;
	}

	public void setFlowerlimit(Integer flowerlimit) {
		this.flowerlimit = flowerlimit;
	}

	public Integer getFupperlimit() {
		return this.fupperlimit;
	}

	public void setFupperlimit(Integer fupperlimit) {
		this.fupperlimit = fupperlimit;
	}

	public Date getFstartdate() {
		return this.fstartdate;
	}

	public void setFstartdate(Date fstartdate) {
		this.fstartdate = fstartdate;
	}

	public Date getFenddate() {
		return this.fenddate;
	}

	public void setFenddate(Date fenddate) {
		this.fenddate = fenddate;
	}

	public BigDecimal getFprice() {
		return this.fprice;
	}

	public void setFprice(BigDecimal fprice) {
		this.fprice = fprice;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

	public int getFiseffect() {
		return this.fiseffect;
	}

	public void setFiseffect(int fiseffect) {
		this.fiseffect = fiseffect;
	}

}
