package Com.Entity.Finance;
// default package
// Generated 2014-1-2 16:19:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TBalCustbalanceprice generated by hbm2java
 */
public class Custbalanceprice implements java.io.Serializable {

	private String fid;
	private String fcustproductid;
	private String fcreatorid;
	private Date fcreatetime;
	private Integer fbalancetype;

	public Custbalanceprice() {
	}

	public Custbalanceprice(String fid) {
		this.fid = fid;
	}

	public Custbalanceprice(String fid, String fcustproductid,
			String fcreatorid, Date fcreatetime, Integer fbalancetype) {
		this.fid = fid;
		this.fcustproductid = fcustproductid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fbalancetype = fbalancetype;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcustproductid() {
		return this.fcustproductid;
	}

	public void setFcustproductid(String fcustproductid) {
		this.fcustproductid = fcustproductid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public Integer getFbalancetype() {
		return this.fbalancetype;
	}

	public void setFbalancetype(Integer fbalancetype) {
		this.fbalancetype = fbalancetype;
	}

}
