package Com.Entity.Finance;
// default package
// Generated 2013-11-30 14:42:19 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TBalPurchaseourprice generated by hbm2java
 */
public class Purchaseourprice implements java.io.Serializable {

	private String fid;
	private String fparentid;
	private BigDecimal flowerlimit;
	private BigDecimal fupperlimit;
	private BigDecimal fprice;
	private String fremark;
	private Date fstartdate;
	private Date fenddate;
	private int fiseffect;

	public Purchaseourprice() {
	}

	public Purchaseourprice(String fid, String fparentid, int fiseffect) {
		this.fid = fid;
		this.fparentid = fparentid;
		this.fiseffect = fiseffect;
	}

	public Purchaseourprice(String fid, String fparentid,
			BigDecimal flowerlimit, BigDecimal fupperlimit, BigDecimal fprice,
			String fremark, Date fstartdate, Date fenddate, int fiseffect) {
		this.fid = fid;
		this.fparentid = fparentid;
		this.flowerlimit = flowerlimit;
		this.fupperlimit = fupperlimit;
		this.fprice = fprice;
		this.fremark = fremark;
		this.fstartdate = fstartdate;
		this.fenddate = fenddate;
		this.fiseffect = fiseffect;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public BigDecimal getFlowerlimit() {
		return this.flowerlimit;
	}

	public void setFlowerlimit(BigDecimal flowerlimit) {
		this.flowerlimit = flowerlimit;
	}

	public BigDecimal getFupperlimit() {
		return this.fupperlimit;
	}

	public void setFupperlimit(BigDecimal fupperlimit) {
		this.fupperlimit = fupperlimit;
	}

	public BigDecimal getFprice() {
		return this.fprice;
	}

	public void setFprice(BigDecimal fprice) {
		this.fprice = fprice;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

	public Date getFstartdate() {
		return this.fstartdate;
	}

	public void setFstartdate(Date fstartdate) {
		this.fstartdate = fstartdate;
	}

	public Date getFenddate() {
		return this.fenddate;
	}

	public void setFenddate(Date fenddate) {
		this.fenddate = fenddate;
	}

	public int getFiseffect() {
		return this.fiseffect;
	}

	public void setFiseffect(int fiseffect) {
		this.fiseffect = fiseffect;
	}

}
