package Com.Entity.traffic;
// default package
// Generated 2014-1-15 13:31:56 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TTraTruckassembleentry generated by hbm2java
 */
public class Truckassembleentry implements java.io.Serializable {

	private String fid;
	private Integer fseq;
	private Integer fdeliveryed;
	private String fparentid;
	private String fsaleorderid;
	private String fdeliverorderid;
	private String fsupplierid;
	private String fproductid;
	private String fproductspec;
	private BigDecimal famount;
	private String freceiveaddress;
	private String freceiver;
	private String freceiverphone;
	private String fdeliveryaddress;
	private String fdelivery;
	private String fdeliveryphone;
	private String fremark;
	private String feasid;
	private String fcustomerid;
	private Integer fouted;
	private Date fouttime;
	private String foutor;

	public Truckassembleentry() {
		this.fouted=0;
	}

	public Truckassembleentry(String fid) {
		this.fid = fid;
	}

	public Truckassembleentry(String fid, Integer fseq,
			Integer fdeliveryed, String fparentid, String fsaleorderid,
			String fdeliverorderid, String fsupplierid, String fproductid,
			String fproductspec, BigDecimal famount, String freceiveaddress,
			String freceiver, String freceiverphone, String fdeliveryaddress,
			String fdelivery, String fdeliveryphone, String fremark,
			String feasid, String fcustomerid, Integer fouted, Date fouttime,
			String foutor) {
		this.fid = fid;
		this.fseq = fseq;
		this.fdeliveryed = fdeliveryed;
		this.fparentid = fparentid;
		this.fsaleorderid = fsaleorderid;
		this.fdeliverorderid = fdeliverorderid;
		this.fsupplierid = fsupplierid;
		this.fproductid = fproductid;
		this.fproductspec = fproductspec;
		this.famount = famount;
		this.freceiveaddress = freceiveaddress;
		this.freceiver = freceiver;
		this.freceiverphone = freceiverphone;
		this.fdeliveryaddress = fdeliveryaddress;
		this.fdelivery = fdelivery;
		this.fdeliveryphone = fdeliveryphone;
		this.fremark = fremark;
		this.feasid = feasid;
		this.fcustomerid = fcustomerid;
		this.fouted = fouted;
		this.fouttime = fouttime;
		this.foutor = foutor;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Integer getFseq() {
		return this.fseq;
	}

	public void setFseq(Integer fseq) {
		this.fseq = fseq;
	}

	public Integer getFdeliveryed() {
		return this.fdeliveryed;
	}

	public void setFdeliveryed(Integer fdeliveryed) {
		this.fdeliveryed = fdeliveryed;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public String getFsaleorderid() {
		return this.fsaleorderid;
	}

	public void setFsaleorderid(String fsaleorderid) {
		this.fsaleorderid = fsaleorderid;
	}

	public String getFdeliverorderid() {
		return this.fdeliverorderid;
	}

	public void setFdeliverorderid(String fdeliverorderid) {
		this.fdeliverorderid = fdeliverorderid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public String getFproductspec() {
		return this.fproductspec;
	}

	public void setFproductspec(String fproductspec) {
		this.fproductspec = fproductspec;
	}

	public BigDecimal getFamount() {
		return this.famount;
	}

	public void setFamount(BigDecimal famount) {
		this.famount = famount;
	}

	public String getFreceiveaddress() {
		return this.freceiveaddress;
	}

	public void setFreceiveaddress(String freceiveaddress) {
		this.freceiveaddress = freceiveaddress;
	}

	public String getFreceiver() {
		return this.freceiver;
	}

	public void setFreceiver(String freceiver) {
		this.freceiver = freceiver;
	}

	public String getFreceiverphone() {
		return this.freceiverphone;
	}

	public void setFreceiverphone(String freceiverphone) {
		this.freceiverphone = freceiverphone;
	}

	public String getFdeliveryaddress() {
		return this.fdeliveryaddress;
	}

	public void setFdeliveryaddress(String fdeliveryaddress) {
		this.fdeliveryaddress = fdeliveryaddress;
	}

	public String getFdelivery() {
		return this.fdelivery;
	}

	public void setFdelivery(String fdelivery) {
		this.fdelivery = fdelivery;
	}

	public String getFdeliveryphone() {
		return this.fdeliveryphone;
	}

	public void setFdeliveryphone(String fdeliveryphone) {
		this.fdeliveryphone = fdeliveryphone;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

	public String getFeasid() {
		return this.feasid;
	}

	public void setFeasid(String feasid) {
		this.feasid = feasid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public Integer getFouted() {
		return this.fouted;
	}

	public void setFouted(Integer fouted) {
		this.fouted = fouted;
	}

	public Date getFouttime() {
		return this.fouttime;
	}

	public void setFouttime(Date fouttime) {
		this.fouttime = fouttime;
	}

	public String getFoutor() {
		return this.foutor;
	}

	public void setFoutor(String foutor) {
		this.foutor = foutor;
	}

}
