package Com.Entity.traffic;
// default package
// Generated 2014-1-15 13:31:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTraTruckassemble generated by hbm2java
 */
public class Truckassemble implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private Date fbizdate;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private String ftruckid;
	private String feasid;
	private String fsupplier;
	private Integer ftype;
	private Integer faudited;
	private String fexternalNum;
	private String fdriverid;
	private String fphone;
	

	public Truckassemble() {
	}

	public Truckassemble(String fid) {
		this.fid = fid;
	}

	public Truckassemble(String fid, String fnumber, Date fbizdate,
			String fcreatorid, Date fcreatetime, String flastupdateuserid,
			Date flastupdatetime, String ftruckid, String feasid,
			String fsupplier, Integer ftype, Integer faudited,String fexternalNum,String fdriverid,String fphone) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fbizdate = fbizdate;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.ftruckid = ftruckid;
		this.feasid = feasid;
		this.fsupplier = fsupplier;
		this.ftype = ftype;
		this.faudited = faudited;
		this.fexternalNum=fexternalNum;
		this.fdriverid=fdriverid;
		this.fphone=fphone;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public Date getFbizdate() {
		return this.fbizdate;
	}

	public void setFbizdate(Date fbizdate) {
		this.fbizdate = fbizdate;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public String getFtruckid() {
		return this.ftruckid;
	}

	public void setFtruckid(String ftruckid) {
		this.ftruckid = ftruckid;
	}

	public String getFeasid() {
		return this.feasid;
	}

	public void setFeasid(String feasid) {
		this.feasid = feasid;
	}

	public String getFsupplier() {
		return this.fsupplier;
	}

	public void setFsupplier(String fsupplier) {
		this.fsupplier = fsupplier;
	}

	public Integer getFtype() {
		return this.ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	public Integer getFaudited() {
		return this.faudited;
	}

	public void setFaudited(Integer faudited) {
		this.faudited = faudited;
	}

	/**
	 * @return the fexternalNum
	 */
	public String getFexternalNum() {
		return fexternalNum;
	}

	/**
	 * @param fexternalNum the fexternalNum to set
	 */
	public void setFexternalNum(String fexternalNum) {
		this.fexternalNum = fexternalNum;
	}

	/**
	 * @return the fdriverid
	 */
	public String getFdriverid() {
		return fdriverid;
	}

	/**
	 * @param fdriverid the fdriverid to set
	 */
	public void setFdriverid(String fdriverid) {
		this.fdriverid = fdriverid;
	}

	/**
	 * @return the fphone
	 */
	public String getFphone() {
		return fphone;
	}

	/**
	 * @param fphone the fphone to set
	 */
	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

}
