package Com.Entity.System;
// default package
// Generated 2014-4-11 9:06:53 by Hibernate Tools 3.4.0.CR1

/**
 * TSysSupplierjudgement generated by hbm2java
 */
public class Supplierjudgement implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private String fname;
	private Double frate;

	public Supplierjudgement() {
	}

	public Supplierjudgement(String fid) {
		this.fid = fid;
	}

	public Supplierjudgement(String fid, String fnumber, String fname,
			Double frate) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fname = fname;
		this.frate = frate;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public Double getFrate() {
		return this.frate;
	}

	public void setFrate(Double frate) {
		this.frate = frate;
	}

}
