package com.model.firstproductdemand;
// default package
// Generated 2014-12-15 12:06:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TOrdFirstproductdemand generated by hbm2java
 */
public class Firstproductdemand implements java.io.Serializable {

	private String fid;                    /*** 主键*/
	private String fnumber;                /*** 编码*/
	private String fdescription;           /*** 需求描述*/
	private BigDecimal fboxlength;         /*** 纸箱长（暂时无用）*/
	private BigDecimal fboxwidth;          /*** 纸箱宽（暂时无用）*/
	private BigDecimal fboxheight;         /*** 纸箱高（暂时无用）*/
	private BigDecimal fboardlength;       /*** 纸板长（暂时无用）*/
	private BigDecimal fboardwidth;        /*** 纸板宽（暂时无用）*/
	private String fcreatid;               /*** 创建人*/
	private Date fcreatetime;              /*** 创建时间*/
	private String fupdateuserid;          /*** 修改人*/
	private Date fupdatetime;              /*** 修改时间*/
	private String fauditorid;             /*** 发布人*/
	private Date fauditortime;             /*** 发布时间*/
	private Boolean isfauditor;            /*** 是否发布*/
	private String fcustomerid;            /*** 客户*/
	private String fsupplierid;            /*** 制造商*/
	private Boolean falloted;              /*** 是否分配*/
	private String fallotor;               /*** 分配人*/
	private Date fallottime;               /*** 分配时间*/
	private Boolean freceived;             /*** 是否接收*/
	private String freceiver;              /*** 接收人*/
	private Date freceivetime;             /*** 接收时间*/
	private String fname;                  /*** 需求名称*/
	private Integer ftype;                 /*** 需求类别（暂时无用）0新产品包装设计，1老产品包装技改*/
	private String fcostneed;              /*** 成本要求（暂时无用）*/
	private Boolean fiszhiyang;            /*** 是否制样0:否,1:是*/
	private Integer famount;               /*** 订单数量*/
	private Date foverdate;                /*** 方案入库日期*/
	private Date farrivetime;              /*** 发货日期*/
	private String fboxpileid;             /*** 箱型（暂时无用）*/
	private String fmaterial;              /*** 材料（暂时无用）*/
	private Integer fcorrugated;           /*** 楞型（暂时无用）*/
	private String fprintcolor;            /*** 印刷颜色（暂时无用）*/
	private String fprintbarcode;          /*** 印刷条形码（暂时无用）*/
	private Integer funitestyle;           /*** 结合方式（暂时无用）*/
	private Integer fprintstyle;           /*** 印刷方式（暂时无用）*/
	private Integer fsurfacetreatment;     /*** 表面处理（暂时无用）*/
	private String fpackstyle;             /*** 打包方式（暂时无用）*/
	private String fpackdescription;       /*** 打包描述（暂时无用）*/
	private Boolean fisclean;              /*** 是否清废（暂时无用）*/
	private Boolean fispackage;            /*** 是否组装（暂时无用）*/
	private String fpackagedescription;    /*** 组装描述（暂时无用）*/
	private Boolean fislettering;          /*** 是否刻字（暂时无用）*/
	private String fletteringescription;   /*** 刻字描述（暂时无用）*/
	private String flinkphone;             /*** 联系电话*/
	private String flinkman;               /*** 联系人*/
	private Boolean fisaccessory = false;  /*** 是否有附件*/
	private String fstate;                 /*** 需求状态*/
	private Date fclosetime;               /*** */
	private String fcloseuserid;           /*** */
	private String fcloseprevstate;        /*** */
	private String fpreproductdemandid;    /*** */
	private Integer fisdemandpackage=0;          /*** 是否需求包，0为否,1为是*/
	private String fpurordernumber;    
	private String fdesignproviderid;		/**设计商  默认东经**/ 
    private String fresourceschemeid;      
    public String getFresourceschemeid() {
		return fresourceschemeid;
	}

	public void setFresourceschemeid(String fresourceschemeid) {
		this.fresourceschemeid = fresourceschemeid;
	}

	/**快速设计的来源明星方案**/   
	public String getFpurordernumber() {
		return fpurordernumber;
	}

	public void setFpurordernumber(String fpurordernumber) {
		this.fpurordernumber = fpurordernumber;
	}

	/*** 采购单号*/
	
	///////////////////////用于封装数据与实际数据库字段无关联/////////////开始//////////////////////
	private String  fqq;//QQ号码
	private String  customerName;//客户名称
	private String  freceiverTel;//接收人电话
	private String  supplierName;//制造商名称
	private String  fgroupid;
	private String freceivetimeString;
	private String fauditortimeString;
	private String foverdateString;
	private String farrivetimeString;
	private String fisaccessoryString;
	private String fTimeString;
	private String latestpathImg;


	public String getLatestpathImg() {
		return latestpathImg;
	}

	public void setLatestpathImg(String latestpathImg) {
		this.latestpathImg = latestpathImg;
	}

	public String getFarrivetimeString() {
		return farrivetimeString;
	}

	public void setFarrivetimeString(String farrivetimeString) {
		this.farrivetimeString = farrivetimeString;
	}

	public String getfTimeString() {
		return fTimeString;
	}

	public void setfTimeString(String fTimeString) {
		this.fTimeString = fTimeString;
	}

	public String getFisaccessoryString() {
		return fisaccessoryString;
	}

	public void setFisaccessoryString(String fisaccessoryString) {
		this.fisaccessoryString = fisaccessoryString;
	}

	public String getFqq() {
		return fqq;
	}

	public void setFqq(String fqq) {
		this.fqq = fqq;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getFreceiverTel() {
		return freceiverTel;
	}

	public void setFreceiverTel(String freceiverTel) {
		this.freceiverTel = freceiverTel;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}
	public String getFgroupid() {
		return fgroupid;
	}

	public void setFgroupid(String fgroupid) {
		this.fgroupid = fgroupid;
	}

	public String getFreceivetimeString() {
		return freceivetimeString;
	}

	public void setFreceivetimeString(String freceivetimeString) {
		this.freceivetimeString = freceivetimeString;
	}

	public String getFauditortimeString() {
		return fauditortimeString;
	}

	public void setFauditortimeString(String fauditortimeString) {
		this.fauditortimeString = fauditortimeString;
	}

	public String getFoverdateString() {
		return foverdateString;
	}

	public void setFoverdateString(String foverdateString) {
		this.foverdateString = foverdateString;
	}
	///////////////////////用于封装数据与实际数据库字段无关联/////////////结束//////////////////////

	public Firstproductdemand() {
	}

	public Firstproductdemand(String fid) {
		this.fid = fid;
	}

	public Firstproductdemand(String fid, String fnumber,
			String fdescription, BigDecimal fboxlength, BigDecimal fboxwidth,
			BigDecimal fboxheight, BigDecimal fboardlength,
			BigDecimal fboardwidth, String fcreatid, Date fcreatetime,
			String fupdateuserid, Date fupdatetime, String fauditorid,
			Date fauditortime, Boolean isfauditor, String fcustomerid,
			String fsupplierid, Boolean falloted, String fallotor,
			Date fallottime, Boolean freceived, String freceiver,
			Date freceivetime, String fname, Integer ftype, String fcostneed,
			Boolean fiszhiyang, Integer famount, Date foverdate,
			Date farrivetime, String fboxpileid, String fmaterial,
			Integer fcorrugated, String fprintcolor, String fprintbarcode,
			Integer funitestyle, Integer fprintstyle,
			Integer fsurfacetreatment, String fpackstyle,
			String fpackdescription, Boolean fisclean, Boolean fispackage,
			String fpackagedescription, Boolean fislettering,
			String fletteringescription, String flinkphone, String flinkman,
			Boolean fisaccessory, String fstate, Date fclosetime,
			String fcloseuserid, String fcloseprevstate,String fdesignproviderid) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fdescription = fdescription;
		this.fboxlength = fboxlength;
		this.fboxwidth = fboxwidth;
		this.fboxheight = fboxheight;
		this.fboardlength = fboardlength;
		this.fboardwidth = fboardwidth;
		this.fcreatid = fcreatid;
		this.fcreatetime = fcreatetime;
		this.fupdateuserid = fupdateuserid;
		this.fupdatetime = fupdatetime;
		this.fauditorid = fauditorid;
		this.fauditortime = fauditortime;
		this.isfauditor = isfauditor;
		this.fcustomerid = fcustomerid;
		this.fsupplierid = fsupplierid;
		this.falloted = falloted;
		this.fallotor = fallotor;
		this.fallottime = fallottime;
		this.freceived = freceived;
		this.freceiver = freceiver;
		this.freceivetime = freceivetime;
		this.fname = fname;
		this.ftype = ftype;
		this.fcostneed = fcostneed;
		this.fiszhiyang = fiszhiyang;
		this.famount = famount;
		this.foverdate = foverdate;
		this.farrivetime = farrivetime;
		this.fboxpileid = fboxpileid;
		this.fmaterial = fmaterial;
		this.fcorrugated = fcorrugated;
		this.fprintcolor = fprintcolor;
		this.fprintbarcode = fprintbarcode;
		this.funitestyle = funitestyle;
		this.fprintstyle = fprintstyle;
		this.fsurfacetreatment = fsurfacetreatment;
		this.fpackstyle = fpackstyle;
		this.fpackdescription = fpackdescription;
		this.fisclean = fisclean;
		this.fispackage = fispackage;
		this.fpackagedescription = fpackagedescription;
		this.fislettering = fislettering;
		this.fletteringescription = fletteringescription;
		this.flinkphone = flinkphone;
		this.flinkman = flinkman;
		this.fisaccessory = fisaccessory;
		this.fstate = fstate;
		this.fclosetime = fclosetime;
		this.fcloseuserid = fcloseuserid;
		this.fcloseprevstate = fcloseprevstate;
		this.fdesignproviderid=fdesignproviderid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public BigDecimal getFboxlength() {
		return this.fboxlength;
	}

	public void setFboxlength(BigDecimal fboxlength) {
		this.fboxlength = fboxlength;
	}

	public BigDecimal getFboxwidth() {
		return this.fboxwidth;
	}

	public void setFboxwidth(BigDecimal fboxwidth) {
		this.fboxwidth = fboxwidth;
	}

	public BigDecimal getFboxheight() {
		return this.fboxheight;
	}

	public void setFboxheight(BigDecimal fboxheight) {
		this.fboxheight = fboxheight;
	}

	public BigDecimal getFboardlength() {
		return this.fboardlength;
	}

	public void setFboardlength(BigDecimal fboardlength) {
		this.fboardlength = fboardlength;
	}

	public BigDecimal getFboardwidth() {
		return this.fboardwidth;
	}

	public void setFboardwidth(BigDecimal fboardwidth) {
		this.fboardwidth = fboardwidth;
	}

	public String getFcreatid() {
		return this.fcreatid;
	}

	public void setFcreatid(String fcreatid) {
		this.fcreatid = fcreatid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFupdateuserid() {
		return this.fupdateuserid;
	}

	public void setFupdateuserid(String fupdateuserid) {
		this.fupdateuserid = fupdateuserid;
	}

	public Date getFupdatetime() {
		return this.fupdatetime;
	}

	public void setFupdatetime(Date fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

	public String getFauditorid() {
		return this.fauditorid;
	}

	public void setFauditorid(String fauditorid) {
		this.fauditorid = fauditorid;
	}

	public Date getFauditortime() {
		return this.fauditortime;
	}

	public void setFauditortime(Date fauditortime) {
		this.fauditortime = fauditortime;
	}

	public Boolean getIsfauditor() {
		return this.isfauditor;
	}

	public void setIsfauditor(Boolean isfauditor) {
		this.isfauditor = isfauditor;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public Boolean getFalloted() {
		return this.falloted;
	}

	public void setFalloted(Boolean falloted) {
		this.falloted = falloted;
	}

	public String getFallotor() {
		return this.fallotor;
	}

	public void setFallotor(String fallotor) {
		this.fallotor = fallotor;
	}

	public Date getFallottime() {
		return this.fallottime;
	}

	public void setFallottime(Date fallottime) {
		this.fallottime = fallottime;
	}

	public Boolean getFreceived() {
		return this.freceived;
	}

	public void setFreceived(Boolean freceived) {
		this.freceived = freceived;
	}

	public String getFreceiver() {
		return this.freceiver;
	}

	public void setFreceiver(String freceiver) {
		this.freceiver = freceiver;
	}

	public Date getFreceivetime() {
		return this.freceivetime;
	}

	public void setFreceivetime(Date freceivetime) {
		this.freceivetime = freceivetime;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public Integer getFtype() {
		return this.ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	public String getFcostneed() {
		return this.fcostneed;
	}

	public void setFcostneed(String fcostneed) {
		this.fcostneed = fcostneed;
	}

	public Boolean getFiszhiyang() {
		return this.fiszhiyang;
	}

	public void setFiszhiyang(Boolean fiszhiyang) {
		this.fiszhiyang = fiszhiyang;
	}

	public Integer getFamount() {
		return this.famount;
	}

	public void setFamount(Integer famount) {
		this.famount = famount;
	}

	public Date getFoverdate() {
		return this.foverdate;
	}

	public void setFoverdate(Date foverdate) {
		this.foverdate = foverdate;
	}

	public Date getFarrivetime() {
		return this.farrivetime;
	}

	public void setFarrivetime(Date farrivetime) {
		this.farrivetime = farrivetime;
	}

	public String getFboxpileid() {
		return this.fboxpileid;
	}

	public void setFboxpileid(String fboxpileid) {
		this.fboxpileid = fboxpileid;
	}

	public String getFmaterial() {
		return this.fmaterial;
	}

	public void setFmaterial(String fmaterial) {
		this.fmaterial = fmaterial;
	}

	public Integer getFcorrugated() {
		return this.fcorrugated;
	}

	public void setFcorrugated(Integer fcorrugated) {
		this.fcorrugated = fcorrugated;
	}

	public String getFprintcolor() {
		return this.fprintcolor;
	}

	public void setFprintcolor(String fprintcolor) {
		this.fprintcolor = fprintcolor;
	}

	public String getFprintbarcode() {
		return this.fprintbarcode;
	}

	public void setFprintbarcode(String fprintbarcode) {
		this.fprintbarcode = fprintbarcode;
	}

	public Integer getFunitestyle() {
		return this.funitestyle;
	}

	public void setFunitestyle(Integer funitestyle) {
		this.funitestyle = funitestyle;
	}

	public Integer getFprintstyle() {
		return this.fprintstyle;
	}

	public void setFprintstyle(Integer fprintstyle) {
		this.fprintstyle = fprintstyle;
	}

	public Integer getFsurfacetreatment() {
		return this.fsurfacetreatment;
	}

	public void setFsurfacetreatment(Integer fsurfacetreatment) {
		this.fsurfacetreatment = fsurfacetreatment;
	}

	public String getFpackstyle() {
		return this.fpackstyle;
	}

	public void setFpackstyle(String fpackstyle) {
		this.fpackstyle = fpackstyle;
	}

	public String getFpackdescription() {
		return this.fpackdescription;
	}

	public void setFpackdescription(String fpackdescription) {
		this.fpackdescription = fpackdescription;
	}

	public Boolean getFisclean() {
		return this.fisclean;
	}

	public void setFisclean(Boolean fisclean) {
		this.fisclean = fisclean;
	}

	public Boolean getFispackage() {
		return this.fispackage;
	}

	public void setFispackage(Boolean fispackage) {
		this.fispackage = fispackage;
	}

	public String getFpackagedescription() {
		return this.fpackagedescription;
	}

	public void setFpackagedescription(String fpackagedescription) {
		this.fpackagedescription = fpackagedescription;
	}

	public Boolean getFislettering() {
		return this.fislettering;
	}

	public void setFislettering(Boolean fislettering) {
		this.fislettering = fislettering;
	}

	public String getFletteringescription() {
		return this.fletteringescription;
	}

	public void setFletteringescription(String fletteringescription) {
		this.fletteringescription = fletteringescription;
	}

	public String getFlinkphone() {
		return this.flinkphone;
	}

	public void setFlinkphone(String flinkphone) {
		this.flinkphone = flinkphone;
	}

	public String getFlinkman() {
		return this.flinkman;
	}

	public void setFlinkman(String flinkman) {
		this.flinkman = flinkman;
	}

	public Boolean getFisaccessory() {
		return this.fisaccessory;
	}

	public void setFisaccessory(Boolean fisaccessory) {
		this.fisaccessory = fisaccessory;
	}

	public String getFstate() {
		return this.fstate;
	}

	public void setFstate(String fstate) {
		this.fstate = fstate;
	}

	public Date getFclosetime() {
		return this.fclosetime;
	}

	public void setFclosetime(Date fclosetime) {
		this.fclosetime = fclosetime;
	}

	public String getFcloseuserid() {
		return this.fcloseuserid;
	}

	public void setFcloseuserid(String fcloseuserid) {
		this.fcloseuserid = fcloseuserid;
	}

	public String getFcloseprevstate() {
		return this.fcloseprevstate;
	}

	public void setFcloseprevstate(String fcloseprevstate) {
		this.fcloseprevstate = fcloseprevstate;
	}

	public String getFpreproductdemandid() {
		return fpreproductdemandid;
	}

	public void setFpreproductdemandid(String fpreproductdemandid) {
		this.fpreproductdemandid = fpreproductdemandid;
	}


	
	public String getFdesignproviderid() {
		return fdesignproviderid;
	}


	public void setFdesignproviderid(String fdesignproviderid) {
		this.fdesignproviderid = fdesignproviderid;
	}


	public Integer getFisdemandpackage() {
		return fisdemandpackage;
	}

	public void setFisdemandpackage(Integer fisdemandpackage) {
		this.fisdemandpackage = fisdemandpackage;
	}
	

	

	
}
