package Com.Entity.Finance;
// default package
// Generated 2013-12-30 16:14:52 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TBalGathering generated by hbm2java
 */
public class Gathering implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private Date fbizdate;
	private String fcreatorid;
	private Date fcreatetime;
	private String fdeliverapplyid;
	private String fsaledeliverid;
	private String fsaledeliverentryid;
	private String fcustproductid;
	private BigDecimal famount;
	private BigDecimal fprice;
	private BigDecimal fsum;
	private String fdeliverorderid;
	private String fdeliversid;
	private String fproductplanid;

	public Gathering() {
	}

	public Gathering(String fid) {
		this.fid = fid;
	}

	public Gathering(String fid, String fnumber, Date fbizdate,
			String fcreatorid, Date fcreatetime, String fdeliverapplyid,
			String fsaledeliverid, String fsaledeliverentryid,
			String fcustproductid, BigDecimal famount, BigDecimal fprice,
			BigDecimal fsum, String fdeliverorderid, String fdeliversid,
			String fproductplanid) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fbizdate = fbizdate;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fdeliverapplyid = fdeliverapplyid;
		this.fsaledeliverid = fsaledeliverid;
		this.fsaledeliverentryid = fsaledeliverentryid;
		this.fcustproductid = fcustproductid;
		this.famount = famount;
		this.fprice = fprice;
		this.fsum = fsum;
		this.fdeliverorderid = fdeliverorderid;
		this.fdeliversid = fdeliversid;
		this.fproductplanid = fproductplanid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public Date getFbizdate() {
		return this.fbizdate;
	}

	public void setFbizdate(Date fbizdate) {
		this.fbizdate = fbizdate;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFdeliverapplyid() {
		return this.fdeliverapplyid;
	}

	public void setFdeliverapplyid(String fdeliverapplyid) {
		this.fdeliverapplyid = fdeliverapplyid;
	}

	public String getFsaledeliverid() {
		return this.fsaledeliverid;
	}

	public void setFsaledeliverid(String fsaledeliverid) {
		this.fsaledeliverid = fsaledeliverid;
	}

	public String getFsaledeliverentryid() {
		return this.fsaledeliverentryid;
	}

	public void setFsaledeliverentryid(String fsaledeliverentryid) {
		this.fsaledeliverentryid = fsaledeliverentryid;
	}

	public String getFcustproductid() {
		return this.fcustproductid;
	}

	public void setFcustproductid(String fcustproductid) {
		this.fcustproductid = fcustproductid;
	}

	public BigDecimal getFamount() {
		return this.famount;
	}

	public void setFamount(BigDecimal famount) {
		this.famount = famount;
	}

	public BigDecimal getFprice() {
		return this.fprice;
	}

	public void setFprice(BigDecimal fprice) {
		this.fprice = fprice;
	}

	public BigDecimal getFsum() {
		return this.fsum;
	}

	public void setFsum(BigDecimal fsum) {
		this.fsum = fsum;
	}

	public String getFdeliverorderid() {
		return this.fdeliverorderid;
	}

	public void setFdeliverorderid(String fdeliverorderid) {
		this.fdeliverorderid = fdeliverorderid;
	}

	public String getFdeliversid() {
		return this.fdeliversid;
	}

	public void setFdeliversid(String fdeliversid) {
		this.fdeliversid = fdeliversid;
	}

	public String getFproductplanid() {
		return this.fproductplanid;
	}

	public void setFproductplanid(String fproductplanid) {
		this.fproductplanid = fproductplanid;
	}

}
