package com.model.designschemes;


import java.text.SimpleDateFormat;
import java.util.Date;

/**
* TOrdDesignschemes generated by hbm2java
*/
@SuppressWarnings("serial")
public class Designschemes implements java.io.Serializable {

	private String fid;
	private String fname;
	private String fcreatorid;//方案的创建者
	private String fdescription;
	private String fsupplierid;//供应商的id
	private Integer fauthtype;//方案授权信息012对应页面下拉列表
	private String fsuppliername;//供应商的name
	private String ftype;
	private Date fcreatetime;
	private Integer fstate;//方案上架1下架0
	

	///////////////////////用于封装数据与实际数据库字段无关联/////////////开始//////////////////////
	private String  fcreator;//创建者名称
	private Integer  feffect;//创建者帐号状态
	private String fshowpic;
	private String fstringctime;
	public String getFstringctime() {
		return fstringctime;
	}
	public String setFstringctime() {
		SimpleDateFormat sf = new SimpleDateFormat("yyyy-mm-dd HH24:mi:ss");
		return sf.format(this.fcreatetime);
	}
	public String getFshowpic() {
		return fshowpic;
	}

	public void setFshowpic(String fshowpic) {
		this.fshowpic = fshowpic;
	}
	
	public Integer getFstate() {
		return fstate;
	}

	public void setFstate(Integer fstate) {
		this.fstate = fstate;
	}

	public Designschemes() {
	}

	public Designschemes(String fid) {
		this.fid = fid;
	}

	public Designschemes(String fname, String fcreatorid, String fdescription,
			String fsupplierid, Integer fauthtype, String fsuppliername,
			String ftype, Date fcreatetime, Integer fstate) {
		super();
		this.fname = fname;
		this.fcreatorid = fcreatorid;
		this.fdescription = fdescription;
		this.fsupplierid = fsupplierid;
		this.fauthtype = fauthtype;
		this.fsuppliername = fsuppliername;
		this.ftype = ftype;
		this.fcreatetime = fcreatetime;
		this.fstate = fstate;
	}

	public Designschemes(String fid, String fname, String fcreatorid,
			String fdescription, String fsupplierid, Integer fauthtype,
			String fsuppliername, String ftype, Date fcreatetime, Integer fstate) {
		super();
		this.fid = fid;
		this.fname = fname;
		this.fcreatorid = fcreatorid;
		this.fdescription = fdescription;
		this.fsupplierid = fsupplierid;
		this.fauthtype = fauthtype;
		this.fsuppliername = fsuppliername;
		this.ftype = ftype;
		this.fcreatetime = fcreatetime;
		this.fstate = fstate;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public Integer getFauthtype() {
		return this.fauthtype;
	}

	public void setFauthtype(Integer fauthtype) {
		this.fauthtype = fauthtype;
	}

	public String getFsuppliername() {
		return this.fsuppliername;
	}

	public void setFsuppliername(String fsuppliername) {
		this.fsuppliername = fsuppliername;
	}

	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFcreator() {
		return fcreator;
	}

	public void setFcreator(String fcreator) {
		this.fcreator = fcreator;
	}

	public Integer getFeffect() {
		return feffect;
	}

	public void setFeffect(Integer feffect) {
		this.feffect = feffect;
	}
	

}
