package com.model.designschemes;
// default package
// Generated 2016-4-2 10:26:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TOrdSchemefiles generated by hbm2java
 */
public class Schemefiles implements java.io.Serializable {

	private String fid;
	private String fname;
	private String fparentid;
	private String fdescription;
	private Date fcreatetime;
	private String fpath;

	public Schemefiles() {
	}

	public Schemefiles(String fid) {
		this.fid = fid;
	}

	public Schemefiles(String fid, String fname, String fparentid,
			String fdescription, Date fcreatetime, String fpath) {
		this.fid = fid;
		this.fname = fname;
		this.fparentid = fparentid;
		this.fdescription = fdescription;
		this.fcreatetime = fcreatetime;
		this.fpath = fpath;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFpath() {
		return this.fpath;
	}

	public void setFpath(String fpath) {
		this.fpath = fpath;
	}

}
