package Com.Entity.System;
// default package
// Generated 2015-3-3 15:28:34 by Hibernate Tools 3.4.0.CR1

/**
 * TSysFrienduser generated by hbm2java
 */
public class Frienduser implements java.io.Serializable {

	private String fid;
	private String fuserid;
	private String frienduserid;

	public Frienduser() {
	}

	public Frienduser(String fid) {
		this.fid = fid;
	}

	public Frienduser(String fid, String fuserid, String frienduserid) {
		this.fid = fid;
		this.fuserid = fuserid;
		this.frienduserid = frienduserid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public String getFrienduserid() {
		return this.frienduserid;
	}

	public void setFrienduserid(String frienduserid) {
		this.frienduserid = frienduserid;
	}

}
