package Com.Entity.System;
// default package
// Generated 2013-6-4 15:20:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TBdAddress generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private String fid;
	private String fname;
	private String fnumber;
	private String fpostalcode;
	private String femail;
	private String flinkman;
	private String fphone;
	private String ffax;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private String fprovinceid;
	private String fcountryid;
	private String fdetailaddress;
	private String fcityidid;
	private String fdistrictidid;
	private String fcontrolunitid;
	private String fcustomerid;
	
	public Address() {
	}

	public Address(String fid) {
		this.fid = fid;
	}

	public Address(String fid, String fname, String fnumber,
			String fpostalcode, String femail, String flinkman, String fphone,
			String ffax, String fcreatorid, Date fcreatetime,
			String flastupdateuserid, Date flastupdatetime, String fprovinceid,
			String fcountryid, String fdetailaddress, String fcityidid,
			String fdistrictidid, String fcontrolunitid,String fcustomerid) {
		this.fid = fid;
		this.fname = fname;
		this.fnumber = fnumber;
		this.fpostalcode = fpostalcode;
		this.femail = femail;
		this.flinkman = flinkman;
		this.fphone = fphone;
		this.ffax = ffax;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.fprovinceid = fprovinceid;
		this.fcountryid = fcountryid;
		this.fdetailaddress = fdetailaddress;
		this.fcityidid = fcityidid;
		this.fdistrictidid = fdistrictidid;
		this.fcontrolunitid = fcontrolunitid;
		
		this.fcustomerid = fcustomerid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFpostalcode() {
		return this.fpostalcode;
	}

	public void setFpostalcode(String fpostalcode) {
		this.fpostalcode = fpostalcode;
	}

	public String getFemail() {
		return this.femail;
	}

	public void setFemail(String femail) {
		this.femail = femail;
	}

	public String getFlinkman() {
		return this.flinkman;
	}

	public void setFlinkman(String flinkman) {
		this.flinkman = flinkman;
	}

	public String getFphone() {
		return this.fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public String getFfax() {
		return this.ffax;
	}

	public void setFfax(String ffax) {
		this.ffax = ffax;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public String getFprovinceid() {
		return this.fprovinceid;
	}

	public void setFprovinceid(String fprovinceid) {
		this.fprovinceid = fprovinceid;
	}

	public String getFcountryid() {
		return this.fcountryid;
	}

	public void setFcountryid(String fcountryid) {
		this.fcountryid = fcountryid;
	}

	public String getFdetailaddress() {
		return this.fdetailaddress;
	}

	public void setFdetailaddress(String fdetailaddress) {
		this.fdetailaddress = fdetailaddress;
	}

	public String getFcityidid() {
		return this.fcityidid;
	}

	public void setFcityidid(String fcityidid) {
		this.fcityidid = fcityidid;
	}

	public String getFdistrictidid() {
		return this.fdistrictidid;
	}

	public void setFdistrictidid(String fdistrictidid) {
		this.fdistrictidid = fdistrictidid;
	}

	public String getFcontrolunitid() {
		return this.fcontrolunitid;
	}

	public void setFcontrolunitid(String fcontrolunitid) {
		this.fcontrolunitid = fcontrolunitid;
	}

	public String getFcustomerid() {
		return fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

}
