package Com.Entity.System;
// default package
// Generated 2015-1-30 10:43:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysBodypape generated by hbm2java
 */
public class Bodypape implements java.io.Serializable {

	private String fid = "";
	private String fname;
	/**
	 * 厂商
	 */
	private String fmanufacturer;
	/**
	 * 克重
	 */
	private double fgramweight;
	/**
	 * 误差
	 */
	private Double ferror;
	/**
	 * 耐破
	 */
	private Double fpopstrength;
	/**
	 * 耐折
	 */
	private Double fhardfold;
	/**
	 * 吸水
	 */
	private Double fwaterabsorption;
	/**
	 * 原纸类型
	 */
	private String fbasepapercategory;
	/**
	 * 适用类型
	 */
	private Byte fusecategory;
	private String fremark;
	private Byte fenable = 1;
	private Date fcreatetime = new Date();
	private Date fupdatetime = new Date();

	public Bodypape() {
	}

	public Bodypape(String fid, String fname, String fmanufacturer,
			double fgramweight) {
		this.fid = fid;
		this.fname = fname;
		this.fmanufacturer = fmanufacturer;
		this.fgramweight = fgramweight;
	}

	public Bodypape(String fid, String fname, String fmanufacturer,
			double fgramweight, Double ferror, Double fpopstrength,
			Double fhardfold, Double fwaterabsorption,
			String fbasepapercategory, Byte fusecategory, String fremark,
			Byte fenable, Date fcreatetime, Date fupdatetime) {
		this.fid = fid;
		this.fname = fname;
		this.fmanufacturer = fmanufacturer;
		this.fgramweight = fgramweight;
		this.ferror = ferror;
		this.fpopstrength = fpopstrength;
		this.fhardfold = fhardfold;
		this.fwaterabsorption = fwaterabsorption;
		this.fbasepapercategory = fbasepapercategory;
		this.fusecategory = fusecategory;
		this.fremark = fremark;
		this.fenable = fenable;
		this.fcreatetime = fcreatetime;
		this.fupdatetime = fupdatetime;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFmanufacturer() {
		return this.fmanufacturer;
	}

	public void setFmanufacturer(String fmanufacturer) {
		this.fmanufacturer = fmanufacturer;
	}

	public double getFgramweight() {
		return this.fgramweight;
	}

	public void setFgramweight(double fgramweight) {
		this.fgramweight = fgramweight;
	}

	public Double getFerror() {
		return this.ferror;
	}

	public void setFerror(Double ferror) {
		this.ferror = ferror;
	}

	public Double getFpopstrength() {
		return this.fpopstrength;
	}

	public void setFpopstrength(Double fpopstrength) {
		this.fpopstrength = fpopstrength;
	}

	public Double getFhardfold() {
		return this.fhardfold;
	}

	public void setFhardfold(Double fhardfold) {
		this.fhardfold = fhardfold;
	}

	public Double getFwaterabsorption() {
		return this.fwaterabsorption;
	}

	public void setFwaterabsorption(Double fwaterabsorption) {
		this.fwaterabsorption = fwaterabsorption;
	}

	public String getFbasepapercategory() {
		return this.fbasepapercategory;
	}

	public void setFbasepapercategory(String fbasepapercategory) {
		this.fbasepapercategory = fbasepapercategory;
	}

	public Byte getFusecategory() {
		return this.fusecategory;
	}

	public void setFusecategory(Byte fusecategory) {
		this.fusecategory = fusecategory;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

	public Byte getFenable() {
		return this.fenable;
	}

	public void setFenable(Byte fenable) {
		this.fenable = fenable;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public Date getFupdatetime() {
		return this.fupdatetime;
	}

	public void setFupdatetime(Date fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

}
