package Com.Entity.System;
// default package
// Generated 2013-6-4 15:20:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TBdAddress generated by hbm2java
 */
public class Certificate implements java.io.Serializable {

	private String fid;
	private String fuserid;
	private String fusername;
	private Date fcreatetime;
	private String fauditor;
	private Date fauditedtime;
	private int faudited;
	private String fauditorid;
	private String fserial;
	private Date flastlogintime;
	private String fremark;

	public int getFaudited() {
		return faudited;
	}

	public void setFaudited(int faudited) {
		this.faudited = faudited;
	}

	public String getFremark() {
		return fremark;
		
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

	public Certificate() {
		faudited=0;
	}

	public Certificate(String fid) {
		this.fid = fid;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFuserid() {
		return fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public String getFusername() {
		return fusername;
	}

	public void setFusername(String fusername) {
		this.fusername = fusername;
	}

	public Date getFcreatetime() {
		return fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFauditor() {
		return fauditor;
	}

	public void setFauditor(String fauditor) {
		this.fauditor = fauditor;
	}

	public Date getFauditedtime() {
		return fauditedtime;
	}

	public void setFauditedtime(Date fauditedtime) {
		this.fauditedtime = fauditedtime;
	}

	public String getFauditorid() {
		return fauditorid;
	}

	public void setFauditorid(String fauditorid) {
		this.fauditorid = fauditorid;
	}

	public String getFserial() {
		return fserial;
	}

	public void setFserial(String fserial) {
		this.fserial = fserial;
	}

	public Date getFlastlogintime() {
		return flastlogintime;
	}

	public void setFlastlogintime(Date flastlogintime) {
		this.flastlogintime = flastlogintime;
	}


}
