package Com.Entity.System;
// default package
// Generated 2013-5-20 9:44:29 by Hibernate Tools 3.4.0.CR1

/**
 * TSysCustrelationproduct generated by hbm2java
 */
public class CustRelationProduct implements java.io.Serializable {

	private String fid;
	private String fcustid;
	private String fproductdefid;

	public CustRelationProduct() {
	}

	public CustRelationProduct(String fid, String fcustid,
			String fproductdefid) {
		this.fid = fid;
		this.fcustid = fcustid;
		this.fproductdefid = fproductdefid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcustid() {
		return this.fcustid;
	}

	public void setFcustid(String fcustid) {
		this.fcustid = fcustid;
	}

	public String getFproductdefid() {
		return this.fproductdefid;
	}

	public void setFproductdefid(String fproductdefid) {
		this.fproductdefid = fproductdefid;
	}

}
