package Com.Entity.System;
// default package
// Generated 2015-6-13 19:39:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TBdCustomer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private String fid;
	private String fname;
	private String fnumber ="";
	private String fdescription;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private String fcountryid;
	private String fcityid;
	private String fprovince;
	private String fregionid;
	private String findustryid;
	private String fartificialperson;
	private String fbizregisterno;
	private Integer fisinternalcompany=0;//原为“是否内部客户”，改为是否认证
	private String ftxregisterno;//原为税务登记证 现改为统一注册号 营业执照、税务登记证或是组织机构代码证三选一即可
	private String fbarcode;//原 条形码，现改为身份证号
	private String fmnemoniccode;
	private String fbusilicence;
	private String fbusiexequatur;
	private String fgspauthentication;
	private String fforeignname;
	private String faddress;
	private Integer fusedstatus;
	private String fsimplename;
	private Integer fschemedesign  = Integer.valueOf(0);
	private String fphone;
	private Long fpacktotal;
	private Long fpackbuyamount;
	private String fartificialpersonphone;
	private String flinkman;
	private Integer fisinvited=0;//是否被邀请
	private  Date finvitetime;//邀请时间
	private String ffax;
	
	public String getFfax() {
		return ffax;
	}

	public void setFfax(String ffax) {
		this.ffax = ffax;
	}

	public Customer() {
	}

	public Customer(String fid, String fnumber) {
		this.fid = fid;
		this.fnumber = fnumber;
	}

	public Customer(String fid, String fname, String fnumber,
			String fdescription, String fcreatorid, Date fcreatetime,
			String flastupdateuserid, Date flastupdatetime, String fcountryid,
			String fcityid, String fprovince, String fregionid,
			String findustryid, String fartificialperson,
			String fbizregisterno, Integer fisinternalcompany,
			String ftxregisterno, String fbarcode, String fmnemoniccode,
			String fbusilicence, String fbusiexequatur,
			String fgspauthentication, String fforeignname, String faddress,
			Integer fusedstatus, String fsimplename, Integer fschemedesign,
			String fphone, Long fpacktotal, Long fpackbuyamount,
			String fartificialpersonphone, String flinkman,String ffax) {
		this.fid = fid;
		this.fname = fname;
		this.fnumber = fnumber;
		this.fdescription = fdescription;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.fcountryid = fcountryid;
		this.fcityid = fcityid;
		this.fprovince = fprovince;
		this.fregionid = fregionid;
		this.findustryid = findustryid;
		this.fartificialperson = fartificialperson;
		this.fbizregisterno = fbizregisterno;
		this.fisinternalcompany = fisinternalcompany;
		this.ftxregisterno = ftxregisterno;
		this.fbarcode = fbarcode;
		this.fmnemoniccode = fmnemoniccode;
		this.fbusilicence = fbusilicence;
		this.fbusiexequatur = fbusiexequatur;
		this.fgspauthentication = fgspauthentication;
		this.fforeignname = fforeignname;
		this.faddress = faddress;
		this.fusedstatus = fusedstatus;
		this.fsimplename = fsimplename;
		this.fschemedesign = fschemedesign;
		this.fphone = fphone;
		this.fpacktotal = fpacktotal;
		this.fpackbuyamount = fpackbuyamount;
		this.fartificialpersonphone = fartificialpersonphone;
		this.flinkman = flinkman;
		this.ffax = ffax;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public String getFcountryid() {
		return this.fcountryid;
	}

	public void setFcountryid(String fcountryid) {
		this.fcountryid = fcountryid;
	}

	public String getFcityid() {
		return this.fcityid;
	}

	public void setFcityid(String fcityid) {
		this.fcityid = fcityid;
	}

	public String getFprovince() {
		return this.fprovince;
	}

	public void setFprovince(String fprovince) {
		this.fprovince = fprovince;
	}

	public String getFregionid() {
		return this.fregionid;
	}

	public void setFregionid(String fregionid) {
		this.fregionid = fregionid;
	}

	public String getFindustryid() {
		return this.findustryid;
	}

	public void setFindustryid(String findustryid) {
		this.findustryid = findustryid;
	}

	public String getFartificialperson() {
		return this.fartificialperson;
	}

	public void setFartificialperson(String fartificialperson) {
		this.fartificialperson = fartificialperson;
	}

	public String getFbizregisterno() {
		return this.fbizregisterno;
	}

	public void setFbizregisterno(String fbizregisterno) {
		this.fbizregisterno = fbizregisterno;
	}

	public Integer getFisinternalcompany() {
		return this.fisinternalcompany;
	}

	public void setFisinternalcompany(Integer fisinternalcompany) {
		this.fisinternalcompany = fisinternalcompany;
	}

	public String getFtxregisterno() {
		return this.ftxregisterno;
	}

	public void setFtxregisterno(String ftxregisterno) {
		this.ftxregisterno = ftxregisterno;
	}

	public String getFbarcode() {
		return this.fbarcode;
	}

	public void setFbarcode(String fbarcode) {
		this.fbarcode = fbarcode;
	}

	public String getFmnemoniccode() {
		return this.fmnemoniccode;
	}

	public void setFmnemoniccode(String fmnemoniccode) {
		this.fmnemoniccode = fmnemoniccode;
	}

	public String getFbusilicence() {
		return this.fbusilicence;
	}

	public void setFbusilicence(String fbusilicence) {
		this.fbusilicence = fbusilicence;
	}

	public String getFbusiexequatur() {
		return this.fbusiexequatur;
	}

	public void setFbusiexequatur(String fbusiexequatur) {
		this.fbusiexequatur = fbusiexequatur;
	}

	public String getFgspauthentication() {
		return this.fgspauthentication;
	}

	public void setFgspauthentication(String fgspauthentication) {
		this.fgspauthentication = fgspauthentication;
	}

	public String getFforeignname() {
		return this.fforeignname;
	}

	public void setFforeignname(String fforeignname) {
		this.fforeignname = fforeignname;
	}

	public String getFaddress() {
		return this.faddress;
	}

	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	public Integer getFusedstatus() {
		return this.fusedstatus;
	}

	public void setFusedstatus(Integer fusedstatus) {
		this.fusedstatus = fusedstatus;
	}

	public String getFsimplename() {
		return this.fsimplename;
	}

	public void setFsimplename(String fsimplename) {
		this.fsimplename = fsimplename;
	}

	public Integer getFschemedesign() {
		return this.fschemedesign;
	}

	public void setFschemedesign(Integer fschemedesign) {
		this.fschemedesign = fschemedesign;
	}

	public String getFphone() {
		return this.fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public Long getFpacktotal() {
		return this.fpacktotal;
	}

	public void setFpacktotal(Long fpacktotal) {
		this.fpacktotal = fpacktotal;
	}

	public Long getFpackbuyamount() {
		return this.fpackbuyamount;
	}

	public void setFpackbuyamount(Long fpackbuyamount) {
		this.fpackbuyamount = fpackbuyamount;
	}

	public String getFartificialpersonphone() {
		return this.fartificialpersonphone;
	}

	public void setFartificialpersonphone(String fartificialpersonphone) {
		this.fartificialpersonphone = fartificialpersonphone;
	}

	public String getFlinkman() {
		return this.flinkman;
	}

	public void setFlinkman(String flinkman) {
		this.flinkman = flinkman;
	}

	/**
	 * @return the fisinvited
	 */
	public Integer getFisinvited() {
		return fisinvited;
	}

	/**
	 * @param fisinvited the fisinvited to set
	 */
	public void setFisinvited(Integer fisinvited) {
		this.fisinvited = fisinvited;
	}

	/**
	 * @return the finvitetime
	 */
	public Date getFinvitetime() {
		return finvitetime;
	}

	/**
	 * @param finvitetime the finvitetime to set
	 */
	public void setFinvitetime(Date finvitetime) {
		this.finvitetime = finvitetime;
	}

}
