package Com.Entity.System;
// default package
// Generated 2013-8-23 11:17:18 by Hibernate Tools 3.4.0.CR1

/**
 * TSysQueryconfig generated by hbm2java
 */
public class ListQueryEntry implements java.io.Serializable {

	private String fid;
	private String FPARENTID;
	private Integer FSEQ;
	private String FLEFT;
	private String FMYFILTERFIELD;
	private String FCOMPARETYPE;
	private String FVALUE;
	private String FMERGE;
	private String FRIGHT;
	
	public Integer getFSEQ() {
		return FSEQ;
	}

	public void setFSEQ(Integer fSEQ) {
		FSEQ = fSEQ;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFPARENTID() {
		return FPARENTID;
	}

	public void setFPARENTID(String fPARENTID) {
		FPARENTID = fPARENTID;
	}

	public String getFLEFT() {
		return FLEFT;
	}

	public void setFLEFT(String fLEFT) {
		FLEFT = fLEFT;
	}

	public String getFMYFILTERFIELD() {
		return FMYFILTERFIELD;
	}

	public void setFMYFILTERFIELD(String fMYFILTERFIELD) {
		FMYFILTERFIELD = fMYFILTERFIELD;
	}

	public String getFCOMPARETYPE() {
		return FCOMPARETYPE;
	}

	public void setFCOMPARETYPE(String fCOMPARETYPE) {
		FCOMPARETYPE = fCOMPARETYPE;
	}

	public String getFVALUE() {
		return FVALUE;
	}

	public void setFVALUE(String fVALUE) {
		FVALUE = fVALUE;
	}

	public String getFMERGE() {
		return FMERGE;
	}

	public void setFMERGE(String fMERGE) {
		FMERGE = fMERGE;
	}

	public String getFRIGHT() {
		return FRIGHT;
	}

	public void setFRIGHT(String fRIGHT) {
		FRIGHT = fRIGHT;
	}

	public ListQueryEntry() {
	}
	

}
