package Com.Entity.System;
// default package
// Generated 2013-8-23 11:17:18 by Hibernate Tools 3.4.0.CR1

/**
 * TSysQueryconfig generated by hbm2java
 */
public class ListQuery implements java.io.Serializable {

	private String fid;
	private String FNAME;
	private String FUIID;
	private String FUSERID;
	public ListQuery() {
	}
	public String getFid() {
		return fid;
	}
	public void setFid(String fid) {
		this.fid = fid;
	}
	public String getFNAME() {
		return FNAME;
	}
	public void setFNAME(String fNAME) {
		FNAME = fNAME;
	}
	public String getFUIID() {
		return FUIID;
	}
	public void setFUIID(String fUIID) {
		FUIID = fUIID;
	}
	public String getFUSERID() {
		return FUSERID;
	}
	public void setFUSERID(String fUSERID) {
		FUSERID = fUSERID;
	}

}
