package Com.Entity.System;
// default package
// Generated 2013-8-23 11:17:18 by Hibernate Tools 3.4.0.CR1

/**
 * TSysQueryconfig generated by hbm2java
 */
public class Queryconfig implements java.io.Serializable {

	private String fid;
	private String fpath;
	private Integer fseq;
	private String fcolumnname;
	private String fcolumnkey;
	private Integer ffilterable;
	private String ffilterfield;
	private String ftype;
	private Integer fhide;
	private String fsql;
	private Integer fwidth;

	public Integer getFwidth() {
		return fwidth;
	}

	public void setFwidth(Integer fwidth) {
		this.fwidth = fwidth;
	}

	public String getFsql() {
		return fsql;
	}

	public void setFsql(String fsql) {
		this.fsql = fsql;
	}

	public Queryconfig() {
	}

	public Queryconfig(String fid) {
		this.fid = fid;
	}

	public Queryconfig(String fid, String fpath, Integer fseq,
			String fcolumnname, String fcolumnkey, Integer ffilterable,
			String ffilterfield, String ftype, Integer fhide) {
		this.fid = fid;
		this.fpath = fpath;
		this.fseq = fseq;
		this.fcolumnname = fcolumnname;
		this.fcolumnkey = fcolumnkey;
		this.ffilterable = ffilterable;
		this.ffilterfield = ffilterfield;
		this.ftype = ftype;
		this.fhide = fhide;
		this.fsql = fsql;
		this.fwidth = fwidth;
		
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFpath() {
		return this.fpath;
	}

	public void setFpath(String fpath) {
		this.fpath = fpath;
	}

	public Integer getFseq() {
		return this.fseq;
	}

	public void setFseq(Integer fseq) {
		this.fseq = fseq;
	}

	public String getFcolumnname() {
		return this.fcolumnname;
	}

	public void setFcolumnname(String fcolumnname) {
		this.fcolumnname = fcolumnname;
	}

	public String getFcolumnkey() {
		return this.fcolumnkey;
	}

	public void setFcolumnkey(String fcolumnkey) {
		this.fcolumnkey = fcolumnkey;
	}

	public Integer getFfilterable() {
		return this.ffilterable;
	}

	public void setFfilterable(Integer ffilterable) {
		this.ffilterable = ffilterable;
	}

	public String getFfilterfield() {
		return this.ffilterfield;
	}

	public void setFfilterfield(String ffilterfield) {
		this.ffilterfield = ffilterfield;
	}

	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public Integer getFhide() {
		return this.fhide;
	}

	public void setFhide(Integer fhide) {
		this.fhide = fhide;
	}

}
