package Com.Entity.System;
// default package
// Generated 2013-8-28 17:01:51 by Hibernate Tools 3.4.0.CR1

/**
 * TBdRolesupplier generated by hbm2java
 */
public class RoleSupplier implements java.io.Serializable {

	private String fid;
	private String froleid;
	private String fsupplierid;

	public RoleSupplier() {
	}

	public RoleSupplier(String fid) {
		this.fid = fid;
	}

	public RoleSupplier(String fid, String froleid, String fsupplierid) {
		this.fid = fid;
		this.froleid = froleid;
		this.fsupplierid = fsupplierid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFroleid() {
		return this.froleid;
	}

	public void setFroleid(String froleid) {
		this.froleid = froleid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

}
