package Com.Entity.System;
// default package
// Generated 2013-8-28 16:55:29 by Hibernate Tools 3.4.0.CR1

/**
 * TBdRolecustomer generated by hbm2java
 */
public class RoleCustomer implements java.io.Serializable {

	private String fid;
	private String froleid;
	private String fcustomerid;

	public RoleCustomer() {
	}

	public RoleCustomer(String fid) {
		this.fid = fid;
	}

	public RoleCustomer(String fid, String froleid, String fcustomerid) {
		this.fid = fid;
		this.froleid = froleid;
		this.fcustomerid = fcustomerid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFroleid() {
		return this.froleid;
	}

	public void setFroleid(String froleid) {
		this.froleid = froleid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

}
