package Com.Entity.System;
// default package
// Generated 2013-5-3 14:19:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysSupplier generated by hbm2java
 */
public class Supplier implements java.io.Serializable {

	private String fid;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private String fname;
	private String fnumber;
	private String fdescription;
	private String fsimplename;
	private String fartificialperson;
	private String fbarcode;
	private String fbusiexequatur;
	private String fbizregisterno;
	private String fbusilicence;
	private String fgspauthentication;
	private String ftaxregisterno;
	private int fusedstatus;
	private String fmnemoniccode;
	private String fforeignname;
	private String faddress;
	private String ftel;
	private String femail;
	private String fcountry;
	private String fcity;
	private String fwarehouseid;
	private String fwarehousesiteid;
	private int fisManageStock=0;

	public Supplier() {
		fisManageStock=0;
	}

	public Supplier(String fid) {
		this.fid = fid;
	}

	public Supplier(String fid, String fcreatorid, Date fcreatetime,
			String flastupdateuserid, Date flastupdatetime, String fname,
			String fnumber, String fdescription, String fsimplename,
			String fartificialperson, String fbarcode, String fbusiexequatur,
			String fbizregisterno, String fbusilicence,
			String fgspauthentication, String ftaxregisterno,
			int fusedstatus, String fmnemoniccode, String fforeignname,
			String faddress, String ftel, String femail,String Fcountry,String Fcity,String fwarehouseid,String fwarehousesiteid, int fisManageStock) {
		this.fid = fid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.fname = fname;
		this.fnumber = fnumber;
		this.fdescription = fdescription;
		this.fsimplename = fsimplename;
		this.fartificialperson = fartificialperson;
		this.fbarcode = fbarcode;
		this.fbusiexequatur = fbusiexequatur;
		this.fbizregisterno = fbizregisterno;
		this.fbusilicence = fbusilicence;
		this.fgspauthentication = fgspauthentication;
		this.ftaxregisterno = ftaxregisterno;
		this.fusedstatus = fusedstatus;
		this.fmnemoniccode = fmnemoniccode;
		this.fforeignname = fforeignname;
		this.faddress = faddress;
		this.ftel = ftel;
		this.femail = femail;
		this.fcountry = Fcountry;
		this.fcity = Fcity;
		this.fwarehouseid=fwarehouseid;
		this.fwarehousesiteid=fwarehousesiteid;
		this.fisManageStock=fisManageStock;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFsimplename() {
		return this.fsimplename;
	}

	public void setFsimplename(String fsimplename) {
		this.fsimplename = fsimplename;
	}

	public String getFartificialperson() {
		return this.fartificialperson;
	}

	public void setFartificialperson(String fartificialperson) {
		this.fartificialperson = fartificialperson;
	}

	public String getFbarcode() {
		return this.fbarcode;
	}

	public void setFbarcode(String fbarcode) {
		this.fbarcode = fbarcode;
	}

	public String getFbusiexequatur() {
		return this.fbusiexequatur;
	}

	public void setFbusiexequatur(String fbusiexequatur) {
		this.fbusiexequatur = fbusiexequatur;
	}

	public String getFbizregisterno() {
		return this.fbizregisterno;
	}

	public void setFbizregisterno(String fbizregisterno) {
		this.fbizregisterno = fbizregisterno;
	}

	public String getFbusilicence() {
		return this.fbusilicence;
	}

	public void setFbusilicence(String fbusilicence) {
		this.fbusilicence = fbusilicence;
	}

	public String getFgspauthentication() {
		return this.fgspauthentication;
	}

	public void setFgspauthentication(String fgspauthentication) {
		this.fgspauthentication = fgspauthentication;
	}

	public String getFtaxregisterno() {
		return this.ftaxregisterno;
	}

	public void setFtaxregisterno(String ftaxregisterno) {
		this.ftaxregisterno = ftaxregisterno;
	}

	public Integer getFusedstatus() {
		return this.fusedstatus;
	}

	public void setFusedstatus(Integer fusedstatus) {
		this.fusedstatus = fusedstatus;
	}

	public String getFmnemoniccode() {
		return this.fmnemoniccode;
	}

	public void setFmnemoniccode(String fmnemoniccode) {
		this.fmnemoniccode = fmnemoniccode;
	}

	public String getFforeignname() {
		return this.fforeignname;
	}

	public void setFforeignname(String fforeignname) {
		this.fforeignname = fforeignname;
	}

	public String getFaddress() {
		return this.faddress;
	}

	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	public String getFtel() {
		return this.ftel;
	}

	public void setFtel(String ftel) {
		this.ftel = ftel;
	}

	public String getFemail() {
		return this.femail;
	}

	public void setFemail(String femail) {
		this.femail = femail;
	}

	public String getFcountry(){
		return this.fcountry;
	}
	
	public void setFcountry(String fcountry){
		this.fcountry = fcountry;
	}
	
	public String getFcity(){
		return this.fcity;
	}
	
	public void setFcity(String fcity){
		this.fcity = fcity;
	}

	public String getFwarehouseid() {
		return fwarehouseid;
	}

	public void setFwarehouseid(String fwarehouseid) {
		this.fwarehouseid = fwarehouseid;
	}

	public String getFwarehousesiteid() {
		return fwarehousesiteid;
	}

	public void setFwarehousesiteid(String fwarehousesiteid) {
		this.fwarehousesiteid = fwarehousesiteid;
	}

	/**
	 * @return the fisManageStock
	 */
	public int getFisManageStock() {
		return fisManageStock;
	}

	/**
	 * @param fisManageStock the fisManageStock to set
	 */
	public void setFisManageStock(int fisManageStock) {
		this.fisManageStock = fisManageStock;
	}
}
