package Com.Entity.System;
// default package
// Generated 2014-4-23 10:43:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysSupplierjudgementrptui generated by hbm2java
 */
public class Supplierjudgementrpt implements java.io.Serializable {

	private String fid;
	private String fsupplierid;
	private Integer fyear;
	private Integer fmonth;
	private String fsupplierJudgementid;
	private String fsupplierJudgeProjectid;
	private Double fresultValue;
	private Double fjudgeProjectScore;
	private Double fjudgementScore;
	private Double fendScore;
	private String fcreatorid;
	private Date fcreatetime;
	private String fupdateuserid;
	private Date fupdatetime;

	public Supplierjudgementrpt() {
	}

	public Supplierjudgementrpt(String fid) {
		this.fid = fid;
	}

	public Supplierjudgementrpt(String fid, String fsupplierid,
			Integer fyear, Integer fmonth, String fsupplierJudgementid,
			String fsupplierJudgeProjectid, Double fresultValue,
			Double fjudgeProjectScore, Double fjudgementScore,
			Double fendScore, String fcreatorid, Date fcreatetime,
			String fupdateuserid, Date fupdatetime) {
		this.fid = fid;
		this.fsupplierid = fsupplierid;
		this.fyear = fyear;
		this.fmonth = fmonth;
		this.fsupplierJudgementid = fsupplierJudgementid;
		this.fsupplierJudgeProjectid = fsupplierJudgeProjectid;
		this.fresultValue = fresultValue;
		this.fjudgeProjectScore = fjudgeProjectScore;
		this.fjudgementScore = fjudgementScore;
		this.fendScore = fendScore;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fupdateuserid = fupdateuserid;
		this.fupdatetime = fupdatetime;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public Integer getFyear() {
		return this.fyear;
	}

	public void setFyear(Integer fyear) {
		this.fyear = fyear;
	}

	public Integer getFmonth() {
		return this.fmonth;
	}

	public void setFmonth(Integer fmonth) {
		this.fmonth = fmonth;
	}

	public String getFsupplierJudgementid() {
		return this.fsupplierJudgementid;
	}

	public void setFsupplierJudgementid(String fsupplierJudgementid) {
		this.fsupplierJudgementid = fsupplierJudgementid;
	}

	public String getFsupplierJudgeProjectid() {
		return this.fsupplierJudgeProjectid;
	}

	public void setFsupplierJudgeProjectid(String fsupplierJudgeProjectid) {
		this.fsupplierJudgeProjectid = fsupplierJudgeProjectid;
	}

	public Double getFresultValue() {
		return this.fresultValue;
	}

	public void setFresultValue(Double fresultValue) {
		this.fresultValue = fresultValue;
	}

	public Double getFjudgeProjectScore() {
		return this.fjudgeProjectScore;
	}

	public void setFjudgeProjectScore(Double fjudgeProjectScore) {
		this.fjudgeProjectScore = fjudgeProjectScore;
	}

	public Double getFjudgementScore() {
		return this.fjudgementScore;
	}

	public void setFjudgementScore(Double fjudgementScore) {
		this.fjudgementScore = fjudgementScore;
	}

	public Double getFendScore() {
		return this.fendScore;
	}

	public void setFendScore(Double fendScore) {
		this.fendScore = fendScore;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFupdateuserid() {
		return this.fupdateuserid;
	}

	public void setFupdateuserid(String fupdateuserid) {
		this.fupdateuserid = fupdateuserid;
	}

	public Date getFupdatetime() {
		return this.fupdatetime;
	}

	public void setFupdatetime(Date fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

}
