package Com.Entity.System;

// default package
// Generated 2013-4-18 9:15:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;



/**
 * TSysUser generated by hbm2java
 */
public class SysUser implements java.io.Serializable {
	private String fid;   
	private String fname;
	private String fpassword;
	private int feffect=0;//0为启用 1为禁用
	private String fcustomername="";
	private String femail="";
	private String ftel="";	//手机
	private Date fcreatetime;
	private String fcustomerid = "";
	private String fsupplierid;
	private int fisfilter = 0;
	private int fisreadonly=0;
	private Integer ftype = 0;
	private Integer fimid;
	private String fphone;	//电话
	private String ffax;	//传真
	private int fstate = 1;
	private String fqq="";
	Customer customer;
	
	public int getFstate() {
		return fstate;
	}

	public void setFstate(int fstate) {
		this.fstate = fstate;
	}

	public SysUser() {
	}

	public SysUser(String fid, String fname, String fpassword, int feffect,
			String fcustomername, String femail, String ftel, Date fcreatetime,int fisfilter,Integer ftype,int fisreadonly,int fstate,String fqq) {
		this.fid = fid;
		this.fname = fname;
		this.fpassword = fpassword;
		this.feffect = feffect;
		this.fcustomername = fcustomername;
		this.femail = femail;
		this.ftel = ftel;
		this.fcreatetime = fcreatetime;
		this.fisfilter=fisfilter;
		this.ftype=ftype;
		this.fisreadonly=fisreadonly;
		this.fstate = fstate;
		this.fqq=fqq;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFpassword() {
		return this.fpassword;
	}

	public void setFpassword(String fpassword) {
		this.fpassword = fpassword;
	}

	public int getFeffect() {
		return this.feffect;
	}

	public void setFeffect(int feffect) {
		this.feffect = feffect;
	}
	
//	public boolean isFeffect() {
//		return this.feffect==1?true:false;
//	}

	public String getFcustomername() {
		return this.fcustomername;
	}

	public void setFcustomername(String fcustomername) {
		this.fcustomername = fcustomername;
	}

	public String getFemail() {
		return this.femail;
	}

	public void setFemail(String femail) {
		this.femail = femail;
	}

	public String getFtel() {
		return this.ftel;
	}

	public void setFtel(String ftel) {
		this.ftel = ftel;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFcustomerid() {
		return fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFsupplierid() {
		return fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public int getFisfilter() {
		return fisfilter;
	}

	public void setFisfilter(int fisfilter) {
		this.fisfilter = fisfilter;
	}

	public Integer getFtype() {
		return ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	/**
	 * @return the fisreadonly
	 */
	public int getFisreadonly() {
		return fisreadonly;
	}

	/**
	 * @param fisreadonly the fisreadonly to set
	 */
	public void setFisreadonly(int fisreadonly) {
		this.fisreadonly = fisreadonly;
	}

	public Integer getFimid() {
		return fimid;
	}

	public void setFimid(Integer fimid) {
		this.fimid = fimid;
	}

	public String getFphone() {
		return fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public String getFfax() {
		return ffax;
	}

	public void setFfax(String ffax) {
		this.ffax = ffax;
	}

	/**
	 * @return the fqq
	 */
	public String getFqq() {
		return fqq;
	}

	/**
	 * @param fqq the fqq to set
	 */
	public void setFqq(String fqq) {
		this.fqq = fqq;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	
	

	
}
