package Com.Entity.System;
// default package
// Generated 2014-4-11 9:06:53 by Hibernate Tools 3.4.0.CR1

/**
 * TSysTakenumberformula generated by hbm2java
 */
public class Takenumberformula implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private String fname;
	private String fsqlStatement;

	public Takenumberformula() {
	}

	public Takenumberformula(String fid) {
		this.fid = fid;
	}

	public Takenumberformula(String fid, String fnumber, String fname,
			String fsqlStatement) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fname = fname;
		this.fsqlStatement = fsqlStatement;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFsqlStatement() {
		return this.fsqlStatement;
	}

	public void setFsqlStatement(String fsqlStatement) {
		this.fsqlStatement = fsqlStatement;
	}

}
