package Com.Entity.System;
// default package
// Generated 2014-1-3 15:22:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysUserip generated by hbm2java
 */
public class Userip implements java.io.Serializable {

	private String fid;
	private String fuserid;
	private String fip;
	private String fcreatorid;
	private Date fcreatetime;
	private String fefector;
	private Date fefecttime;
	private Integer fefected;

	public Userip() {
	}

	public Userip(String fid) {
		this.fid = fid;
	}

	public Userip(String fid, String fuserid, String fip,
			String fcreatorid, Date fcreatetime, String fefector,
			Date fefecttime, Integer fefected) {
		this.fid = fid;
		this.fuserid = fuserid;
		this.fip = fip;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fefector = fefector;
		this.fefecttime = fefecttime;
		this.fefected = fefected;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public String getFip() {
		return this.fip;
	}

	public void setFip(String fip) {
		this.fip = fip;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFefector() {
		return this.fefector;
	}

	public void setFefector(String fefector) {
		this.fefector = fefector;
	}

	public Date getFefecttime() {
		return this.fefecttime;
	}

	public void setFefecttime(Date fefecttime) {
		this.fefecttime = fefecttime;
	}

	public Integer getFefected() {
		return this.fefected;
	}

	public void setFefected(Integer fefected) {
		this.fefected = fefected;
	}

}
