package Com.Entity.System;
// default package
// Generated 2014-12-2 10:01:20 by Hibernate Tools 3.4.0.CR1

/**
 * TBdUseraddress generated by hbm2java
 */
public class Useraddress implements java.io.Serializable {

	private String fid = "";
	private String fuserid;
	private String faddress;
	private int faddefault = 0;
	public Useraddress() {
	}

	public Useraddress(String fid) {
		this.fid = fid;
	}

	public Useraddress(String fid, String fuserid, String faddress,int faddefault) {
		this.fid = fid;
		this.fuserid = fuserid;
		this.faddress = faddress;
		this.faddefault = faddefault;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public String getFaddress() {
		return this.faddress;
	}

	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	public int getFaddefault() {
		return faddefault;
	}

	public void setFaddefault(int faddefault) {
		this.faddefault = faddefault;
	}
}
