package Com.Entity.System;

// default package
// Generated 2013-4-20 13:47:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysUseronline generated by hbm2java
 */
public class Useronline implements java.io.Serializable {

	private String fid;
	private String fuserid;
	private Date flogintime;
	private Date flastoperatetime;
	private String fusername;
	private String fsessionid;
	private String fip;
	private String fbrowser;
	private String fsystem;

	public String getFsessionid() {
		return fsessionid;
	}

	public String getFip() {
		return fip;
	}

	public void setFip(String fip) {
		this.fip = fip;
	}

	public String getFbrowser() {
		return fbrowser;
	}

	public void setFbrowser(String fbrowser) {
		this.fbrowser = fbrowser;
	}

	public String getFsystem() {
		return fsystem;
	}

	public void setFsystem(String fsystem) {
		this.fsystem = fsystem;
	}

	public void setFsessionid(String fsessionid) {
		this.fsessionid = fsessionid;
	}

	public String getFusername() {
		return fusername;
	}

	public void setFusername(String fusername) {
		this.fusername = fusername;
	}

	public Useronline() {
	}

	public Useronline(String fid, String fuserid, Date flogintime,
			Date flastoperatetime) {
		this.fid = fid;
		this.fuserid = fuserid;
		this.flogintime = flogintime;
		this.flastoperatetime = flastoperatetime;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public Date getFlogintime() {
		return this.flogintime;
	}

	public void setFlogintime(Date flogintime) {
		this.flogintime = flogintime;
	}

	public Date getFlastoperatetime() {
		return this.flastoperatetime;
	}

	public void setFlastoperatetime(Date flastoperatetime) {
		this.flastoperatetime = flastoperatetime;
	}

}
