package Com.Entity.System;
// default package
// Generated 2014-4-11 9:06:53 by Hibernate Tools 3.4.0.CR1

/**
 * TSysSupplierjudgeproject generated by hbm2java
 */
public class Supplierjudgeproject implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private String fname;
	private Double frate;
	private String fsupplierJudgementId;
	private String ftakeNumberFormulaId;

	public Supplierjudgeproject() {
	}

	public Supplierjudgeproject(String fid) {
		this.fid = fid;
	}

	public Supplierjudgeproject(String fid, String fnumber, String fname,
			Double frate, String fsupplierJudgementId,
			String ftakeNumberFormulaId) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fname = fname;
		this.frate = frate;
		this.fsupplierJudgementId = fsupplierJudgementId;
		this.ftakeNumberFormulaId = ftakeNumberFormulaId;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public Double getFrate() {
		return this.frate;
	}

	public void setFrate(Double frate) {
		this.frate = frate;
	}

	public String getFsupplierJudgementId() {
		return this.fsupplierJudgementId;
	}

	public void setFsupplierJudgementId(String fsupplierJudgementId) {
		this.fsupplierJudgementId = fsupplierJudgementId;
	}

	public String getFtakeNumberFormulaId() {
		return this.ftakeNumberFormulaId;
	}

	public void setFtakeNumberFormulaId(String ftakeNumberFormulaId) {
		this.ftakeNumberFormulaId = ftakeNumberFormulaId;
	}

}
