package com.model.system;

// default package
// Generated 2014-2-11 9:26:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysSimplemessage generated by hbm2java
 */
public class Simplemessage implements java.io.Serializable, Cloneable {

	public static final Integer FTYPE_NORMAL = 0;
	public static final Integer FTYPE_REQUST_RECEIVING = 1;
	public static final Integer FTYPE_PROJECT_EVALUATION = 2;
	public static final Integer FTYPE_PRODUCTION_REMIND = 3;
	
	private String fid;
	private String fsender;
	private Date ftime;
	private String fcontent;
	private String fremark;
	private String frecipient;
	private int fhaveReaded;
	private Integer ftype;
	private Date freceivingTime;

	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}
	
	public Simplemessage() {
	}

	public Simplemessage(String fid, int fhaveReaded) {
		this.fid = fid;
		this.fhaveReaded = fhaveReaded;
	}

	public Simplemessage(String fid, String fsender, Date ftime,
			String fcontent, String fremark, String frecipient,
			int fhaveReaded, Date freceivingTime,Integer ftype) {
		this.fid = fid;
		this.fsender = fsender;
		this.ftime = ftime;
		this.fcontent = fcontent;
		this.fremark = fremark;
		this.frecipient = frecipient;
		this.fhaveReaded = fhaveReaded;
		this.freceivingTime = freceivingTime;
		this.ftype = ftype;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFsender() {
		return this.fsender;
	}

	public void setFsender(String fsender) {
		this.fsender = fsender;
	}

	public Date getFtime() {
		return this.ftime;
	}

	public void setFtime(Date ftime) {
		this.ftime = ftime;
	}

	public String getFcontent() {
		return this.fcontent;
	}

	public void setFcontent(String fcontent) {
		this.fcontent = fcontent;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

	public String getFrecipient() {
		return this.frecipient;
	}

	public void setFrecipient(String frecipient) {
		this.frecipient = frecipient;
	}

	public int getFhaveReaded() {
		return this.fhaveReaded;
	}

	public void setFhaveReaded(int fhaveReaded) {
		this.fhaveReaded = fhaveReaded;
	}

	public Date getFreceivingTime() {
		return this.freceivingTime;
	}

	public void setFreceivingTime(Date freceivingTime) {
		this.freceivingTime = freceivingTime;
	}

	public Integer getFtype() {
		return ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

}
