package com.model.system;
// default package
// Generated 2014-7-15 13:41:39 by Hibernate Tools 3.4.0.CR1

/**
 * TSysSyscfg generated by hbm2java
 */
public class Syscfg implements java.io.Serializable {

	private String fid;
	private String fkey;
	private String fvalue;
	private String fuser;

	public Syscfg() {
	}

	public Syscfg(String fid) {
		this.fid = fid;
	}

	public Syscfg(String fid, String fkey, String fvalue, String fuser) {
		this.fid = fid;
		this.fkey = fkey;
		this.fvalue = fvalue;
		this.fuser = fuser;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFkey() {
		return this.fkey;
	}

	public void setFkey(String fkey) {
		this.fkey = fkey;
	}

	public String getFvalue() {
		return this.fvalue;
	}

	public void setFvalue(String fvalue) {
		this.fvalue = fvalue;
	}

	public String getFuser() {
		return this.fuser;
	}

	public void setFuser(String fuser) {
		this.fuser = fuser;
	}

}
