package com.model.supplierboardplanconfig;
import java.util.Date;

/**
 * TSysSupplierboardplanconfig generated by hbm2java
 */
public class Supplierboardplanconfig implements java.io.Serializable {

	private String fid;
	private String fsupplierid;
	private Date forderlasttime;


	public Supplierboardplanconfig() {
	}

	public Supplierboardplanconfig(String fid) {
		this.fid = fid;
	}

	public Supplierboardplanconfig(String fid, String fsupplierid,
			Date forderlasttime) {
		this.fid = fid;
		this.fsupplierid = fsupplierid;
		this.forderlasttime = forderlasttime;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public Date getForderlasttime() {
		return this.forderlasttime;
	}

	public void setForderlasttime(Date forderlasttime) {
		this.forderlasttime = forderlasttime;
	}


}
