package Com.Entity.System;
// default package
// Generated 2013-9-25 15:09:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TPdtVmiproductparam generated by hbm2java
 */
public class VmipdtParam implements java.io.Serializable {

	private String fid;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private String fcustomerid;
	private String fproductid;
	private Integer fmaxstock;
	private Integer forderamount;
	private Integer fminstock;
	private Integer fbalanceqty;
	private Integer fproducedqty;
	private String fdescription;
	private String fcontrolunitid;
	private Integer fefected;
	private String fsupplierId;
	private Integer ftype;

	public VmipdtParam() {
	}

	public VmipdtParam(String fid) {
		this.fid = fid;
	}

	public VmipdtParam(String fid, String fcreatorid, Date fcreatetime,
			String flastupdateuserid, Date flastupdatetime, String fcustomerid,
			String fproductid, Integer fmaxstock, Integer forderamount,
			Integer fminstock, Integer fbalanceqty, Integer fproducedqty,
			String fdescription, String fcontrolunitid, Integer fefected,
			 String fsupplierId, Integer ftype) {
		this.fid = fid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.fcustomerid = fcustomerid;
		this.fproductid = fproductid;
		this.fmaxstock = fmaxstock;
		this.forderamount = forderamount;
		this.fminstock = fminstock;
		this.fbalanceqty = fbalanceqty;
		this.fproducedqty = fproducedqty;
		this.fdescription = fdescription;
		this.fcontrolunitid = fcontrolunitid;
		this.fefected = fefected;
		this.fsupplierId = fsupplierId;
		this.setFtype(ftype);
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public Integer getFmaxstock() {
		return this.fmaxstock;
	}

	public void setFmaxstock(Integer fmaxstock) {
		this.fmaxstock = fmaxstock;
	}

	public Integer getForderamount() {
		return this.forderamount;
	}

	public void setForderamount(Integer forderamount) {
		this.forderamount = forderamount;
	}

	public Integer getFminstock() {
		return this.fminstock;
	}

	public void setFminstock(Integer fminstock) {
		this.fminstock = fminstock;
	}

	public Integer getFbalanceqty() {
		return this.fbalanceqty;
	}

	public void setFbalanceqty(Integer fbalanceqty) {
		this.fbalanceqty = fbalanceqty;
	}

	public Integer getFproducedqty() {
		return this.fproducedqty;
	}

	public void setFproducedqty(Integer fproducedqty) {
		this.fproducedqty = fproducedqty;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFcontrolunitid() {
		return this.fcontrolunitid;
	}

	public void setFcontrolunitid(String fcontrolunitid) {
		this.fcontrolunitid = fcontrolunitid;
	}

	public Integer getFefected() {
		return this.fefected;
	}

	public void setFefected(Integer fefected) {
		this.fefected = fefected;
	}

	public String getFsupplierId() {
		return fsupplierId;
	}

	public void setFsupplierId(String fsupplierId) {
		this.fsupplierId = fsupplierId;
	}

	public Integer getFtype() {
		return ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

}
