// default package
// Generated 2015-9-15 11:00:59 by Hibernate Tools 3.4.0.CR1
package Com.Entity.order;
/**
 * TFtuParameter generated by hbm2java
 */
public class FtuParameter implements java.io.Serializable {

	private String fid;
	private Integer fieldtype;
	private Integer fdecimals;
	private Integer fedit;
	private String fcomputationalformula;
	private String falias;
	private String fuserid;
	private String fname;
	private Integer fisprint;
	private String fsaledeliverentry;
	
	public String getFsaledeliverentry() {
		return fsaledeliverentry;
	}

	public void setFsaledeliverentry(String fsaledeliverentry) {
		this.fsaledeliverentry = fsaledeliverentry;
	}

	public Integer getFisprint() {
		return fisprint;
	}

	public void setFisprint(Integer fisprint) {
		this.fisprint = fisprint;
	}

	public FtuParameter() {
	}

	public FtuParameter(String fid) {
		this.fid = fid;
	}

	public FtuParameter(String fid, Integer fieldtype, Integer fdecimals,
			Integer fedit, String fcomputationalformula, String falias,
			String fuserid, String fname,Integer fisprint,String fsaledeliverentry) {
		this.fid = fid;
		this.fieldtype = fieldtype;
		this.fdecimals = fdecimals;
		this.fedit = fedit;
		this.fcomputationalformula = fcomputationalformula;
		this.falias = falias;
		this.fuserid = fuserid;
		this.fname = fname;
		this.fisprint = fisprint;
		this.fsaledeliverentry =fsaledeliverentry;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Integer getFieldtype() {
		return this.fieldtype;
	}

	public void setFieldtype(Integer fieldtype) {
		this.fieldtype = fieldtype;
	}

	public Integer getFdecimals() {
		return this.fdecimals;
	}

	public void setFdecimals(Integer fdecimals) {
		this.fdecimals = fdecimals;
	}

	public Integer getFedit() {
		return this.fedit;
	}

	public void setFedit(Integer fedit) {
		this.fedit = fedit;
	}

	public String getFcomputationalformula() {
		return this.fcomputationalformula;
	}

	public void setFcomputationalformula(String fcomputationalformula) {
		this.fcomputationalformula = fcomputationalformula;
	}

	public String getFalias() {
		return this.falias;
	}

	public void setFalias(String falias) {
		this.falias = falias;
	}

	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

}
