// default package
// Generated 2015-9-23 9:12:51 by Hibernate Tools 3.4.0.CR1
package Com.Entity.order;
import java.math.BigDecimal;

/**
 * TFtuSaledeliverentry generated by hbm2java
 */
public class FTUSaledeliverEntry implements java.io.Serializable {

	private String fid;
	private String fftuproductid;
	private String famount;
	private String fprice;
	private String fparentid;
	private Integer fsequence;
	private String fdescription;
	private Integer faffirmed;
	private String fdanjia;
	private String string1;
	private String string2;
	private String string3;
	private String string4;
	private String string5;
	private String string6;
	private String string7;
	private String string8;
	private String string9;
	private String string10;
	private String fcusproductname;
	private String fspec;
	private String funit;

	public FTUSaledeliverEntry() {
	}

	public FTUSaledeliverEntry(String fid, String fftuproductid) {
		this.fid = fid;
		this.fftuproductid = fftuproductid;
	}

	public FTUSaledeliverEntry(String fid, String fftuproductid,
			String famount, String fprice, String fparentid,
			Integer fsequence, String fdescription, Integer faffirmed,
			String fdanjia, String string1, String string2, String string3,
			String string4, String string5, String string6, String string7,
			String string8, String string9, String string10,
			String fcusproductname, String fspec, String funit) {
		this.fid = fid;
		this.fftuproductid = fftuproductid;
		this.famount = famount;
		this.fprice = fprice;
		this.fparentid = fparentid;
		this.fsequence = fsequence;
		this.fdescription = fdescription;
		this.faffirmed = faffirmed;
		this.fdanjia = fdanjia;
		this.string1 = string1;
		this.string2 = string2;
		this.string3 = string3;
		this.string4 = string4;
		this.string5 = string5;
		this.string6 = string6;
		this.string7 = string7;
		this.string8 = string8;
		this.string9 = string9;
		this.string10 = string10;
		this.fcusproductname = fcusproductname;
		this.fspec = fspec;
		this.funit = funit;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFftuproductid() {
		return this.fftuproductid;
	}

	public void setFftuproductid(String fftuproductid) {
		this.fftuproductid = fftuproductid;
	}

	public String getFamount() {
		return this.famount;
	}

	public void setFamount(String famount) {
		this.famount = famount;
	}

	public String getFprice() {
		return this.fprice;
	}

	public void setFprice(String fprice) {
		this.fprice = fprice;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public Integer getFsequence() {
		return this.fsequence;
	}

	public void setFsequence(Integer fsequence) {
		this.fsequence = fsequence;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public Integer getFaffirmed() {
		return this.faffirmed;
	}

	public void setFaffirmed(Integer faffirmed) {
		this.faffirmed = faffirmed;
	}

	public String getFdanjia() {
		return this.fdanjia;
	}

	public void setFdanjia(String fdanjia) {
		this.fdanjia = fdanjia;
	}

	public String getString1() {
		return this.string1;
	}

	public void setString1(String string1) {
		this.string1 = string1;
	}

	public String getString2() {
		return this.string2;
	}

	public void setString2(String string2) {
		this.string2 = string2;
	}

	public String getString3() {
		return this.string3;
	}

	public void setString3(String string3) {
		this.string3 = string3;
	}

	public String getString4() {
		return this.string4;
	}

	public void setString4(String string4) {
		this.string4 = string4;
	}

	public String getString5() {
		return this.string5;
	}

	public void setString5(String string5) {
		this.string5 = string5;
	}

	public String getString6() {
		return this.string6;
	}

	public void setString6(String string6) {
		this.string6 = string6;
	}

	public String getString7() {
		return this.string7;
	}

	public void setString7(String string7) {
		this.string7 = string7;
	}

	public String getString8() {
		return this.string8;
	}

	public void setString8(String string8) {
		this.string8 = string8;
	}

	public String getString9() {
		return this.string9;
	}

	public void setString9(String string9) {
		this.string9 = string9;
	}

	public String getString10() {
		return this.string10;
	}

	public void setString10(String string10) {
		this.string10 = string10;
	}

	public String getFcusproductname() {
		return this.fcusproductname;
	}

	public void setFcusproductname(String fcusproductname) {
		this.fcusproductname = fcusproductname;
	}

	public String getFspec() {
		return this.fspec;
	}

	public void setFspec(String fspec) {
		this.fspec = fspec;
	}

	public String getFunit() {
		return this.funit;
	}

	public void setFunit(String funit) {
		this.funit = funit;
	}

}
