package com.model.productreqallocationrules;
// default package
// Generated 2014-8-13 10:54:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TPdtProductreqallocationrules generated by hbm2java
 */
public class Productreqallocationrules implements java.io.Serializable {

	private String fid;
	private String fcustomerid;
	private String fsupplierid;
	private String fcreatorid;
	private Date fcreatetime;
	private Integer fisstock=1;//1位快速下单 0 普通下单
	private Integer fbacthstock=0;//为1 快速下单，购物车支持备货

	public Productreqallocationrules() {
		fisstock=1;
	}

	public Productreqallocationrules(String fid) {
		this.fid = fid;
	}

	public Productreqallocationrules(String fid, String fcustomerid,
			String fsupplierid, String fcreatorid, Date fcreatetime,Integer fisstock,Integer fbacthstock) {
		this.fid = fid;
		this.fcustomerid = fcustomerid;
		this.fsupplierid = fsupplierid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fisstock=fisstock;
		this.fbacthstock=fbacthstock;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	/**
	 * @return the fisstock
	 */
	public Integer getFisstock() {
		return fisstock;
	}

	/**
	 * @param fisstock the fisstock to set
	 */
	public void setFisstock(Integer fisstock) {
		this.fisstock = fisstock;
	}

	/**
	 * @return the fbacthstock
	 */
	public Integer getFbacthstock() {
		return fbacthstock;
	}

	/**
	 * @param fbacthstock the fbacthstock to set
	 */
	public void setFbacthstock(Integer fbacthstock) {
		this.fbacthstock = fbacthstock;
	}

}
