package Com.Entity.System;
// default package
// Generated 2015-5-12 10:02:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TBdCustaccountbalance generated by hbm2java
 */
public class Custaccountbalance implements java.io.Serializable {

	private String fid;
	private String fcustomerid;
	private Date fcreatetime;
	private Integer fisread;

	public Custaccountbalance() {
	}

	public Custaccountbalance(String fid) {
		this.fid = fid;
	}

	public Custaccountbalance(String fid, String fcustomerid,
			String fcreatorid, Date fcreatetime, Integer fisread) {
		this.fid = fid;
		this.fcustomerid = fcustomerid;
		this.fcreatetime = fcreatetime;
		this.fisread = fisread;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public Integer getFisread() {
		return this.fisread;
	}

	public void setFisread(Integer fisread) {
		this.fisread = fisread;
	}

}
