package Com.Entity.traffic;
// default package
// Generated 2013-11-21 8:40:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTraSaledeliver generated by hbm2java
 */
public class Saledeliver implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private Date fbizdate;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private String ftruckid;
	private String fassembleid;
	private String fcustomerid;
	private String faddressid;
	private String fauditorid;
	private Date fauditdate;
	private Integer faudited;
	private String feasid;
	private String fsupplier;
	private Integer ftype;
	private Integer fisexport;
	private String fexternalNum;
	private String fdriverid;
	private String fphone;

	public Saledeliver() {
		fisexport=0;
		faudited=0;
	}

	public Integer getFisexport() {
		return fisexport;
	}

	public void setFisexport(Integer fisexport) {
		this.fisexport = fisexport;
	}

	public Saledeliver(String fid) {
		this.fid = fid;
	}

	public Saledeliver(String fid, String fnumber, Date fbizdate,
			String fcreatorid, Date fcreatetime, String flastupdateuserid,
			Date flastupdatetime, String ftruckid, String fassembleid,
			String fcustomerid, String faddressid, String fauditorid,
			Date fauditdate, Integer faudited, String feasid, String fsupplier, Integer ftype,
			String fexternalNum,String fdriverid,String fphone) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fbizdate = fbizdate;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.ftruckid = ftruckid;
		this.fassembleid = fassembleid;
		this.fcustomerid = fcustomerid;
		this.faddressid = faddressid;
		this.fauditorid = fauditorid;
		this.fauditdate = fauditdate;
		this.faudited = faudited;
		this.feasid = feasid;
		this.fsupplier = fsupplier;
		this.ftype = ftype;
		this.fexternalNum=fexternalNum;
		this.fdriverid=fdriverid;
		this.fphone=fphone;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public Date getFbizdate() {
		return this.fbizdate;
	}

	public void setFbizdate(Date fbizdate) {
		this.fbizdate = fbizdate;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public String getFtruckid() {
		return this.ftruckid;
	}

	public void setFtruckid(String ftruckid) {
		this.ftruckid = ftruckid;
	}

	public String getFassembleid() {
		return this.fassembleid;
	}

	public void setFassembleid(String fassembleid) {
		this.fassembleid = fassembleid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFaddressid() {
		return this.faddressid;
	}

	public void setFaddressid(String faddressid) {
		this.faddressid = faddressid;
	}

	public String getFauditorid() {
		return this.fauditorid;
	}

	public void setFauditorid(String fauditorid) {
		this.fauditorid = fauditorid;
	}

	public Date getFauditdate() {
		return this.fauditdate;
	}

	public void setFauditdate(Date fauditdate) {
		this.fauditdate = fauditdate;
	}

	public Integer getFaudited() {
		return this.faudited;
	}

	public void setFaudited(Integer faudited) {
		this.faudited = faudited;
	}

	public String getFeasid() {
		return feasid;
	}

	public void setFeasid(String feasid) {
		this.feasid = feasid;
	}

	public String getFsupplier() {
		return fsupplier;
	}

	public void setFsupplier(String fsupplier) {
		this.fsupplier = fsupplier;
	}

	public Integer getFtype() {
		return ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	/**
	 * @return the fexternalNum
	 */
	public String getFexternalNum() {
		return fexternalNum;
	}

	/**
	 * @param fexternalNum the fexternalNum to set
	 */
	public void setFexternalNum(String fexternalNum) {
		this.fexternalNum = fexternalNum;
	}

	/**
	 * @return the fdriverid
	 */
	public String getFdriverid() {
		return fdriverid;
	}

	/**
	 * @param fdriverid the fdriverid to set
	 */
	public void setFdriverid(String fdriverid) {
		this.fdriverid = fdriverid;
	}

	/**
	 * @return the fphone
	 */
	public String getFphone() {
		return fphone;
	}

	/**
	 * @param fphone the fphone to set
	 */
	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

}
