package Com.Entity.System;
// default package
// Generated 2013-8-27 13:49:15 by Hibernate Tools 3.4.0.CR1

/**
 * TBdUsercustomer generated by hbm2java
 */
public class UserCustomer implements java.io.Serializable {

	private String fid;
	private String fuserid;
	private String fcustomerid;

	public UserCustomer() {
	}

	public UserCustomer(String fid) {
		this.fid = fid;
	}

	public UserCustomer(String fid, String fuserid, String fcustomerid) {
		this.fid = fid;
		this.fuserid = fuserid;
		this.fcustomerid = fcustomerid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

}
