package com.model.schemedesign;
// default package
// Generated 2014-9-2 16:53:24 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.model.productdemandfile.Productdemandfile;

/**
 * TOrdSchemedesign generated by hbm2java
 */
public class Schemedesign implements java.io.Serializable {

	/***
	 *<p>Description: </p>
	 *<p>Company: CPS-TEAM</p> 
	 * @author WANGC
	 * @date 2015-9-22 下午3:33:05
	*/
	private static final long serialVersionUID = 2107799580497767610L;
	private String fid;                        /*** 主键*/
	private String fcreatorid;                 /*** 创建人*/
	private Date fcreatetime;                  /*** 创建时间*/
	private String fname;                      /*** 名称*/
	private String fnumber;                    /*** 编码*/
	private String fdescription="";            /*** 描述*/
	private String ffirstproductid;            /*** 需求标识t_ord_firstproductdemand 主键FID*/
	private String fcustomerid;                /*** 客户标识（t_bd_customer 主键FID）*/
	private String fsupplierid;                /*** 制造商标识(t_sys_supplier 主键FID)*/
	private Integer fconfirmed=0;              /*** 是否确认*/
	private String fconfirmer;                 /*** 确认人*/
	private Date fconfirmtime;                 /*** 确认时间*/
	private Date foverdate;                    /*** 配送时间*/
	private Long fboxlength;                   /*** 纸箱长*/
	private Long fboxwidth;                    /*** 纸箱宽*/
	private Long fboxheight;                   /*** 纸箱高*/
	private String fmaterial="";               /*** 材料*/
	private String ftilemodel="";              /*** 楞型*/
	private Integer famount=0;                 /*** 数量*/
	private Integer fordered=0;                /*** */
	private String forderperson;               /*** */
	private Date fordertime;                   /*** */
	private String ftemplateproduct;           /*** 模板产品*/
	private String ftemplatenumber;            /*** 模板编码*/
	private String fgroupid;                   /*** 群组fid*/
	private Integer faudited=0;                /*** 是否审核*/
	private String fauditorid;                 /*** 审核人*/
	private Date faudittime;                   /*** 审核时间*/
	
	///////////////////////用于封装数据与实际数据库字段无关联/////////////开始//////////////////////
	private String  supplierName;//制造商名称
	private String  customerName;//客户名称
	private String  fcreator;//创建人
	private Integer ftype;
	private String sfid;
	private String fqq;
	private String crateTime_ymr;
	private String crateTime_sfm;
	private String confirmTime_ymr;
	private String confirmTime_sfm;
	
	
	public String getCrateTime_ymr() {
		return crateTime_ymr;
	}

	public void setCrateTime_ymr(String crateTime_ymr) {
		this.crateTime_ymr = crateTime_ymr;
	}

	public String getCrateTime_sfm() {
		return crateTime_sfm;
	}

	public void setCrateTime_sfm(String crateTime_sfm) {
		this.crateTime_sfm = crateTime_sfm;
	}

	public String getConfirmTime_ymr() {
		return confirmTime_ymr;
	}

	public void setConfirmTime_ymr(String confirmTime_ymr) {
		this.confirmTime_ymr = confirmTime_ymr;
	}

	public String getConfirmTime_sfm() {
		return confirmTime_sfm;
	}

	public void setConfirmTime_sfm(String confirmTime_sfm) {
		this.confirmTime_sfm = confirmTime_sfm;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getFcreator() {
		return fcreator;
	}

	public void setFcreator(String fcreator) {
		this.fcreator = fcreator;
	}

	public Integer getFtype() {
		return ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	public String getSfid() {
		return sfid;
	}

	public void setSfid(String sfid) {
		this.sfid = sfid;
	}

	public String getFqq() {
		return fqq;
	}

	public void setFqq(String fqq) {
		this.fqq = fqq;
	}

	///////////////////////用于封装数据与实际数据库字段无关联/////////////结束//////////////////////
	public Integer getFaudited() {
		return faudited;
	}

	public void setFaudited(Integer faudited) {
		this.faudited = faudited;
	}

	public String getFauditorid() {
		return fauditorid;
	}

	public void setFauditorid(String fauditorid) {
		this.fauditorid = fauditorid;
	}

	public Date getFaudittime() {
		return faudittime;
	}

	public void setFaudittime(Date faudittime) {
		this.faudittime = faudittime;
	}

	
	public Schemedesign() {
	}

	public Schemedesign(String fid) {
		this.fid = fid;
	}


	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFfirstproductid() {
		return this.ffirstproductid;
	}

	public void setFfirstproductid(String ffirstproductid) {
		this.ffirstproductid = ffirstproductid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public Integer getFconfirmed() {
		return this.fconfirmed;
	}

	public void setFconfirmed(Integer fconfirmed) {
		this.fconfirmed = fconfirmed;
	}

	public String getFconfirmer() {
		return this.fconfirmer;
	}

	public void setFconfirmer(String fconfirmer) {
		this.fconfirmer = fconfirmer;
	}

	public Date getFconfirmtime() {
		return this.fconfirmtime;
	}

	public void setFconfirmtime(Date fconfirmtime) {
		this.fconfirmtime = fconfirmtime;
	}

	public Date getFoverdate() {
		return this.foverdate;
	}

	public void setFoverdate(Date foverdate) {
		this.foverdate = foverdate;
	}

	public Long getFboxlength() {
		return this.fboxlength;
	}

	public void setFboxlength(Long fboxlength) {
		this.fboxlength = fboxlength;
	}

	public Long getFboxwidth() {
		return this.fboxwidth;
	}

	public void setFboxwidth(Long fboxwidth) {
		this.fboxwidth = fboxwidth;
	}

	public Long getFboxheight() {
		return this.fboxheight;
	}

	public void setFboxheight(Long fboxheight) {
		this.fboxheight = fboxheight;
	}

	public String getFmaterial() {
		return this.fmaterial;
	}

	public void setFmaterial(String fmaterial) {
		this.fmaterial = fmaterial;
	}


	public String getFtilemodel() {
		return ftilemodel;
	}

	public void setFtilemodel(String ftilemodel) {
		this.ftilemodel = ftilemodel;
	}

	public Integer getFamount() {
		return this.famount;
	}

	public void setFamount(Integer famount) {
		this.famount = famount;
	}

	public Integer getFordered() {
		return this.fordered;
	}

	public void setFordered(Integer fordered) {
		this.fordered = fordered;
	}

	public String getForderperson() {
		return this.forderperson;
	}

	public void setForderperson(String forderperson) {
		this.forderperson = forderperson;
	}

	public Date getFordertime() {
		return this.fordertime;
	}

	public void setFordertime(Date fordertime) {
		this.fordertime = fordertime;
	}
	
	

	public String getFtemplateproduct() {
		return ftemplateproduct;
	}

	public void setFtemplateproduct(String ftemplateproduct) {
		this.ftemplateproduct = ftemplateproduct;
	}

	public String getFtemplatenumber() {
		return ftemplatenumber;
	}

	public void setFtemplatenumber(String ftemplatenumber) {
		this.ftemplatenumber = ftemplatenumber;
	}

	@Override
	public String toString() {
		return "Schemedesign [fid=" + fid + ", fcreatorid=" + fcreatorid
				+ ", fcreatetime=" + fcreatetime + ", fname=" + fname
				+ ", fnumber=" + fnumber + ", fdescription=" + fdescription
				+ ", ffirstproductid=" + ffirstproductid + ", fcustomerid="
				+ fcustomerid + ", fsupplierid=" + fsupplierid
				+ ", fconfirmed=" + fconfirmed + ", fconfirmer=" + fconfirmer
				+ ", fconfirmtime=" + fconfirmtime + ", foverdate=" + foverdate
				+ ", fboxlength=" + fboxlength + ", fboxwidth=" + fboxwidth
				+ ", fboxheight=" + fboxheight + ", fmaterial=" + fmaterial
				+ ", ftilemodel=" + ftilemodel + ", famount=" + famount
				+ ", fordered=" + fordered + ", forderperson=" + forderperson
				+ ", fordertime=" + fordertime + "]";
	}

	public String getFgroupid() {
		return fgroupid;
	}

	public void setFgroupid(String fgroupid) {
		this.fgroupid = fgroupid;
	}

	
	

}
