package Com.Entity.System;
// default package
// Generated 2015-5-18 13:32:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TBdCustproduct generated by hbm2java
 */
public class Custproduct implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private String fname;
	private String fspec;
	private String forderunit;
	private String fcustomerid;
	private String fdescription;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private Integer frelationed;
	private String fmaterial;
	private String ftilemodel;
	private String fcharactername;
	private String fcharacterid;
	private Integer ftype;
	private Integer feffect = 1;
	private String fproductmatching;
	private String fproductid;
	private Integer fordercount;
	private Integer forderamount;
	private BigDecimal fprice;
	private Boolean fiscommon=false;
	private String funit;
	private double fprices = 0;		//总金额
	private Date flastordertime;//最后次通过快递下单时间
	private Integer  flastorderfamount=0;//最后次下单数量
	private Integer  fisupdate=0;//是否更新过 针对快速下单
	private String flastordertype="";
	
	public Integer getFisupdate() {
		return fisupdate;
	}

	public void setFisupdate(Integer fisupdate) {
		this.fisupdate = fisupdate;
	}

	public double getFprices() {
		return fprices;
	}

	public void setFprices(double fprices) {
		this.fprices = fprices;
	}

	public double getFamount() {
		return famount;
	}

	public void setFamount(double famount) {
		this.famount = famount;
	}

	private double famount = 0;		//数量
	
	public Custproduct() {
	}

	public Custproduct(String fid) {
		this.fid = fid;
	}

	public Custproduct(String fid, String fnumber, String fname,
			String fspec, String forderunit, String fcustomerid,
			String fdescription, String fcreatorid, Date fcreatetime,
			String flastupdateuserid, Date flastupdatetime,
			Integer frelationed, String fmaterial, String ftilemodel,
			String fcharactername, String fcharacterid, Integer ftype,
			Integer feffect, String fproductmatching, String fproductid,
			Integer fordercount, Integer forderamount, BigDecimal fprice,
			Boolean fiscommon, String funit,Date flastordertime,Integer  flastorderfamount,Integer fisupdate,String flastordertype) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fname = fname;
		this.fspec = fspec;
		this.forderunit = forderunit;
		this.fcustomerid = fcustomerid;
		this.fdescription = fdescription;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.frelationed = frelationed;
		this.fmaterial = fmaterial;
		this.ftilemodel = ftilemodel;
		this.fcharactername = fcharactername;
		this.fcharacterid = fcharacterid;
		this.ftype = ftype;
		this.feffect = feffect;
		this.fproductmatching = fproductmatching;
		this.fproductid = fproductid;
		this.fordercount = fordercount;
		this.forderamount = forderamount;
		this.fprice = fprice;
		this.fiscommon = fiscommon;
		this.funit = funit;
		this.flastordertime=flastordertime;
		this.flastorderfamount=flastorderfamount;
		this.fisupdate = fisupdate;
		this.flastordertype=flastordertype;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFspec() {
		return this.fspec;
	}

	public void setFspec(String fspec) {
		this.fspec = fspec;
	}

	public String getForderunit() {
		return this.forderunit;
	}

	public void setForderunit(String forderunit) {
		this.forderunit = forderunit;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public Integer getFrelationed() {
		return this.frelationed;
	}

	public void setFrelationed(Integer frelationed) {
		this.frelationed = frelationed;
	}

	public String getFmaterial() {
		return this.fmaterial;
	}

	public void setFmaterial(String fmaterial) {
		this.fmaterial = fmaterial;
	}

	public String getFtilemodel() {
		return this.ftilemodel;
	}

	public void setFtilemodel(String ftilemodel) {
		this.ftilemodel = ftilemodel;
	}

	public String getFcharactername() {
		return this.fcharactername;
	}

	public void setFcharactername(String fcharactername) {
		this.fcharactername = fcharactername;
	}

	public String getFcharacterid() {
		return this.fcharacterid;
	}

	public void setFcharacterid(String fcharacterid) {
		this.fcharacterid = fcharacterid;
	}

	public Integer getFtype() {
		return this.ftype;
	}

	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

	public Integer getFeffect() {
		return this.feffect;
	}

	public void setFeffect(Integer feffect) {
		this.feffect = feffect;
	}

	public String getFproductmatching() {
		return this.fproductmatching;
	}

	public void setFproductmatching(String fproductmatching) {
		this.fproductmatching = fproductmatching;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public Integer getFordercount() {
		return this.fordercount;
	}

	public void setFordercount(Integer fordercount) {
		this.fordercount = fordercount;
	}

	public Integer getForderamount() {
		return this.forderamount;
	}

	public void setForderamount(Integer forderamount) {
		this.forderamount = forderamount;
	}

	public BigDecimal getFprice() {
		return this.fprice;
	}

	public void setFprice(BigDecimal fprice) {
		this.fprice = fprice;
	}

	public Boolean getFiscommon() {
		return this.fiscommon;
	}

	public void setFiscommon(Boolean fiscommon) {
		this.fiscommon = fiscommon;
	}

	public String getFunit() {
		return this.funit;
	}

	public void setFunit(String funit) {
		this.funit = funit;
	}

	/**
	 * @return the flastordertime
	 */
	public Date getFlastordertime() {
		return flastordertime;
	}

	/**
	 * @param flastordertime the flastordertime to set
	 */
	public void setFlastordertime(Date flastordertime) {
		this.flastordertime = flastordertime;
	}

	/**
	 * @return the flastorderfamount
	 */
	public Integer getFlastorderfamount() {
		return flastorderfamount;
	}

	/**
	 * @param flastorderfamount the flastorderfamount to set
	 */
	public void setFlastorderfamount(Integer flastorderfamount) {
		this.flastorderfamount = flastorderfamount;
	}

	/**
	 * @return the flastordertype
	 */
	public String getFlastordertype() {
		return flastordertype;
	}

	/**
	 * @param flastordertype the flastordertype to set
	 */
	public void setFlastordertype(String flastordertype) {
		this.flastordertype = flastordertype;
	}

}
