package Com.Entity.System;
// default package
// Generated 2013-6-4 14:44:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TBdProductcycle generated by hbm2java
 */
public class Productcycle implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private String fname;
	private String fdescription;
	private String fcreatorid;
	private Date fcreatetime;
	private String flastupdateuserid;
	private Date flastupdatetime;
	private Integer flifecycle;
	private String fproductdefid;
	private String fsupplierid;
	
	private Double fproportion;

	public Productcycle() {
	}

	public Productcycle(String fid) {
		this.fid = fid;
	}

	


	public Double getFproportion() {
		return fproportion;
	}

	public void setFproportion(Double fproportion) {
		this.fproportion = fproportion;
	}

	public Productcycle(String fid, String fnumber, String fname,
			String fdescription, String fcreatorid, Date fcreatetime,
			String flastupdateuserid, Date flastupdatetime, Integer flifecycle,
			String fproductdefid, String fsupplierid, Double fproportion) {
//		super();
		this.fid = fid;
		this.fnumber = fnumber;
		this.fname = fname;
		this.fdescription = fdescription;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.flastupdateuserid = flastupdateuserid;
		this.flastupdatetime = flastupdatetime;
		this.flifecycle = flifecycle;
		this.fproductdefid = fproductdefid;
		this.fsupplierid = fsupplierid;
		this.fproportion = fproportion;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFlastupdateuserid() {
		return this.flastupdateuserid;
	}

	public void setFlastupdateuserid(String flastupdateuserid) {
		this.flastupdateuserid = flastupdateuserid;
	}

	public Date getFlastupdatetime() {
		return this.flastupdatetime;
	}

	public void setFlastupdatetime(Date flastupdatetime) {
		this.flastupdatetime = flastupdatetime;
	}

	public Integer getFlifecycle() {
		return this.flifecycle;
	}

	public void setFlifecycle(Integer flifecycle) {
		this.flifecycle = flifecycle;
	}

	public String getFproductdefid() {
		return this.fproductdefid;
	}

	public void setFproductdefid(String fproductdefid) {
		this.fproductdefid = fproductdefid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

}
