package Com.Entity.order;
// default package
// Generated 2013-8-9 10:39:37 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TPplConventionalplan generated by hbm2java
 */
public class Conventionalplan implements java.io.Serializable {

	private String fid;
	private String fcreatorid;
	private Date fcreatetime;
	private String fupdateuserid;
	private Date fupdatetime;
	private String fcustProductid;
	private String fcustProductName;
	private BigDecimal fplanQty;
	private BigDecimal fplanCycle;
	private Date fplanDelivery;
	private BigDecimal fplanAmount;
	private String fcustomerid;
	private String fcustomerName;
	private Date fplanbegintime;
	private Date fplanendtime;
	private String fdescription;

	public Conventionalplan() {
	}

	public Conventionalplan(String fid) {
		this.fid = fid;
	}

	public Conventionalplan(String fid, String fcreatorid,
			Date fcreatetime, String fupdateuserid, Date fupdatetime,
			String fcustProductid, String fcustProductName,
			BigDecimal fplanQty, BigDecimal fplanCycle, Date fplanDelivery,
			BigDecimal fplanAmount, String fcustomerid, String fcustomerName,
			Date fplanbegintime, Date fplanendtime, String fdescription) {
		this.fid = fid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fupdateuserid = fupdateuserid;
		this.fupdatetime = fupdatetime;
		this.fcustProductid = fcustProductid;
		this.fcustProductName = fcustProductName;
		this.fplanQty = fplanQty;
		this.fplanCycle = fplanCycle;
		this.fplanDelivery = fplanDelivery;
		this.fplanAmount = fplanAmount;
		this.fcustomerid = fcustomerid;
		this.fcustomerName = fcustomerName;
		this.fplanbegintime = fplanbegintime;
		this.fplanendtime = fplanendtime;
		this.fdescription = fdescription;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFupdateuserid() {
		return this.fupdateuserid;
	}

	public void setFupdateuserid(String fupdateuserid) {
		this.fupdateuserid = fupdateuserid;
	}

	public Date getFupdatetime() {
		return this.fupdatetime;
	}

	public void setFupdatetime(Date fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

	public String getFcustProductid() {
		return this.fcustProductid;
	}

	public void setFcustProductid(String fcustProductid) {
		this.fcustProductid = fcustProductid;
	}

	public String getFcustProductName() {
		return this.fcustProductName;
	}

	public void setFcustProductName(String fcustProductName) {
		this.fcustProductName = fcustProductName;
	}

	public BigDecimal getFplanQty() {
		return this.fplanQty;
	}

	public void setFplanQty(BigDecimal fplanQty) {
		this.fplanQty = fplanQty;
	}

	public BigDecimal getFplanCycle() {
		return this.fplanCycle;
	}

	public void setFplanCycle(BigDecimal fplanCycle) {
		this.fplanCycle = fplanCycle;
	}

	public Date getFplanDelivery() {
		return this.fplanDelivery;
	}

	public void setFplanDelivery(Date fplanDelivery) {
		this.fplanDelivery = fplanDelivery;
	}

	public BigDecimal getFplanAmount() {
		return this.fplanAmount;
	}

	public void setFplanAmount(BigDecimal fplanAmount) {
		this.fplanAmount = fplanAmount;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFcustomerName() {
		return this.fcustomerName;
	}

	public void setFcustomerName(String fcustomerName) {
		this.fcustomerName = fcustomerName;
	}

	public Date getFplanbegintime() {
		return this.fplanbegintime;
	}

	public void setFplanbegintime(Date fplanbegintime) {
		this.fplanbegintime = fplanbegintime;
	}

	public Date getFplanendtime() {
		return this.fplanendtime;
	}

	public void setFplanendtime(Date fplanendtime) {
		this.fplanendtime = fplanendtime;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

}
