package Com.Entity.order;
// default package
// Generated 2014-3-18 15:01:54 by Hibernate Tools 3.4.0.CR1

/**
 * TOrdDeliverorderexception generated by hbm2java
 */
public class Deliverorderexception implements java.io.Serializable {

	private String fid;
	private String fdeliverorderId;
	private String fremark;

	public Deliverorderexception() {
	}

	public Deliverorderexception(String fid) {
		this.fid = fid;
	}

	public Deliverorderexception(String fid, String fdeliverorderId,
			String fremark) {
		this.fid = fid;
		this.fdeliverorderId = fdeliverorderId;
		this.fremark = fremark;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFdeliverorderId() {
		return this.fdeliverorderId;
	}

	public void setFdeliverorderId(String fdeliverorderId) {
		this.fdeliverorderId = fdeliverorderId;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

}
