package Com.Entity.order;
// default package
// Generated 2015-1-26 8:35:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TOrdDeliverorder generated by hbm2java
 */
public class Deliverorder implements java.io.Serializable,Cloneable {

	private String fid;
	private String fcreatorid;
	private Date fcreatetime;
	private String fupdateuserid;
	private Date fupdatetime;
	private String fnumber;
	private String fcustomerid;
	private String fcusproductid;
	private Date farrivetime;
	private String flinkman;
	private String flinkphone;
	private Integer famount;
	private String faddress;
	private String fdescription;
	private int fordered;
	private String fordermanid;
	private Date fordertime;
	private String fsaleorderid;
	private String fordernumber;
	private String forderentryid;
	private Integer fimportEas;
	private String fimportEasuserid;
	private Date fimportEastime;
	private Integer fouted;
	private String foutorid;
	private Date fouttime;
	private String faddressid;
	private String feasdeliverid;
	private Integer fistoPlan;
	private Date fplanTime;
	private String fplanNumber;
	private String fplanid;
	private Integer falloted;
	private String fdeliversId;
	private String fsupplierId;
	private BigDecimal fbalanceprice;
	private BigDecimal fpurchaseprice;
	private BigDecimal fbalanceunitprice;
	private BigDecimal fpurchaseunitprice;
	private String fproductid;
	private String fcusfid;
	private Integer fmatched;
	private Integer faudited;
	private String fauditorid;
	private Date faudittime;
	private String fstorebalanceid;
	private String ftype;
	private Integer fassembleQty;
	private Integer foutQty;
	private Integer fissync;
	private String ftraitid;
	private String fpcmordernumber;
	private Integer fdelivertype;
	private Integer fstate= 0;//1部分发货2全部发货
	private Integer fclosed=0;
	private Byte fboxtype = 0;
	
	
	
	  public Byte getFboxtype() {
		return fboxtype;
	}

	public void setFboxtype(Byte fboxtype) {
		this.fboxtype = fboxtype;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
	        //直接调用父类的clone()方法,返回克隆副本
	        return super.clone();
	    }

		public Deliverorder() {
			falloted=0;
			fclosed=0;
			fimportEas=0;
			fordered=0;
			faudited=0;
			fbalanceprice=new BigDecimal("0.00");
			fpurchaseprice=new BigDecimal("0.00");
			fbalanceunitprice=new BigDecimal("0.00");
			fpurchaseunitprice=new BigDecimal("0.00");
			fmatched=0;
			ftype="0";
			fassembleQty=0;
			foutQty=0;
			fissync=0;
		}
		
	public Deliverorder(String fid, int fordered, String fproductid) {
		this.fid = fid;
		this.fordered = fordered;
		this.fproductid = fproductid;
	}

	public Deliverorder(String fid, String fcreatorid, Date fcreatetime,
			String fupdateuserid, Date fupdatetime, String fnumber,
			String fcustomerid, String fcusproductid, Date farrivetime,
			String flinkman, String flinkphone, Integer famount,
			String faddress, String fdescription, int fordered,
			String fordermanid, Date fordertime, String fsaleorderid,
			String fordernumber, String forderentryid, Integer fimportEas,
			String fimportEasuserid, Date fimportEastime, Integer fouted,
			String foutorid, Date fouttime, String faddressid,
			String feasdeliverid, Integer fistoPlan, Date fplanTime,
			String fplanNumber, String fplanid, Integer falloted,
			String fdeliversId, String fsupplierId, BigDecimal fbalanceprice,
			BigDecimal fpurchaseprice, BigDecimal fbalanceunitprice,
			BigDecimal fpurchaseunitprice, String fproductid, String fcusfid,
			Integer fmatched, Integer faudited, String fauditorid,
			Date faudittime, String fstorebalanceid, String ftype,
			Integer fassembleQty, Integer foutQty, Integer fissync,
			String ftraitid, String fpcmordernumber,Byte fboxtype, Integer fdelivertype) {
		this.fboxtype = fboxtype;
		this.fid = fid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fupdateuserid = fupdateuserid;
		this.fupdatetime = fupdatetime;
		this.fnumber = fnumber;
		this.fcustomerid = fcustomerid;
		this.fcusproductid = fcusproductid;
		this.farrivetime = farrivetime;
		this.flinkman = flinkman;
		this.flinkphone = flinkphone;
		this.famount = famount;
		this.faddress = faddress;
		this.fdescription = fdescription;
		this.fordered = fordered;
		this.fordermanid = fordermanid;
		this.fordertime = fordertime;
		this.fsaleorderid = fsaleorderid;
		this.fordernumber = fordernumber;
		this.forderentryid = forderentryid;
		this.fimportEas = fimportEas;
		this.fimportEasuserid = fimportEasuserid;
		this.fimportEastime = fimportEastime;
		this.fouted = fouted;
		this.foutorid = foutorid;
		this.fouttime = fouttime;
		this.faddressid = faddressid;
		this.feasdeliverid = feasdeliverid;
		this.fistoPlan = fistoPlan;
		this.fplanTime = fplanTime;
		this.fplanNumber = fplanNumber;
		this.fplanid = fplanid;
		this.falloted = falloted;
		this.fdeliversId = fdeliversId;
		this.fsupplierId = fsupplierId;
		this.fbalanceprice = fbalanceprice;
		this.fpurchaseprice = fpurchaseprice;
		this.fbalanceunitprice = fbalanceunitprice;
		this.fpurchaseunitprice = fpurchaseunitprice;
		this.fproductid = fproductid;
		this.fcusfid = fcusfid;
		this.fmatched = fmatched;
		this.faudited = faudited;
		this.fauditorid = fauditorid;
		this.faudittime = faudittime;
		this.fstorebalanceid = fstorebalanceid;
		this.ftype = ftype;
		this.fassembleQty = fassembleQty;
		this.foutQty = foutQty;
		this.fissync = fissync;
		this.ftraitid = ftraitid;
		this.fpcmordernumber = fpcmordernumber;
		this.fdelivertype = fdelivertype;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFupdateuserid() {
		return this.fupdateuserid;
	}

	public void setFupdateuserid(String fupdateuserid) {
		this.fupdateuserid = fupdateuserid;
	}

	public Date getFupdatetime() {
		return this.fupdatetime;
	}

	public void setFupdatetime(Date fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFcusproductid() {
		return this.fcusproductid;
	}

	public void setFcusproductid(String fcusproductid) {
		this.fcusproductid = fcusproductid;
	}

	public Date getFarrivetime() {
		return this.farrivetime;
	}

	public void setFarrivetime(Date farrivetime) {
		this.farrivetime = farrivetime;
	}

	public String getFlinkman() {
		return this.flinkman;
	}

	public void setFlinkman(String flinkman) {
		this.flinkman = flinkman;
	}

	public String getFlinkphone() {
		return this.flinkphone;
	}

	public void setFlinkphone(String flinkphone) {
		this.flinkphone = flinkphone;
	}

	public Integer getFamount() {
		return this.famount;
	}

	public void setFamount(Integer famount) {
		this.famount = famount;
	}

	public String getFaddress() {
		return this.faddress;
	}

	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public int getFordered() {
		return this.fordered;
	}

	public void setFordered(int fordered) {
		this.fordered = fordered;
	}

	public String getFordermanid() {
		return this.fordermanid;
	}

	public void setFordermanid(String fordermanid) {
		this.fordermanid = fordermanid;
	}

	public Date getFordertime() {
		return this.fordertime;
	}

	public void setFordertime(Date fordertime) {
		this.fordertime = fordertime;
	}

	public String getFsaleorderid() {
		return this.fsaleorderid;
	}

	public void setFsaleorderid(String fsaleorderid) {
		this.fsaleorderid = fsaleorderid;
	}

	public String getFordernumber() {
		return this.fordernumber;
	}

	public void setFordernumber(String fordernumber) {
		this.fordernumber = fordernumber;
	}

	public String getForderentryid() {
		return this.forderentryid;
	}

	public void setForderentryid(String forderentryid) {
		this.forderentryid = forderentryid;
	}

	public Integer getFimportEas() {
		return this.fimportEas;
	}

	public void setFimportEas(Integer fimportEas) {
		this.fimportEas = fimportEas;
	}

	public String getFimportEasuserid() {
		return this.fimportEasuserid;
	}

	public void setFimportEasuserid(String fimportEasuserid) {
		this.fimportEasuserid = fimportEasuserid;
	}

	public Date getFimportEastime() {
		return this.fimportEastime;
	}

	public void setFimportEastime(Date fimportEastime) {
		this.fimportEastime = fimportEastime;
	}

	public Integer getFouted() {
		return this.fouted;
	}

	public void setFouted(Integer fouted) {
		this.fouted = fouted;
	}

	public String getFoutorid() {
		return this.foutorid;
	}

	public void setFoutorid(String foutorid) {
		this.foutorid = foutorid;
	}

	public Date getFouttime() {
		return this.fouttime;
	}

	public void setFouttime(Date fouttime) {
		this.fouttime = fouttime;
	}

	public String getFaddressid() {
		return this.faddressid;
	}

	public void setFaddressid(String faddressid) {
		this.faddressid = faddressid;
	}

	public String getFeasdeliverid() {
		return this.feasdeliverid;
	}

	public void setFeasdeliverid(String feasdeliverid) {
		this.feasdeliverid = feasdeliverid;
	}

	public Integer getFistoPlan() {
		return this.fistoPlan;
	}

	public void setFistoPlan(Integer fistoPlan) {
		this.fistoPlan = fistoPlan;
	}

	public Date getFplanTime() {
		return this.fplanTime;
	}

	public void setFplanTime(Date fplanTime) {
		this.fplanTime = fplanTime;
	}

	public String getFplanNumber() {
		return this.fplanNumber;
	}

	public void setFplanNumber(String fplanNumber) {
		this.fplanNumber = fplanNumber;
	}

	public String getFplanid() {
		return this.fplanid;
	}

	public void setFplanid(String fplanid) {
		this.fplanid = fplanid;
	}

	public Integer getFalloted() {
		return this.falloted;
	}

	public void setFalloted(Integer falloted) {
		this.falloted = falloted;
	}

	public String getFdeliversId() {
		return this.fdeliversId;
	}

	public void setFdeliversId(String fdeliversId) {
		this.fdeliversId = fdeliversId;
	}

	public String getFsupplierId() {
		return this.fsupplierId;
	}

	public void setFsupplierId(String fsupplierId) {
		this.fsupplierId = fsupplierId;
	}

	public BigDecimal getFbalanceprice() {
		return this.fbalanceprice;
	}

	public void setFbalanceprice(BigDecimal fbalanceprice) {
		this.fbalanceprice = fbalanceprice;
	}

	public BigDecimal getFpurchaseprice() {
		return this.fpurchaseprice;
	}

	public void setFpurchaseprice(BigDecimal fpurchaseprice) {
		this.fpurchaseprice = fpurchaseprice;
	}

	public BigDecimal getFbalanceunitprice() {
		return this.fbalanceunitprice;
	}

	public void setFbalanceunitprice(BigDecimal fbalanceunitprice) {
		this.fbalanceunitprice = fbalanceunitprice;
	}

	public BigDecimal getFpurchaseunitprice() {
		return this.fpurchaseunitprice;
	}

	public void setFpurchaseunitprice(BigDecimal fpurchaseunitprice) {
		this.fpurchaseunitprice = fpurchaseunitprice;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public String getFcusfid() {
		return this.fcusfid;
	}

	public void setFcusfid(String fcusfid) {
		this.fcusfid = fcusfid;
	}

	public Integer getFmatched() {
		return this.fmatched;
	}

	public void setFmatched(Integer fmatched) {
		this.fmatched = fmatched;
	}

	public Integer getFaudited() {
		return this.faudited;
	}

	public void setFaudited(Integer faudited) {
		this.faudited = faudited;
	}

	public String getFauditorid() {
		return this.fauditorid;
	}

	public void setFauditorid(String fauditorid) {
		this.fauditorid = fauditorid;
	}

	public Date getFaudittime() {
		return this.faudittime;
	}

	public void setFaudittime(Date faudittime) {
		this.faudittime = faudittime;
	}

	public String getFstorebalanceid() {
		return this.fstorebalanceid;
	}

	public void setFstorebalanceid(String fstorebalanceid) {
		this.fstorebalanceid = fstorebalanceid;
	}

	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	public Integer getFassembleQty() {
		return this.fassembleQty;
	}

	public void setFassembleQty(Integer fassembleQty) {
		this.fassembleQty = fassembleQty;
	}

	public Integer getFoutQty() {
		return this.foutQty;
	}

	public void setFoutQty(Integer foutQty) {
		this.foutQty = foutQty;
	}

	public Integer getFissync() {
		return this.fissync;
	}

	public void setFissync(Integer fissync) {
		this.fissync = fissync;
	}

	public String getFtraitid() {
		return this.ftraitid;
	}

	public void setFtraitid(String ftraitid) {
		this.ftraitid = ftraitid;
	}

	public String getFpcmordernumber() {
		return this.fpcmordernumber;
	}

	public void setFpcmordernumber(String fpcmordernumber) {
		this.fpcmordernumber = fpcmordernumber;
	}

	public Integer getFdelivertype() {
		return this.fdelivertype;
	}

	public void setFdelivertype(Integer fdelivertype) {
		this.fdelivertype = fdelivertype;
	}

	public Integer getFstate() {
		return fstate;
	}

	public void setFstate(Integer fstate) {
		this.fstate = fstate;
	}

	/**
	 * @return the fclosed
	 */
	public Integer getFclosed() {
		return fclosed;
	}

	/**
	 * @param fclosed the fclosed to set
	 */
	public void setFclosed(Integer fclosed) {
		this.fclosed = fclosed;
	}

	
}
