package Com.Entity.order;
// Generated 2014-12-10 9:09:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Mystock generated by hbm2java
 */
public class Mystock implements java.io.Serializable {

	private String fid;
	private String fnumber;
	private String fcustproductid;
	private Integer fplanamount;
	private String funit;
	private Date ffinishtime;
	private Date fconsumetime;
	private Integer fisconsumed;
	private String fdescription;
	private Date fcreatetime;
	private String fcreateid;
	private String fcustomerid;
	private String fsaleorderid;
	private Integer fordered;
	private String fordernumber;
	private Date fordertime;
	private String fordermanid;
	private String forderentryid;
	private String fcharactername;
	private String fcharacterid;
	private String fremark;
	private String fsupplierid;
	private Integer fstate;
	private String fpcmordernumber;
	private Integer faveragefamount=0;

	public Mystock() {
	}

	public Mystock(String fid) {
		this.fid = fid;
	}

	public Mystock(String fid, String fnumber, String fcustproductid,
			Integer fplanamount, String funit, Date ffinishtime,
			Date fconsumetime, Integer fisconsumed, String fdescription,
			Date fcreatetime, String fcreateid, String fcustomerid,
			String fsaleorderid, Integer fordered, String fordernumber,
			Date fordertime, String fordermanid, String forderentryid,
			String fcharactername, String fcharacterid, String fremark,
			String fsupplierid, Integer fstate, String fpcmordernumber,Integer faveragefamount) {
		this.fid = fid;
		this.fnumber = fnumber;
		this.fcustproductid = fcustproductid;
		this.fplanamount = fplanamount;
		this.funit = funit;
		this.ffinishtime = ffinishtime;
		this.fconsumetime = fconsumetime;
		this.fisconsumed = fisconsumed;
		this.fdescription = fdescription;
		this.fcreatetime = fcreatetime;
		this.fcreateid = fcreateid;
		this.fcustomerid = fcustomerid;
		this.fsaleorderid = fsaleorderid;
		this.fordered = fordered;
		this.fordernumber = fordernumber;
		this.fordertime = fordertime;
		this.fordermanid = fordermanid;
		this.forderentryid = forderentryid;
		this.fcharactername = fcharactername;
		this.fcharacterid = fcharacterid;
		this.fremark = fremark;
		this.fsupplierid = fsupplierid;
		this.fstate = fstate;
		this.fpcmordernumber = fpcmordernumber;
		this.faveragefamount=faveragefamount;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFcustproductid() {
		return this.fcustproductid;
	}

	public void setFcustproductid(String fcustproductid) {
		this.fcustproductid = fcustproductid;
	}

	public Integer getFplanamount() {
		return this.fplanamount;
	}

	public void setFplanamount(Integer fplanamount) {
		this.fplanamount = fplanamount;
	}

	public String getFunit() {
		return this.funit;
	}

	public void setFunit(String funit) {
		this.funit = funit;
	}

	public Date getFfinishtime() {
		return this.ffinishtime;
	}

	public void setFfinishtime(Date ffinishtime) {
		this.ffinishtime = ffinishtime;
	}

	public Date getFconsumetime() {
		return this.fconsumetime;
	}

	public void setFconsumetime(Date fconsumetime) {
		this.fconsumetime = fconsumetime;
	}

	public Integer getFisconsumed() {
		return this.fisconsumed;
	}

	public void setFisconsumed(Integer fisconsumed) {
		this.fisconsumed = fisconsumed;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFcreateid() {
		return this.fcreateid;
	}

	public void setFcreateid(String fcreateid) {
		this.fcreateid = fcreateid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFsaleorderid() {
		return this.fsaleorderid;
	}

	public void setFsaleorderid(String fsaleorderid) {
		this.fsaleorderid = fsaleorderid;
	}

	public Integer getFordered() {
		return this.fordered;
	}

	public void setFordered(Integer fordered) {
		this.fordered = fordered;
	}

	public String getFordernumber() {
		return this.fordernumber;
	}

	public void setFordernumber(String fordernumber) {
		this.fordernumber = fordernumber;
	}

	public Date getFordertime() {
		return this.fordertime;
	}

	public void setFordertime(Date fordertime) {
		this.fordertime = fordertime;
	}

	public String getFordermanid() {
		return this.fordermanid;
	}

	public void setFordermanid(String fordermanid) {
		this.fordermanid = fordermanid;
	}

	public String getForderentryid() {
		return this.forderentryid;
	}

	public void setForderentryid(String forderentryid) {
		this.forderentryid = forderentryid;
	}

	public String getFcharactername() {
		return this.fcharactername;
	}

	public void setFcharactername(String fcharactername) {
		this.fcharactername = fcharactername;
	}

	public String getFcharacterid() {
		return this.fcharacterid;
	}

	public void setFcharacterid(String fcharacterid) {
		this.fcharacterid = fcharacterid;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public Integer getFstate() {
		return this.fstate;
	}

	public void setFstate(Integer fstate) {
		this.fstate = fstate;
	}

	public String getFpcmordernumber() {
		return this.fpcmordernumber;
	}

	public void setFpcmordernumber(String fpcmordernumber) {
		this.fpcmordernumber = fpcmordernumber;
	}

	/**
	 * @return the faveragefamount
	 */
	public Integer getFaveragefamount() {
		return faveragefamount;
	}

	/**
	 * @param faveragefamount the faveragefamount to set
	 */
	public void setFaveragefamount(Integer faveragefamount) {
		this.faveragefamount = faveragefamount;
	}

}
