package Com.Entity.order;
// default package
// Generated 2014-9-2 16:53:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TOrdSchemedesign generated by hbm2java
 */
public class Schemedesign implements java.io.Serializable {

	private String fid;
	private String fcreatorid;
	private Date fcreatetime;
	private String fname;
	private String fnumber;
	private String fdescription="";
	private String ffirstproductid;
	private String fcustomerid;
	private String fsupplierid;
	private Integer fconfirmed=0;
	private String fconfirmer;
	private Date fconfirmtime;
	private Date foverdate;
	private Long fboxlength;
	private Long fboxwidth;
	private Long fboxheight;
	private String fmaterial="";
	private String ftilemodel="";
	private Integer famount=0;
	private Integer fordered=0;
	private String forderperson;
	private Date fordertime;
	private String ftemplateproduct;
	private String ftemplatenumber;
	private String fgroupid;
	private Integer faudited=0;
	private String fauditorid;
	private Date faudittime;
	
	public Integer getFaudited() {
		return faudited;
	}

	public void setFaudited(Integer faudited) {
		this.faudited = faudited;
	}

	public String getFauditorid() {
		return fauditorid;
	}

	public void setFauditorid(String fauditorid) {
		this.fauditorid = fauditorid;
	}

	public Date getFaudittime() {
		return faudittime;
	}

	public void setFaudittime(Date faudittime) {
		this.faudittime = faudittime;
	}

	
	public Schemedesign() {
	}

	public Schemedesign(String fid) {
		this.fid = fid;
	}


	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFfirstproductid() {
		return this.ffirstproductid;
	}

	public void setFfirstproductid(String ffirstproductid) {
		this.ffirstproductid = ffirstproductid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFsupplierid() {
		return this.fsupplierid;
	}

	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

	public Integer getFconfirmed() {
		return this.fconfirmed;
	}

	public void setFconfirmed(Integer fconfirmed) {
		this.fconfirmed = fconfirmed;
	}

	public String getFconfirmer() {
		return this.fconfirmer;
	}

	public void setFconfirmer(String fconfirmer) {
		this.fconfirmer = fconfirmer;
	}

	public Date getFconfirmtime() {
		return this.fconfirmtime;
	}

	public void setFconfirmtime(Date fconfirmtime) {
		this.fconfirmtime = fconfirmtime;
	}

	public Date getFoverdate() {
		return this.foverdate;
	}

	public void setFoverdate(Date foverdate) {
		this.foverdate = foverdate;
	}

	public Long getFboxlength() {
		return this.fboxlength;
	}

	public void setFboxlength(Long fboxlength) {
		this.fboxlength = fboxlength;
	}

	public Long getFboxwidth() {
		return this.fboxwidth;
	}

	public void setFboxwidth(Long fboxwidth) {
		this.fboxwidth = fboxwidth;
	}

	public Long getFboxheight() {
		return this.fboxheight;
	}

	public void setFboxheight(Long fboxheight) {
		this.fboxheight = fboxheight;
	}

	public String getFmaterial() {
		return this.fmaterial;
	}

	public void setFmaterial(String fmaterial) {
		this.fmaterial = fmaterial;
	}


	public String getFtilemodel() {
		return ftilemodel;
	}

	public void setFtilemodel(String ftilemodel) {
		this.ftilemodel = ftilemodel;
	}

	public Integer getFamount() {
		return this.famount;
	}

	public void setFamount(Integer famount) {
		this.famount = famount;
	}

	public Integer getFordered() {
		return this.fordered;
	}

	public void setFordered(Integer fordered) {
		this.fordered = fordered;
	}

	public String getForderperson() {
		return this.forderperson;
	}

	public void setForderperson(String forderperson) {
		this.forderperson = forderperson;
	}

	public Date getFordertime() {
		return this.fordertime;
	}

	public void setFordertime(Date fordertime) {
		this.fordertime = fordertime;
	}
	
	

	public String getFtemplateproduct() {
		return ftemplateproduct;
	}

	public void setFtemplateproduct(String ftemplateproduct) {
		this.ftemplateproduct = ftemplateproduct;
	}

	public String getFtemplatenumber() {
		return ftemplatenumber;
	}

	public void setFtemplatenumber(String ftemplatenumber) {
		this.ftemplatenumber = ftemplatenumber;
	}

	@Override
	public String toString() {
		return "Schemedesign [fid=" + fid + ", fcreatorid=" + fcreatorid
				+ ", fcreatetime=" + fcreatetime + ", fname=" + fname
				+ ", fnumber=" + fnumber + ", fdescription=" + fdescription
				+ ", ffirstproductid=" + ffirstproductid + ", fcustomerid="
				+ fcustomerid + ", fsupplierid=" + fsupplierid
				+ ", fconfirmed=" + fconfirmed + ", fconfirmer=" + fconfirmer
				+ ", fconfirmtime=" + fconfirmtime + ", foverdate=" + foverdate
				+ ", fboxlength=" + fboxlength + ", fboxwidth=" + fboxwidth
				+ ", fboxheight=" + fboxheight + ", fmaterial=" + fmaterial
				+ ", ftilemodel=" + ftilemodel + ", famount=" + famount
				+ ", fordered=" + fordered + ", forderperson=" + forderperson
				+ ", fordertime=" + fordertime + "]";
	}

	public String getFgroupid() {
		return fgroupid;
	}

	public void setFgroupid(String fgroupid) {
		this.fgroupid = fgroupid;
	}

	
	

}
