package Com.Entity.order;
// default package
// Generated 2014-12-12 10:13:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TOrdOrderappraise generated by hbm2java
 */
public class Orderappraise implements java.io.Serializable {

	private String fid;
	private String fcreatorid;
	private Date fcreatetime;
	private String fupdateuserid;
	private Date fupdatetime;
	private String fcustomerid;
	private String fsupplierId;
	private String fdeliverorderid;
	private Integer fdeliverappraise=0;
	private Integer fqualityappraise=0;
	private Integer fserviceappraise=0;
	private Integer fmultipleappraise=0;
	private String fdescription;
	private String fappraiseman;
	private Date fappraisetime;
	private Integer fordertype=0;
	private String fordernumber;
	private Integer ftype=0;//0 配送订单生成；1 送货凭证

	public Orderappraise() {
	}

	public Orderappraise(String fid) {
		this.fid = fid;
	}

	public Orderappraise(String fid, String fcreatorid, Date fcreatetime,
			String fupdateuserid, Date fupdatetime, String fcustomerid,
			String fsupplierId, String fdeliverorderid,
			Integer fdeliverappraise, Integer fqualityappraise,
			Integer fserviceappraise, Integer fmultipleappraise,
			String fdescription, String fappraiseman, Date fappraisetime,Integer fordertype,String fordernumber,Integer ftype) {
		this.fid = fid;
		this.fcreatorid = fcreatorid;
		this.fcreatetime = fcreatetime;
		this.fupdateuserid = fupdateuserid;
		this.fupdatetime = fupdatetime;
		this.fcustomerid = fcustomerid;
		this.fsupplierId = fsupplierId;
		this.fdeliverorderid = fdeliverorderid;
		this.fdeliverappraise = fdeliverappraise;
		this.fqualityappraise = fqualityappraise;
		this.fserviceappraise = fserviceappraise;
		this.fmultipleappraise = fmultipleappraise;
		this.fdescription = fdescription;
		this.fappraiseman = fappraiseman;
		this.fappraisetime = fappraisetime;
		this.fordertype= fordertype;
		this.fordernumber=fordernumber;
		this.ftype=ftype;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcreatorid() {
		return this.fcreatorid;
	}

	public void setFcreatorid(String fcreatorid) {
		this.fcreatorid = fcreatorid;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFupdateuserid() {
		return this.fupdateuserid;
	}

	public void setFupdateuserid(String fupdateuserid) {
		this.fupdateuserid = fupdateuserid;
	}

	public Date getFupdatetime() {
		return this.fupdatetime;
	}

	public void setFupdatetime(Date fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFsupplierId() {
		return this.fsupplierId;
	}

	public void setFsupplierId(String fsupplierId) {
		this.fsupplierId = fsupplierId;
	}

	public String getFdeliverorderid() {
		return this.fdeliverorderid;
	}

	public void setFdeliverorderid(String fdeliverorderid) {
		this.fdeliverorderid = fdeliverorderid;
	}

	public Integer getFdeliverappraise() {
		return this.fdeliverappraise;
	}

	public void setFdeliverappraise(Integer fdeliverappraise) {
		this.fdeliverappraise = fdeliverappraise;
	}

	public Integer getFqualityappraise() {
		return this.fqualityappraise;
	}

	public void setFqualityappraise(Integer fqualityappraise) {
		this.fqualityappraise = fqualityappraise;
	}

	public Integer getFserviceappraise() {
		return this.fserviceappraise;
	}

	public void setFserviceappraise(Integer fserviceappraise) {
		this.fserviceappraise = fserviceappraise;
	}

	public Integer getFmultipleappraise() {
		return this.fmultipleappraise;
	}

	public void setFmultipleappraise(Integer fmultipleappraise) {
		this.fmultipleappraise = fmultipleappraise;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFappraiseman() {
		return this.fappraiseman;
	}

	public void setFappraiseman(String fappraiseman) {
		this.fappraiseman = fappraiseman;
	}

	public Date getFappraisetime() {
		return this.fappraisetime;
	}

	public void setFappraisetime(Date fappraisetime) {
		this.fappraisetime = fappraisetime;
	}

	/**
	 * @return the fordertype
	 */
	public Integer getFordertype() {
		return fordertype;
	}

	/**
	 * @param fordertype the fordertype to set
	 */
	public void setFordertype(Integer fordertype) {
		this.fordertype = fordertype;
	}

	/**
	 * @return the fordernumber
	 */
	public String getFordernumber() {
		return fordernumber;
	}

	/**
	 * @param fordernumber the fordernumber to set
	 */
	public void setFordernumber(String fordernumber) {
		this.fordernumber = fordernumber;
	}

	/**
	 * @return the ftype
	 */
	public Integer getFtype() {
		return ftype;
	}

	/**
	 * @param ftype the ftype to set
	 */
	public void setFtype(Integer ftype) {
		this.ftype = ftype;
	}

}
