package Com.Entity.System;
// default package
// Generated 2014-11-17 9:24:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysNews generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer fid;
	private String ftitle;
	private String fcontent;
	private Date fcreatetime = new Date();
	private String fcreaterid;
	private String fimgid = "-1";

	public News() {
	}

	public News(String ftitle, String fcontent, Date fcreatetime,
			String fcreaterid, String fimgid) {
		this.ftitle = ftitle;
		this.fcontent = fcontent;
		this.fcreatetime = fcreatetime;
		this.fcreaterid = fcreaterid;
		this.fimgid = fimgid;
	}

	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	public String getFtitle() {
		return this.ftitle;
	}

	public void setFtitle(String ftitle) {
		this.ftitle = ftitle;
	}

	public String getFcontent() {
		return this.fcontent;
	}

	public void setFcontent(String fcontent) {
		this.fcontent = fcontent;
	}

	public Date getFcreatetime() {
		return this.fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFcreaterid() {
		return this.fcreaterid;
	}

	public void setFcreaterid(String fcreaterid) {
		this.fcreaterid = fcreaterid;
	}

	public String getFimgid() {
		return this.fimgid;
	}

	public void setFimgid(String fimgid) {
		this.fimgid = fimgid;
	}

}
