package Com.Entity.order;
// default package
// Generated 2014-11-4 16:21:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TOrdAppraise generated by hbm2java
 */
public class Appraise implements java.io.Serializable {

	private String fid;
	private Integer fbasicappraise;
	private String fdescription;
	private String fappraiseman;
	private Date fappraisetime;
	private String fschemedesignid;

	public Appraise() {
	}

	public Appraise(String fid) {
		this.fid = fid;
	}

	public Appraise(String fid, Integer fbasicappraise,
			String fdescription, String fappraiseman, Date fappraisetime,
			String fschemedesignid) {
		this.fid = fid;
		this.fbasicappraise = fbasicappraise;
		this.fdescription = fdescription;
		this.fappraiseman = fappraiseman;
		this.fappraisetime = fappraisetime;
		this.fschemedesignid = fschemedesignid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Integer getFbasicappraise() {
		return this.fbasicappraise;
	}

	public void setFbasicappraise(Integer fbasicappraise) {
		this.fbasicappraise = fbasicappraise;
	}

	public String getFdescription() {
		return this.fdescription;
	}

	public void setFdescription(String fdescription) {
		this.fdescription = fdescription;
	}

	public String getFappraiseman() {
		return this.fappraiseman;
	}

	public void setFappraiseman(String fappraiseman) {
		this.fappraiseman = fappraiseman;
	}

	public Date getFappraisetime() {
		return this.fappraisetime;
	}

	public void setFappraisetime(Date fappraisetime) {
		this.fappraisetime = fappraisetime;
	}

	public String getFschemedesignid() {
		return this.fschemedesignid;
	}

	public void setFschemedesignid(String fschemedesignid) {
		this.fschemedesignid = fschemedesignid;
	}

}
