package Com.Entity.order;
// default package
// Generated 2014-9-27 11:29:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TOrdProductstructure generated by hbm2java
 */
public class Productstructure implements java.io.Serializable {

	private String fid;
	private String fname;
	private String fnumber;
	private String fcustomerid;
	private String fversion;
	private BigDecimal fboxlength;
	private BigDecimal fboxwidth;
	private BigDecimal fboxheight;
	private String fmaterialcodeid;
	private String fparentid;
	private String schemedesignid;
	private Integer subProductAmount;
	private String fsupplierid;

	public Productstructure() {
	}

	public Productstructure(String fid) {
		this.fid = fid;
	}

	public Productstructure(String fid, String fname, String fnumber,
			String fcustomerid, String fversion, BigDecimal fboxlength,
			BigDecimal fboxwidth, BigDecimal fboxheight,
			String fmaterialcodeid, String fparentid, String schemedesignid,
			Integer subProductAmount,String fsupplierid) {
		this.fid = fid;
		this.fname = fname;
		this.fnumber = fnumber;
		this.fcustomerid = fcustomerid;
		this.fversion = fversion;
		this.fboxlength = fboxlength;
		this.fboxwidth = fboxwidth;
		this.fboxheight = fboxheight;
		this.fmaterialcodeid = fmaterialcodeid;
		this.fparentid = fparentid;
		this.schemedesignid = schemedesignid;
		this.subProductAmount = subProductAmount;
		this.fsupplierid=fsupplierid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFnumber() {
		return this.fnumber;
	}

	public void setFnumber(String fnumber) {
		this.fnumber = fnumber;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

	public String getFversion() {
		return this.fversion;
	}

	public void setFversion(String fversion) {
		this.fversion = fversion;
	}

	public BigDecimal getFboxlength() {
		return this.fboxlength;
	}

	public void setFboxlength(BigDecimal fboxlength) {
		this.fboxlength = fboxlength;
	}

	public BigDecimal getFboxwidth() {
		return this.fboxwidth;
	}

	public void setFboxwidth(BigDecimal fboxwidth) {
		this.fboxwidth = fboxwidth;
	}

	public BigDecimal getFboxheight() {
		return this.fboxheight;
	}

	public void setFboxheight(BigDecimal fboxheight) {
		this.fboxheight = fboxheight;
	}

	public String getFmaterialcodeid() {
		return this.fmaterialcodeid;
	}

	public void setFmaterialcodeid(String fmaterialcodeid) {
		this.fmaterialcodeid = fmaterialcodeid;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public String getSchemedesignid() {
		return this.schemedesignid;
	}

	public void setSchemedesignid(String schemedesignid) {
		this.schemedesignid = schemedesignid;
	}

	public Integer getSubProductAmount() {
		return this.subProductAmount;
	}

	public void setSubProductAmount(Integer subProductAmount) {
		this.subProductAmount = subProductAmount;
	}

	/**
	 * @return the fsupplierid
	 */
	public String getFsupplierid() {
		return fsupplierid;
	}

	/**
	 * @param fsupplierid the fsupplierid to set
	 */
	public void setFsupplierid(String fsupplierid) {
		this.fsupplierid = fsupplierid;
	}

}
