package Com.Entity.System;
// default package
// Generated 2015-1-15 10:41:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TSysNote generated by hbm2java
 */
public class Note implements java.io.Serializable,Cloneable {

	private String fid = "";
	private String fuser;
	private String fuserName;
	private String fcontent;
	private String fphone;
	private Date fdate;
	private String fpreNote;
	private String fprenoteMsg;
	private Integer isUnRead = 0;

	public Note() {
	}

	public Note(String fid, String fuserName, String fphone) {
		this.fid = fid;
		this.fuserName = fuserName;
		this.fphone = fphone;
	}

	public Note(String fid, String fuser, String fuserName, String fcontent,
			String fphone, Date fdate, String fpreNote, String fprenoteMsg,
			Integer isUnRead) {
		super();
		this.fid = fid;
		this.fuser = fuser;
		this.fuserName = fuserName;
		this.fcontent = fcontent;
		this.fphone = fphone;
		this.fdate = fdate;
		this.fpreNote = fpreNote;
		this.fprenoteMsg = fprenoteMsg;
		this.isUnRead = isUnRead;
	}

	public Integer getIsUnRead() {
		return isUnRead;
	}

	public void setIsUnRead(Integer isUnRead) {
		this.isUnRead = isUnRead;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFuser() {
		return this.fuser;
	}

	public void setFuser(String fuser) {
		this.fuser = fuser;
	}

	public String getFuserName() {
		return this.fuserName;
	}

	public void setFuserName(String fuserName) {
		this.fuserName = fuserName;
	}

	public String getFcontent() {
		return this.fcontent;
	}

	public void setFcontent(String fcontent) {
		this.fcontent = fcontent;
	}

	public String getFphone() {
		return this.fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public Date getFdate() {
		return this.fdate;
	}

	public void setFdate(Date fdate) {
		this.fdate = fdate;
	}

	public String getFpreNote() {
		return this.fpreNote;
	}

	public void setFpreNote(String fpreNote) {
		this.fpreNote = fpreNote;
	}

	public String getFprenoteMsg() {
		return this.fprenoteMsg;
	}

	public void setFprenoteMsg(String fprenoteMsg) {
		this.fprenoteMsg = fprenoteMsg;
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}

}
