package Com.Entity.System;
// default package
// Generated 2014-9-28 15:55:18 by Hibernate Tools 3.4.0.CR1

/**
 * TBdCustproductproducts generated by hbm2java
 */
public class Custproductproducts implements java.io.Serializable {

	private String fid;
	private Integer fseq;
	private String fparentid;
	private String fcustproductid;
	private Integer famount;
	private String fremark;

	public Custproductproducts() {
	}

	public Custproductproducts(String fid, String fparentid,
			String fcustproductid) {
		this.fid = fid;
		this.fparentid = fparentid;
		this.fcustproductid = fcustproductid;
	}

	public Custproductproducts(String fid, Integer fseq, String fparentid,
			String fcustproductid, Integer famount, String fremark) {
		this.fid = fid;
		this.fseq = fseq;
		this.fparentid = fparentid;
		this.fcustproductid = fcustproductid;
		this.famount = famount;
		this.fremark = fremark;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Integer getFseq() {
		return this.fseq;
	}

	public void setFseq(Integer fseq) {
		this.fseq = fseq;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public String getFcustproductid() {
		return this.fcustproductid;
	}

	public void setFcustproductid(String fcustproductid) {
		this.fcustproductid = fcustproductid;
	}

	public Integer getFamount() {
		return this.famount;
	}

	public void setFamount(Integer famount) {
		this.famount = famount;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

}
