package Com.Entity.System;
/**
 * TBdUserrelationcustp generated by hbm2java
 */
public class Userrelationcustp implements java.io.Serializable {

	private String fid;
	private String fcustproductid;
	private String fuserid;

	public Userrelationcustp() {
	}

	public Userrelationcustp(String fid) {
		this.fid = fid;
	}

	public Userrelationcustp(String fid, String fcustproductid,
			String fuserid) {
		this.fid = fid;
		this.fcustproductid = fcustproductid;
		this.fuserid = fuserid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFcustproductid() {
		return this.fcustproductid;
	}

	public void setFcustproductid(String fcustproductid) {
		this.fcustproductid = fcustproductid;
	}

	public String getFuserid() {
		return this.fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

}
