package Com.Entity.System;

// default package
// Generated 2013-4-15 14:16:08 by Hibernate Tools 3.4.0.CR1

/**
 * TSysMainmenuitem generated by hbm2java
 */
public class Mainmenuitem implements java.io.Serializable {

	private String fid;
	private String fname;
	private Integer fisleaf;
	private String furl;
	private Integer flevel;
	private String fparentid;
	private String fpath;
	private int forder;
	private String ficonCls;

	public String getFiconCls() {
		return ficonCls;
	}

	public void setFiconCls(String ficonCls) {
		this.ficonCls = ficonCls;
	}

	public String getFpath() {
		return fpath;
	}

	public void setFpath(String fpath) {
		this.fpath = fpath;
	}

	public Mainmenuitem() {
		ficonCls="";
	}

	public Mainmenuitem(String fid, int forder) {
		this.fid = fid;
		this.forder = forder;
	}

	public Mainmenuitem(String fid, String fname, Integer fisleaf,
			String furl, Integer flevel, String fparentid, int forder) {
		this.fid = fid;
		this.fname = fname;
		this.fisleaf = fisleaf;
		this.furl = furl;
		this.flevel = flevel;
		this.fparentid = fparentid;
		this.forder = forder;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public Integer getFisleaf() {
		return this.fisleaf;
	}

	public void setFisleaf(Integer fisleaf) {
		this.fisleaf = fisleaf;
	}

	public String getFurl() {
		return this.furl;
	}

	public void setFurl(String furl) {
		this.furl = furl;
	}

	public Integer getFlevel() {
		return this.flevel;
	}

	public void setFlevel(Integer flevel) {
		this.flevel = flevel;
	}

	public String getFparentid() {
		return this.fparentid;
	}

	public void setFparentid(String fparentid) {
		this.fparentid = fparentid;
	}

	public int getForder() {
		return this.forder;
	}

	public void setForder(int forder) {
		this.forder = forder;
	}
	public boolean isleaf() {
		return this.fisleaf==1?true:false;
	}

	public void setFisleaf(Boolean isleaf) {
		this.fisleaf = isleaf?1:0;
	}

}
