package com.model.certificate;

import java.util.Date;
// default package
// Generated 2013-8-28 14:07:36 by Hibernate Tools 3.4.0.CR1

/**
 * TBdUsersupplier generated by hbm2java
 */
public class DesignerCertificateInfo implements java.io.Serializable {

	private String fid;
	private String fuserid;
	private String ffiles;
	private String fcompanyname;
	private String findustry;
	private Integer fstatus;
	private Date fcertificatedtime;
	private String fcertificateuserid;
	private Date fcreatetime;
	private Date fupdatetime;
	private  String fremark;

	public DesignerCertificateInfo() {
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFuserid() {
		return fuserid;
	}

	public void setFuserid(String fuserid) {
		this.fuserid = fuserid;
	}

	public String getFfiles() {
		return ffiles;
	}

	public void setFfiles(String ffiles) {
		this.ffiles = ffiles;
	}

	public String getFcompanyname() {
		return fcompanyname;
	}

	public void setFcompanyname(String fcompanyname) {
		this.fcompanyname = fcompanyname;
	}

	public String getFindustry() {
		return findustry;
	}

	public void setFindustry(String findustry) {
		this.findustry = findustry;
	}
	
	public Integer getFstatus() {
		return fstatus;
	}

	public void setFstatus(Integer fstatus) {
		this.fstatus = fstatus;
	}

	public Date getFcertificatedtime() {
		return fcertificatedtime;
	}

	public void setFcertificatedtime(Date fcertificatedtime) {
		this.fcertificatedtime = fcertificatedtime;
	}

	public Date getFcreatetime() {
		return fcreatetime;
	}

	public void setFcreatetime(Date fcreatetime) {
		this.fcreatetime = fcreatetime;
	}

	public String getFcertificateuserid() {
		return fcertificateuserid;
	}

	public void setFcertificateuserid(String fcertificateuserid) {
		this.fcertificateuserid = fcertificateuserid;
	}

	public Date getFupdatetime() {
		return fupdatetime;
	}

	public void setFupdatetime(Date fupdatetime) {
		this.fupdatetime = fupdatetime;
	}

	public String getFremark() {
		return fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}
	

}
