package com.model.productdef;
// default package
// Generated 2013-10-25 13:12:24 by Hibernate Tools 3.4.0.CR1

/**
 * TPdtProductrelation generated by hbm2java
 */
public class Productrelation implements java.io.Serializable {

	private String fid;
	private String fproductid;
	private String fcustomerid;

	public Productrelation() {
	}

	public Productrelation(String fid, String fproductid, String fcustomerid) {
		this.fid = fid;
		this.fproductid = fproductid;
		this.fcustomerid = fcustomerid;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFproductid() {
		return this.fproductid;
	}

	public void setFproductid(String fproductid) {
		this.fproductid = fproductid;
	}

	public String getFcustomerid() {
		return this.fcustomerid;
	}

	public void setFcustomerid(String fcustomerid) {
		this.fcustomerid = fcustomerid;
	}

}
